# Used directories
mkdir -p ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode
mkdir -p ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc
mkdir -p ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/impl
mkdir -p ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/java
mkdir -p ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/reader/impl
mkdir -p ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/writer/impl

# Java RTTI
java -Xmx4G -d64 -cp "${SPUTNIK}/contrib/ClankGenerator/dist/ClankGenerator.jar" clankgenerator.codegenerators.ClankRTTIGenerator -decls ${SPUTNIK}/contrib/JConvert/dist/decl_LLVM39/llvm_declarations.ser -modules org.llvm.bitcode

# Global and static Enums
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Writer/BitWriter.cpp "-nm=_ZN4llvm12BitcodeErrorE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/BitcodeError.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm4bitc19AtomicOrderingCodesE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/AtomicOrderingCodes.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm4bitc21AtomicSynchScopeCodesE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/AtomicSynchScopeCodes.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm4bitc14AttributeCodesE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/AttributeCodes.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm4bitc18AttributeKindCodesE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/AttributeKindCodes.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm4bitc13BinaryOpcodesE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/BinaryOpcodes.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm4bitc8BlockIDsE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/BlockIDs.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMT.cpp "-nm=_ZN4llvm4bitc14BlockInfoCodesE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/BlockInfoCodes.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm4bitc16CallMarkersFlagsE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/CallMarkersFlags.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm4bitc11CastOpcodesE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/CastOpcodes.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm4bitc24ComdatSelectionKindCodesE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/ComdatSelectionKindCodes.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm4bitc14ConstantsCodesE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/ConstantsCodes.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMT.cpp "-nm=_ZN4llvm4bitc14FixedAbbrevIDsE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/FixedAbbrevIDs.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm4bitc13FunctionCodesE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/FunctionCodes.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm4bitc29GlobalValueSummarySymtabCodesE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/GlobalValueSummarySymtabCodes.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm4bitc19IdentificationCodesE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/IdentificationCodes.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm4bitc13MetadataCodesE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/MetadataCodes.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm4bitc11ModuleCodesE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/ModuleCodes.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm4bitc21ModulePathSymtabCodesE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/ModulePathSymtabCodes.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm4bitc20OperandBundleTagCodeE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/OperandBundleTagCode.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm4bitc38OverflowingBinaryOperatorOptionalFlagsE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/OverflowingBinaryOperatorOptionalFlags.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm4bitc34PossiblyExactOperatorOptionalFlagsE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/PossiblyExactOperatorOptionalFlags.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm4bitc13RMWOperationsE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/RMWOperations.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMT.cpp "-nm=_ZN4llvm4bitc16StandardBlockIDsE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/StandardBlockIDs.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMT.cpp "-nm=_ZN4llvm4bitc14StandardWidthsE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/StandardWidths.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm4bitc9TypeCodesE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/TypeCodes.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm4bitc15TypeSymtabCodesE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/TypeSymtabCodes.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm4bitc12UseListCodesE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/UseListCodes.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm4bitc16ValueSymtabCodesE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/ValueSymtabCodes.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp "-nm=_Z14StringEncoding;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/writer/impl/StringEncoding.java

# Global and static CXXRecords, ClassTemplates, ClassTemplateSpecializations
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp "-nm=_ZN4llvm13BitCodeAbbrevE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/BitCodeAbbrev.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp "-nm=_ZN4llvm15BitCodeAbbrevOpE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/BitCodeAbbrevOp.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm21BitcodeDiagnosticInfoE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/BitcodeDiagnosticInfo.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Writer/BitcodeWriterPass.cpp "-nm=_ZN4llvm17BitcodeWriterPassE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/BitcodeWriterPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Serialization/ASTReader.cpp ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitstreamReader.cpp "-nm=_ZN4llvm15BitstreamCursorE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/BitstreamCursor.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitstreamReader.cpp "-nm=_ZN4llvm14BitstreamEntryE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/BitstreamEntry.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitstreamReader.cpp "-nm=_ZN4llvm15BitstreamReaderE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/BitstreamReader.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp "-nm=_ZN4llvm15BitstreamWriterE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/BitstreamWriter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Serialization/ASTReader.cpp "-nm=_ZN4llvm21SimpleBitstreamCursorE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/SimpleBitstreamCursor.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMT.cpp "-nm=_ZN4llvm9isPodLikeINS_15BitCodeAbbrevOpEEE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/isPodLikeBitCodeAbbrevOp.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Writer/BitWriter.cpp "-nm=_ZSt18is_error_code_enumIN4llvm12BitcodeErrorEE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/is_error_code_enumBitcodeError.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN12_GLOBAL__N_124BitcodeErrorCategoryTypeE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/reader/impl/BitcodeErrorCategoryType.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN12_GLOBAL__N_113BitcodeReaderE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/reader/impl/BitcodeReader.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN12_GLOBAL__N_125BitcodeReaderMetadataListE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/reader/impl/BitcodeReaderMetadataList.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN12_GLOBAL__N_122BitcodeReaderValueListE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/reader/impl/BitcodeReaderValueList.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm12_GLOBAL__N_119ConstantPlaceHolderE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/reader/impl/ConstantPlaceHolder.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN12_GLOBAL__N_131ModuleSummaryIndexBitcodeReaderE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/reader/impl/ModuleSummaryIndexBitcodeReader.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm13OperandTraitsINS_12_GLOBAL__N_119ConstantPlaceHolderEEE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/reader/impl/OperandTraitsConstantPlaceHolder.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN12_GLOBAL__N_116PlaceholderQueueE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/reader/impl/PlaceholderQueue.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp "-nm=_ZN12_GLOBAL__N_113BitcodeWriterE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/writer/impl/BitcodeWriter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp "-nm=_ZN12_GLOBAL__N_118IndexBitcodeWriterE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/writer/impl/IndexBitcodeWriter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp "-nm=_ZN12_GLOBAL__N_119ModuleBitcodeWriterE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/writer/impl/ModuleBitcodeWriter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Writer/ValueEnumerator.cpp "-nm=_ZN12_GLOBAL__N_18OrderMapE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/writer/impl/OrderMap.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp ${LLVM_SRC}/llvm/lib/Bitcode/Writer/ValueEnumerator.cpp "-nm=_ZN4llvm15ValueEnumeratorE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/writer/impl/ValueEnumerator.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Writer/BitcodeWriterPass.cpp "-nm=_ZN12_GLOBAL__N_116WriteBitcodePassE;" > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/writer/impl/WriteBitcodePass.java

# Static functions/variables
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitReader.cpp "-nm=_Z16LLVMParseBitcode;_Z17LLVMParseBitcode2;_Z20LLVMGetBitcodeModule;_Z21LLVMGetBitcodeModule2;_Z25LLVMParseBitcodeInContext;_Z26LLVMParseBitcodeInContext2;_Z29LLVMGetBitcodeModuleInContext;_Z30LLVMGetBitcodeModuleInContext2;_ZL17diagnosticHandlerRKN4llvm14DiagnosticInfoEPv;" -static-type=BitReaderStatics -package=org.llvm.bitcode.reader.impl > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/reader/impl/BitReaderStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=Tpl__ZL15convertToStringN4llvm8ArrayRefIyEEjRT_;_BitcodeReader_cpp_Unnamed_enum;_ZL12unrotateSigny;_ZL13ErrorCategory;_ZL13readWideAPIntN4llvm8ArrayRefIyEEj;_ZL15getAttrFromCodey;_ZL17PrintSummaryGUIDs;_ZL17getDecodedLinkagej;_ZL17hasImplicitComdatj;_ZL18getDecodedOrderingj;_ZL20getBitcodeModuleImplSt10unique_ptrIN4llvm12DataStreamerESt14default_deleteIS1_EENS0_9StringRefEPN12_GLOBAL__N_113BitcodeReaderERNS0_11LLVMContextEbb;_ZL20getDecodedCastOpcodej;_ZL20getDecodedSynchScopej;_ZL20getDecodedVisibilityj;_ZL21hasValidBitcodeHeaderRN4llvm15BitstreamCursorE;_ZL22getDecodedBinaryOpcodejPN4llvm4TypeE;_ZL22getDecodedRMWOperationj;_ZL22jumpToValueSymbolTableyRN4llvm15BitstreamCursorE;_ZL22typeCheckLoadStoreInstPN4llvm4TypeES1_;_ZL23getDecodedFastMathFlagsj;_ZL24getDecodedGVSummaryFlagsyy;_ZL24getLazyBitcodeModuleImplOSt10unique_ptrIN4llvm12MemoryBufferESt14default_deleteIS1_EERNS0_11LLVMContextEbb;_ZL25getDecodedDLLStorageClassj;_ZL25getDecodedThreadLocalModej;_ZL25getDecodedUnnamedAddrTypej;_ZL29getDecodedComdatSelectionKindj;_ZL29upgradeDLLImportExportLinkagePN4llvm11GlobalValueEj;_ZL30decodeLLVMAttributesForBitcodeRN4llvm11AttrBuilderEy;_ZL5errorRKSt8functionIFvRKN4llvm14DiagnosticInfoEEESt10error_codeRKNS0_5TwineE;_ZL5errorRN4llvm11LLVMContextERKNS_5TwineE;_ZL5errorRN4llvm11LLVMContextESt10error_codeRKNS_5TwineE;" -static-type=BitcodeReaderStatics -package=org.llvm.bitcode.reader.impl > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/reader/impl/BitcodeReaderStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitstreamReader.cpp "-nm=_ZL20readAbbreviatedFieldRN4llvm15BitstreamCursorERKNS_15BitCodeAbbrevOpE;_ZL20skipAbbreviatedFieldRN4llvm15BitstreamCursorERKNS_15BitCodeAbbrevOpE;" -static-type=BitstreamReaderStatics -package=org.llvm.bitcode.reader.impl > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/reader/impl/BitstreamReaderStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Writer/BitWriter.cpp "-nm=_Z20LLVMWriteBitcodeToFD;_Z22LLVMWriteBitcodeToFile;_Z28LLVMWriteBitcodeToFileHandle;_Z30LLVMWriteBitcodeToMemoryBuffer;" -static-type=BitWriterStatics -package=org.llvm.bitcode.writer.impl > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/writer/impl/BitWriterStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Writer/BitcodeWriterPass.cpp "-nm=_ZL34InitializeWriteBitcodePassPassFlag;_ZL34initializeWriteBitcodePassPassOnceRN4llvm12PassRegistryE;" -static-type=BitcodeWriterPassStatics -package=org.llvm.bitcode.writer.impl > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/writer/impl/BitcodeWriterPassStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp "-nm=_BitcodeWriter_cpp_Unnamed_enum;_ZL10rotateSignx;_ZL13INDEX_VERSION;_ZL15emitSignedInt64RN4llvm15SmallVectorImplIyEEy;_ZL17getEncodedLinkageN4llvm11GlobalValue12LinkageTypesE;_ZL17getEncodedLinkageRKN4llvm11GlobalValueE;_ZL17getStringEncodingPKcj;_ZL18getEncodedOrderingN4llvm14AtomicOrderingE;_ZL18writeInt32ToBufferjRN4llvm15SmallVectorImplIcEERj;_ZL19getAttrKindEncodingN4llvm9Attribute8AttrKindE;_ZL20getEncodedCastOpcodej;_ZL20getEncodedSynchScopeN4llvm20SynchronizationScopeE;_ZL20getEncodedVisibilityRKN4llvm11GlobalValueE;_ZL20getOptimizationFlagsPKN4llvm5ValueE;_ZL21getEncodedUnnamedAddrRKN4llvm11GlobalValueE;_ZL22getEncodedBinaryOpcodej;_ZL22getEncodedRMWOperationN4llvm13AtomicRMWInst5BinOpE;_ZL24getEncodedGVSummaryFlagsN4llvm18GlobalValueSummary7GVFlagsE;_ZL25getEncodedDLLStorageClassRKN4llvm11GlobalValueE;_ZL25getEncodedThreadLocalModeRKN4llvm11GlobalValueE;_ZL28emitDarwinBCHeaderAndTrailerRN4llvm15SmallVectorImplIcEERKNS_6TripleE;_ZL29getEncodedComdatSelectionKindRKN4llvm6ComdatE;" -static-type=BitcodeWriterStatics -package=org.llvm.bitcode.writer.impl > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/writer/impl/BitcodeWriterStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Writer/ValueEnumerator.cpp "-nm=_ZL10orderValuePKN4llvm5ValueERN12_GLOBAL__N_18OrderMapE;_ZL11orderModuleRKN4llvm6ModuleE;_ZL19predictUseListOrderRKN4llvm6ModuleE;_ZL20getMetadataTypeOrderPKN4llvm8MetadataE;_ZL21isIntOrIntVectorValueRKSt4pairIPKN4llvm5ValueEjE;_ZL24predictValueUseListOrderPKN4llvm5ValueEPKNS_8FunctionERN12_GLOBAL__N_18OrderMapERSt6vectorINS_12UseListOrderESaISA_EE;_ZL28predictValueUseListOrderImplPKN4llvm5ValueEPKNS_8FunctionEjRKN12_GLOBAL__N_18OrderMapERSt6vectorINS_12UseListOrderESaISB_EE;_ZL34IncorporateFunctionInfoGlobalBBIDsPKN4llvm8FunctionERNS_8DenseMapIPKNS_10BasicBlockEjNS_12DenseMapInfoIS6_EENS_6detail12DenseMapPairIS6_jEEEE;" -static-type=ValueEnumeratorStatics -package=org.llvm.bitcode.writer.impl > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/writer/impl/ValueEnumeratorStatics.java

# Global functions/variables for namespace as packages
${SPUTNIK}/contrib/JConvert/jclank.sh -body-delegate -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Writer/BitcodeWriterPass.cpp "-nm=_ZN4llvm12isRawBitcodeEPKhS1_;_ZN4llvm15make_error_codeENS_12BitcodeErrorE;_ZN4llvm16WriteIndexToFileERKNS_18ModuleSummaryIndexERNS_11raw_ostreamEPSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES5_IyPNS_18GlobalValueSummaryESt4lessIyESaISt4pairIKySD_EEESE_ISB_ESaISG_IKSB_SK_EEE;_ZN4llvm16isBitcodeWrapperEPKhS1_;_ZN4llvm16parseBitcodeFileENS_15MemoryBufferRefERNS_11LLVMContextE;_ZN4llvm18WriteBitcodeToFileEPKNS_6ModuleERNS_11raw_ostreamEbPKNS_18ModuleSummaryIndexEb;_ZN4llvm20BitcodeErrorCategoryEv;_ZN4llvm20getLazyBitcodeModuleEOSt10unique_ptrINS_12MemoryBufferESt14default_deleteIS1_EERNS_11LLVMContextEb;_ZN4llvm21getModuleSummaryIndexENS_15MemoryBufferRefERKSt8functionIFvRKNS_14DiagnosticInfoEEE;_ZN4llvm21hasGlobalValueSummaryENS_15MemoryBufferRefERKSt8functionIFvRKNS_14DiagnosticInfoEEE;_ZN4llvm22getBitcodeTargetTripleB5cxx11ENS_15MemoryBufferRefERNS_11LLVMContextE;_ZN4llvm23createBitcodeWriterPassERNS_11raw_ostreamEbbb;_ZN4llvm24SkipBitcodeWrapperHeaderERPKhS2_b;_ZN4llvm24getBitcodeProducerStringB5cxx11ENS_15MemoryBufferRefERNS_11LLVMContextE;_ZN4llvm24getStreamedBitcodeModuleENS_9StringRefESt10unique_ptrINS_12DataStreamerESt14default_deleteIS2_EERNS_11LLVMContextE;_ZN4llvm31isBitcodeContainingObjCCategoryENS_15MemoryBufferRefERNS_11LLVMContextE;_ZN4llvm9isBitcodeEPKhS1_;_ZN4llvmL13BWH_SizeFieldE;_ZN4llvmL14BWH_HeaderSizeE;_ZN4llvmL14BWH_MagicFieldE;_ZN4llvmL15BWH_OffsetFieldE;_ZN4llvmL16BWH_CPUTypeFieldE;_ZN4llvmL16BWH_VersionFieldE;" -static-type=BitcodeLlvmGlobals -package=org.llvm.bitcode > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/BitcodeLlvmGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm16parseBitcodeFileENS_15MemoryBufferRefERNS_11LLVMContextE;_ZN4llvm20BitcodeErrorCategoryEv;_ZN4llvm20getLazyBitcodeModuleEOSt10unique_ptrINS_12MemoryBufferESt14default_deleteIS1_EERNS_11LLVMContextEb;_ZN4llvm21getModuleSummaryIndexENS_15MemoryBufferRefERKSt8functionIFvRKNS_14DiagnosticInfoEEE;_ZN4llvm21hasGlobalValueSummaryENS_15MemoryBufferRefERKSt8functionIFvRKNS_14DiagnosticInfoEEE;_ZN4llvm22getBitcodeTargetTripleB5cxx11ENS_15MemoryBufferRefERNS_11LLVMContextE;_ZN4llvm24getBitcodeProducerStringB5cxx11ENS_15MemoryBufferRefERNS_11LLVMContextE;_ZN4llvm24getStreamedBitcodeModuleENS_9StringRefESt10unique_ptrINS_12DataStreamerESt14default_deleteIS2_EERNS_11LLVMContextE;_ZN4llvm31isBitcodeContainingObjCCategoryENS_15MemoryBufferRefERNS_11LLVMContextE;" -static-type=BitcodeReaderLlvmGlobals -package=org.llvm.bitcode.impl > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/impl/BitcodeReaderLlvmGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Writer/BitcodeWriterPass.cpp "-nm=_ZN4llvm23createBitcodeWriterPassERNS_11raw_ostreamEbbb;" -static-type=BitcodeWriterPassLlvmGlobals -package=org.llvm.bitcode.impl > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/impl/BitcodeWriterPassLlvmGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Writer/BitWriter.cpp "-nm=_ZN4llvm12isRawBitcodeEPKhS1_;_ZN4llvm15make_error_codeENS_12BitcodeErrorE;_ZN4llvm16isBitcodeWrapperEPKhS1_;_ZN4llvm24SkipBitcodeWrapperHeaderERPKhS2_b;_ZN4llvm9isBitcodeEPKhS1_;" -static-type=ReaderWriterLlvmGlobals -package=org.llvm.bitcode.impl > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/impl/ReaderWriterLlvmGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp "-nm=_ZN4llvm16WriteIndexToFileERKNS_18ModuleSummaryIndexERNS_11raw_ostreamEPSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES5_IyPNS_18GlobalValueSummaryESt4lessIyESaISt4pairIKySD_EEESE_ISB_ESaISG_IKSB_SK_EEE;_ZN4llvm18WriteBitcodeToFileEPKNS_6ModuleERNS_11raw_ostreamEbPKNS_18ModuleSummaryIndexEb;" -static-type=BitcodeWriterLlvmGlobals -package=org.llvm.bitcode.impl > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/impl/BitcodeWriterLlvmGlobals.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Reader/BitcodeReader.cpp "-nm=_ZN4llvm4bitcE_LLVMBitCodes_h_Unnamed_enum2;" -static-type=BitcGlobals -package=org.llvm.bitcode.bitc > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/bitc/BitcGlobals.java

# Static functions/variables for namespaces as packages
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.bitcode/llvmToClangType ${LLVM_SRC}/llvm/lib/Bitcode/Writer/BitcodeWriterPass.cpp "-nm=_ZN4llvm30initializeWriteBitcodePassPassERNS_12PassRegistryE;" -static-type=BitcodeLlvmStatics -package=org.llvm.bitcode.writer.impl > ${SPUTNIK}/modules/org.llvm.bitcode/src/org/llvm/bitcode/writer/impl/BitcodeLlvmStatics.java

