FILE_NAME = ArrayRefUShort
CLASS_SUFFIX =
VALUE_TYPE = char
BOXED_VALUE_TYPE = Character
VALUE_POINTER = ushort$ptr
VALUE_REFERENCE = ushort$ref
DEFAULT_VALUE = (char)0/*U*/
VECTOR_TYPE = std.vectorUShort
SMALL_VECTOR_TYPE = SmallVectorImplUShort
REVERSE_ITERATOR = std.reverse_iteratorUShort
POINTER_FACTORY_METHOD = create_const_ushort$ptr
CREATE_ARRAY_FROM_ONE_ELT = new$ushort$elem(OneElt)
CREATE_ARRAY_FROM_ELT_CLASS=NativePointer.new$ushort(cls, Length)
TREF_TYPE = char
TREF_DEFAULT_VALUE = (char)0
CALL_STD_COPY = std.copy(begin(), end(), Buff)
CTOR_FROM_ONE_ELEMENT_COMMENT1 =
CTOR_FROM_ONE_ELEMENT_COMMENT2 =
CTOR_FROM_ONE_ELEMENT_COMMENT3 =