FILE_NAME = ArrayRef
CLASS_SUFFIX = <T>
VALUE_TYPE = T
BOXED_VALUE_TYPE = T
VALUE_POINTER = type$ptr<T>
VALUE_REFERENCE = type$ref<T>
DEFAULT_VALUE = ((T) null)
VECTOR_TYPE = std.vector<T>
SMALL_VECTOR_TYPE = SmallVectorImplCommon<T>
REVERSE_ITERATOR = std.reverse_iterator<T>
POINTER_FACTORY_METHOD = create_const_type$ptr
CREATE_ARRAY_FROM_ONE_ELT = java.util.Arrays.asList(OneElt).toArray()
CREATE_ARRAY_FROM_ELT_CLASS=NativePointer.new$T(cls, Length)
TREF_TYPE = Object
TREF_DEFAULT_VALUE = null
CALL_STD_COPY = std.copy(begin(), end(), Buff, isDataPointerLike)
CTOR_FROM_ONE_ELEMENT_COMMENT1 =
CTOR_FROM_ONE_ELEMENT_COMMENT2 =
CTOR_FROM_ONE_ELEMENT_COMMENT3 =