FILE_NAME = ArrayRefDouble
CLASS_SUFFIX =
VALUE_TYPE = double
BOXED_VALUE_TYPE = Double
VALUE_POINTER = double$ptr
VALUE_REFERENCE = double$ref
DEFAULT_VALUE = 0
VECTOR_TYPE = std.vectorDouble
SMALL_VECTOR_TYPE = SmallVectorImplDouble
REVERSE_ITERATOR = std.reverse_iteratorDouble
POINTER_FACTORY_METHOD = create_const_double$ptr
CREATE_ARRAY_FROM_ONE_ELT = new$double$elem(OneElt)
CREATE_ARRAY_FROM_ELT_CLASS=NativePointer.new$double(cls, Length)
TREF_TYPE = double
TREF_DEFAULT_VALUE = 0
CALL_STD_COPY = std.copy(begin(), end(), Buff)
CTOR_FROM_ONE_ELEMENT_COMMENT1 =
CTOR_FROM_ONE_ELEMENT_COMMENT2 =
CTOR_FROM_ONE_ELEMENT_COMMENT3 =