FILE_NAME = ArrayRefBool
CLASS_SUFFIX =
VALUE_TYPE = boolean
BOXED_VALUE_TYPE = Boolean
VALUE_POINTER = bool$ptr
VALUE_REFERENCE = bool$ref
DEFAULT_VALUE = ((boolean) false)
VECTOR_TYPE = std.vectorBool
SMALL_VECTOR_TYPE = SmallVectorImplBool
REVERSE_ITERATOR = std.reverse_iteratorBool
POINTER_FACTORY_METHOD = create_const_bool$ptr
CREATE_ARRAY_FROM_ONE_ELT = new$bool$elem(OneElt)
CREATE_ARRAY_FROM_ELT_CLASS=NativePointer.new$bool(Length)
TREF_TYPE = boolean
TREF_DEFAULT_VALUE = ((boolean) false)
CALL_STD_COPY = std.copy(begin(), end(), Buff)
CTOR_FROM_ONE_ELEMENT_COMMENT1 = //
CTOR_FROM_ONE_ELEMENT_COMMENT2 = //
CTOR_FROM_ONE_ELEMENT_COMMENT3 = //