FILE_NAME = ArrayRefByte$C
CLASS_SUFFIX =
VALUE_TYPE = byte
BOXED_VALUE_TYPE = Byte
VALUE_POINTER = uchar$ptr
VALUE_REFERENCE = uchar$ref
DEFAULT_VALUE = ((byte) 0)
VECTOR_TYPE = std.vectorUChar
SMALL_VECTOR_TYPE = SmallVectorImplUChar
REVERSE_ITERATOR = std.reverse_iteratorUChar
POINTER_FACTORY_METHOD = create_const_uchar$ptr
CREATE_ARRAY_FROM_ONE_ELT = new$uchar$elem(OneElt)
CREATE_ARRAY_FROM_ELT_CLASS=NativePointer.new$uchar(cls, Length)
TREF_TYPE = byte
TREF_DEFAULT_VALUE = ((byte) 0)
CALL_STD_COPY = std.copy(begin(), end(), Buff)
CTOR_FROM_ONE_ELEMENT_COMMENT1 =
CTOR_FROM_ONE_ELEMENT_COMMENT2 =
CTOR_FROM_ONE_ELEMENT_COMMENT3 =