FILE_NAME = DenseMapIteratorTypeBool
CLASS_SUFFIX = <KeyT>
PAIR_TYPE = std.pairTypeBool<KeyT>
KEY_TYPE = KeyT
RAW_KEY_TYPE = Object
VALUE_TYPE = boolean
DENSE_MAP_INFO = DenseMapInfo<KeyT>
IS_DATA_POINTER_LIKE=false
DENSE_MAP = DenseMapTypeBool
