FILE_NAME = DenseMapPtrType
CLASS_SUFFIX = <KeyT, ValueT>
PAIR_TYPE = std.pairPtrType<KeyT, ValueT>
PAIR_NAME = std.pairPtrType
KEY_TYPE = KeyT
RAW_KEY_TYPE = Object
VALUE_TYPE = ValueT
VALUE_CLASS = Class<ValueT>
DENSE_MAP_INFO = DenseMapInfo<KeyT>
DENSE_MAP_BASE = DenseMapBasePtrType<DenseMap<KeyT, ValueT>, KeyT, ValueT>
CREATE_NEW_BUCKET_PAIR = new std.pairPtrType();
