FILE_NAME = DenseMapIteratorIntLong
CLASS_SUFFIX =
PAIR_TYPE = std.pairIntLong
KEY_TYPE = int
RAW_KEY_TYPE = int
VALUE_TYPE = long
DENSE_MAP_INFO = DenseMapInfoInt
IS_DATA_POINTER_LIKE=false
DENSE_MAP = DenseMapIntLong
