FILE_NAME = DenseMapIteratorULongChar
CLASS_SUFFIX =
PAIR_TYPE = std.pairULongChar
KEY_TYPE = long
RAW_KEY_TYPE = long
VALUE_TYPE = byte
DENSE_MAP_INFO = DenseMapInfoULong
IS_DATA_POINTER_LIKE=false
DENSE_MAP = DenseMapULongChar
