FILE_NAME = DenseMapIteratorPtrType
CLASS_SUFFIX = <KeyT, ValueT>
PAIR_TYPE = std.pairPtrType<KeyT, ValueT>
KEY_TYPE = KeyT
RAW_KEY_TYPE = Object
VALUE_TYPE = ValueT
DENSE_MAP_INFO = DenseMapInfo<KeyT>
IS_DATA_POINTER_LIKE=false
DENSE_MAP = DenseMap
