FILE_NAME = DenseMapUIntChar
CLASS_SUFFIX =
PAIR_TYPE = std.pairUIntChar
PAIR_NAME = std.pairUIntChar
KEY_TYPE = int
RAW_KEY_TYPE = int
VALUE_TYPE = byte
VALUE_CLASS = Class<Byte>
DENSE_MAP_INFO = DenseMapInfoUInt
DENSE_MAP_BASE = DenseMapBaseUIntChar<DenseMapUIntChar>
CREATE_NEW_BUCKET_PAIR = new std.pairUIntChar()
