FILE_NAME = DenseMapIteratorIntInt
CLASS_SUFFIX =
PAIR_TYPE = std.pairIntInt
KEY_TYPE = int
RAW_KEY_TYPE = int
VALUE_TYPE = int
DENSE_MAP_INFO = DenseMapInfoInt
IS_DATA_POINTER_LIKE=false
DENSE_MAP = DenseMapIntInt
