FILE_NAME = DenseMapIntLong
CLASS_SUFFIX =
PAIR_TYPE = std.pairIntLong
PAIR_NAME = std.pairIntLong
KEY_TYPE = int
RAW_KEY_TYPE = int
VALUE_TYPE = long
VALUE_CLASS = Class<Long>
DENSE_MAP_INFO = DenseMapInfoInt
DENSE_MAP_BASE = DenseMapBaseIntLong<DenseMapIntLong>
CREATE_NEW_BUCKET_PAIR = new std.pairIntLong()
