FILE_NAME = DenseMapIteratorTypeULong
CLASS_SUFFIX = <KeyT>
PAIR_TYPE = std.pairTypeULong<KeyT>
KEY_TYPE = KeyT
RAW_KEY_TYPE = Object
VALUE_TYPE = long
DENSE_MAP_INFO = DenseMapInfo<KeyT>
IS_DATA_POINTER_LIKE=false
DENSE_MAP = DenseMapTypeULong
