FILE_NAME = DenseMapIteratorTypeLong
CLASS_SUFFIX = <KeyT>
PAIR_TYPE = std.pairTypeLong<KeyT>
KEY_TYPE = KeyT
RAW_KEY_TYPE = Object
VALUE_TYPE = long
DENSE_MAP_INFO = DenseMapInfo<KeyT>
IS_DATA_POINTER_LIKE=false
DENSE_MAP = DenseMapTypeLong
