FILE_NAME = DenseMapIteratorTypeUShort
CLASS_SUFFIX = <KeyT>
PAIR_TYPE = std.pairTypeUShort<KeyT>
KEY_TYPE = KeyT
RAW_KEY_TYPE = Object
VALUE_TYPE = char
DENSE_MAP_INFO = DenseMapInfo<KeyT>
IS_DATA_POINTER_LIKE=false
DENSE_MAP = DenseMapTypeUShort
