FILE_NAME = DenseMapIntUInt
CLASS_SUFFIX =
PAIR_TYPE = std.pairIntUInt
PAIR_NAME = std.pairIntUInt
KEY_TYPE = int
RAW_KEY_TYPE = int
VALUE_TYPE = /*uint*/int
VALUE_CLASS = Class<Integer>
DENSE_MAP_INFO = DenseMapInfoInt
DENSE_MAP_BASE = DenseMapBaseIntUInt<DenseMapIntUInt>
CREATE_NEW_BUCKET_PAIR = new std.pairIntUInt()