FILE_NAME = DenseMapIteratorTypeInt
CLASS_SUFFIX = <KeyT>
PAIR_TYPE = std.pairTypeInt<KeyT>
KEY_TYPE = KeyT
RAW_KEY_TYPE = Object
VALUE_TYPE = int
DENSE_MAP_INFO = DenseMapInfo<KeyT>
IS_DATA_POINTER_LIKE=false
DENSE_MAP = DenseMapTypeInt
