FILE_NAME = ImmutableSetRef
CLASS_SUFFIX = <KeyT>
CLASS_TYPE = ImmutableSetRef<KeyT>
SET_TYPE = ImmutableSet<KeyT>
AVL_TREE_TYPE = ImutAVLTreeTypeBoolType<KeyT, KeyT>
AVL_FACTORY_TYPE = ImutAVLFactoryTypeBoolType<KeyT, KeyT>
AVL_VALUE_ITER_TYPE = ImutAVLValueIteratorTypeBoolType<KeyT>
KEY_TYPE = KeyT
BOXED_KEY_TYPE = KeyT
JAVA_ITERATOR = JavaIterator<KeyT>