FILE_NAME = ImmutableMapPtrUInt
CLASS_SUFFIX = <KeyT>
CLASS_TYPE = ImmutableMapPtrUInt<KeyT>
PAIR_TYPE = std.pairTypeUInt<KeyT>
AVL_TREE_TYPE = ImutAVLTreePtrUIntType<KeyT, std.pairTypeUInt<KeyT>>
AVL_FACTORY_TYPE = ImutAVLFactoryPtrUIntType<KeyT, std.pairTypeUInt<KeyT>>
AVL_VALUE_ITER_TYPE = ImutAVLValueIteratorPtrUIntType<std.pairTypeUInt<KeyT>>
KEY_VALUE_INFO = ImutKeyValueInfo$PtrUInt<KeyT>
KEY_TYPE = KeyT
DATA_TYPE = /*uint*/int
LOOKUP_TYPE = uint$ptr
LOOKUP_RETURN_IMPL = uint$ptr$inout
CALLBACK_FUNC_TYPE = TypeUInt2Void<KeyT>
JAVA_ITERATOR = JavaIterator<std.pairTypeUInt<KeyT>>
