FILE_NAME = ImmutableSetPtr
CLASS_SUFFIX = <KeyT>
CLASS_TYPE = ImmutableSetPtr<KeyT>
AVL_TREE_TYPE = ImutAVLTreePtrBoolPtr<KeyT, KeyT>
AVL_FACTORY_TYPE = ImutAVLFactoryPtrBoolPtr<KeyT, KeyT>
AVL_VALUE_ITER_TYPE = ImutAVLValueIteratorPtrBoolPtr<KeyT>
CONTAINER_INFO = ImutContainerInfoT$P<KeyT>
KEY_TYPE = KeyT
CALLBACK_FUNC_TYPE = Type2Void<KeyT>
BOXED_KEY_TYPE = KeyT
JAVA_ITERATOR = JavaIterator<KeyT>