FILE_NAME = ImmutableSet
CLASS_SUFFIX = <KeyT>
CLASS_TYPE = ImmutableSet<KeyT>
AVL_TREE_TYPE = ImutAVLTreeTypeBoolType<KeyT, KeyT>
AVL_FACTORY_TYPE = ImutAVLFactoryTypeBoolType<KeyT, KeyT>
AVL_VALUE_ITER_TYPE = ImutAVLValueIteratorTypeBoolType<KeyT>
CONTAINER_INFO = ImutContainerInfo<KeyT>
KEY_TYPE = KeyT
CALLBACK_FUNC_TYPE = Type2Void<KeyT>
BOXED_KEY_TYPE = KeyT
JAVA_ITERATOR = JavaIterator<KeyT>