FILE_NAME = ImmutableMap
CLASS_SUFFIX = <KeyT, DataT>
CLASS_TYPE = ImmutableMap<KeyT, DataT>
PAIR_TYPE = std.pairTypeType<KeyT, DataT>
AVL_TREE_TYPE = ImutAVLTree<KeyT, DataT, std.pairTypeType<KeyT, DataT>>
AVL_FACTORY_TYPE = ImutAVLFactory<KeyT, DataT, std.pairTypeType<KeyT, DataT>>
AVL_VALUE_ITER_TYPE = ImutAVLValueIterator<std.pairTypeType<KeyT, DataT>>
KEY_VALUE_INFO = ImutKeyValueInfo<KeyT, DataT, std.pairTypeType<KeyT, DataT>>
KEY_TYPE = KeyT
DATA_TYPE = DataT
LOOKUP_TYPE = type$ptr<DataT> /*P*/
LOOKUP_RETURN_IMPL = type$ptr$inout<DataT>
CALLBACK_FUNC_TYPE = TypeType2Void<KeyT, DataT>
JAVA_ITERATOR = JavaIterator<std.pairTypeType<KeyT, DataT>>