FILE_NAME = ImmutableSetRefChar
CLASS_SUFFIX =
CLASS_TYPE = ImmutableSetRefChar
SET_TYPE = ImmutableSetChar
AVL_TREE_TYPE = ImutAVLTreeCharBoolChar
AVL_FACTORY_TYPE = ImutAVLFactoryCharBoolChar
AVL_VALUE_ITER_TYPE = ImutAVLValueIteratorCharBoolChar
KEY_TYPE = byte
BOXED_KEY_TYPE = Byte
JAVA_ITERATOR = JavaIteratorChar