FILE_NAME = ImmutableMapUIntPtr
CLASS_SUFFIX = <DataT>
CLASS_TYPE = ImmutableMapUIntPtr<DataT>
PAIR_TYPE = std.pairUIntType<DataT>
AVL_TREE_TYPE = ImutAVLTreeUIntPtrType<DataT, std.pairUIntType<DataT>>
AVL_FACTORY_TYPE = ImutAVLFactoryUIntPtrType<DataT, std.pairUIntType<DataT>>
AVL_VALUE_ITER_TYPE = ImutAVLValueIteratorUIntPtrType<std.pairUIntType<DataT>>
KEY_VALUE_INFO = ImutKeyValueInfo$UIntPtr<DataT>
KEY_TYPE = /*uint*/int
DATA_TYPE = DataT
LOOKUP_TYPE = type$ptr<DataT> /*P*/
LOOKUP_RETURN_IMPL = type$ptr$inout<DataT>
CALLBACK_FUNC_TYPE = UIntType2Void<DataT>
JAVA_ITERATOR = JavaIterator<std.pairUIntType<DataT>>
