FILE_NAME = ImutAVLFactoryTypePtrType
CLASS_SUFFIX = </*typename ImutInfo*/ KeyT, DataT, ValT>
AVL_TREE_TYPE = ImutAVLTreeTypePtrType<KeyT, DataT, ValT>
AVL_FACTORY_TYPE = ImutAVLFactoryTypePtrType<KeyT, DataT, ValT>
AVL_GENERIC_ITER_TYPE = ImutAVLTreeGenericIteratorTypePtrType<KeyT, DataT, ValT>
AVL_ORDERED_ITER_TYPE = ImutAVLTreeInOrderIteratorTypePtrType<KeyT, DataT, ValT>
INFO_TYPE = ImutAVLTreeInfoTypePtrType<KeyT, DataT, ValT>
KEY_TYPE = KeyT
DATA_TYPE = DataT
VALUE_TYPE = ValT