FILE_NAME = ImutAVLTreeInOrderIteratorIntBoolInt
CLASS_SUFFIX = 
AVL_TREE_TYPE = ImutAVLTreeIntBoolInt
AVL_GENERIC_ITER_TYPE = ImutAVLTreeGenericIteratorIntBoolInt
AVL_ORDERED_ITER_TYPE = ImutAVLTreeInOrderIteratorIntBoolInt