FILE_NAME = ImutAVLTreePtrBoolPtr
CLASS_SUFFIX = </*typename ImutInfo*/ KeyT, ValT>
AVL_TREE_TYPE = ImutAVLTreePtrBoolPtr<KeyT, ValT>
AVL_FACTORY_TYPE = ImutAVLFactoryPtrBoolPtr<KeyT, ValT>
AVL_GENERIC_ITER_TYPE = ImutAVLTreeGenericIteratorPtrBoolPtr<KeyT, ValT>
AVL_ORDERED_ITER_TYPE = ImutAVLTreeInOrderIteratorPtrBoolPtr<KeyT, ValT>
INFO_TYPE = ImutAVLTreeInfoPtrBoolPtr<KeyT, ValT>
CALLBACL_FUNC_TYPE = Type2Void<ValT>
KEY_TYPE = KeyT
DATA_TYPE = boolean
VALUE_TYPE = ValT
CLONE_VALUE_IMPL = V