FILE_NAME = ImutAVLFactoryIntBoolInt
CLASS_SUFFIX = 
AVL_TREE_TYPE = ImutAVLTreeIntBoolInt
AVL_FACTORY_TYPE = ImutAVLFactoryIntBoolInt
AVL_GENERIC_ITER_TYPE = ImutAVLTreeGenericIteratorIntBoolInt
AVL_ORDERED_ITER_TYPE = ImutAVLTreeInOrderIteratorIntBoolInt
INFO_TYPE = ImutAVLTreeInfoIntBoolInt
KEY_TYPE = int
DATA_TYPE = boolean
VALUE_TYPE = int