FILE_NAME = ImutAVLTreeUIntPtrType
CLASS_SUFFIX = </*typename ImutInfo*/ DataT, ValT>
AVL_TREE_TYPE = ImutAVLTreeUIntPtrType<DataT, ValT>
AVL_FACTORY_TYPE = ImutAVLFactoryUIntPtrType<DataT, ValT>
AVL_GENERIC_ITER_TYPE = ImutAVLTreeGenericIteratorUIntPtrType<DataT, ValT>
AVL_ORDERED_ITER_TYPE = ImutAVLTreeInOrderIteratorUIntPtrType<DataT, ValT>
INFO_TYPE = ImutAVLTreeInfoUIntPtrType<DataT, ValT>
CALLBACL_FUNC_TYPE = Type2Void<ValT>
KEY_TYPE = /*uint*/int
DATA_TYPE = DataT
VALUE_TYPE = ValT
CLONE_VALUE_IMPL = Native.$tryClone(V)