FILE_NAME = ImutAVLTreeGenericIteratorLongBoolLong
CLASS_SUFFIX = 
AVL_TREE_TYPE = ImutAVLTreeLongBoolLong
AVL_TREE_CLASS_NAME = ImutAVLTreeLongBoolLong
AVL_GENERIC_ITER_TYPE = ImutAVLTreeGenericIteratorLongBoolLong