FILE_NAME = ImutAVLFactoryCharBoolChar
CLASS_SUFFIX = 
AVL_TREE_TYPE = ImutAVLTreeCharBoolChar
AVL_FACTORY_TYPE = ImutAVLFactoryCharBoolChar
AVL_GENERIC_ITER_TYPE = ImutAVLTreeGenericIteratorCharBoolChar
AVL_ORDERED_ITER_TYPE = ImutAVLTreeInOrderIteratorCharBoolChar
INFO_TYPE = ImutAVLTreeInfoCharBoolChar
KEY_TYPE = byte
DATA_TYPE = boolean
VALUE_TYPE = byte