FILE_NAME = ImutAVLFactoryUIntBoolUInt
CLASS_SUFFIX = 
AVL_TREE_TYPE = ImutAVLTreeUIntBoolUInt
AVL_FACTORY_TYPE = ImutAVLFactoryUIntBoolUInt
AVL_GENERIC_ITER_TYPE = ImutAVLTreeGenericIteratorUIntBoolUInt
AVL_ORDERED_ITER_TYPE = ImutAVLTreeInOrderIteratorUIntBoolUInt
INFO_TYPE = ImutAVLTreeInfoUIntBoolUInt
KEY_TYPE = /*uint*/int
DATA_TYPE = boolean
VALUE_TYPE = /*uint*/int