FILE_NAME = ImutAVLValueIteratorLongBoolLong
CLASS_SUFFIX = 
ADAPTOR_BASE = iterator_adaptor_base$Long_type<ImutAVLValueIteratorLongBoolLong, ImutAVLTreeInOrderIteratorLongBoolLong, std.bidirectional_iterator_tag>
CLASS_TYPE = ImutAVLValueIteratorLongBoolLong
AVL_TREE_TYPE = ImutAVLTreeLongBoolLong
AVL_ORDERED_ITER_NAME = ImutAVLTreeInOrderIteratorLongBoolLong
VALUE_TYPE = long