FILE_NAME = ImutAVLFactoryPtrBoolPtr
CLASS_SUFFIX = </*typename ImutInfo*/ KeyT, ValT>
AVL_TREE_TYPE = ImutAVLTreePtrBoolPtr<KeyT, ValT>
AVL_FACTORY_TYPE = ImutAVLFactoryPtrBoolPtr<KeyT, ValT>
AVL_GENERIC_ITER_TYPE = ImutAVLTreeGenericIteratorPtrBoolPtr<KeyT, ValT>
AVL_ORDERED_ITER_TYPE = ImutAVLTreeInOrderIteratorPtrBoolPtr<KeyT, ValT>
INFO_TYPE = ImutAVLTreeInfoPtrBoolPtr<KeyT, ValT>
KEY_TYPE = KeyT
DATA_TYPE = boolean
VALUE_TYPE = ValT