FILE_NAME = ImutAVLTreeGenericIteratorIntBoolInt
CLASS_SUFFIX = 
AVL_TREE_TYPE = ImutAVLTreeIntBoolInt
AVL_TREE_CLASS_NAME = ImutAVLTreeIntBoolInt
AVL_GENERIC_ITER_TYPE = ImutAVLTreeGenericIteratorIntBoolInt