FILE_NAME = MapVectorUIntType
CLASS_SUFFIX = <ValueT>
MAP_TYPE = DenseMapUIntUInt
MAP_ITER = DenseMapIteratorUIntUInt
MAP_PAIR = std.pairUIntUInt
VECTOR_TYPE = std.vector<std.pairUIntType<ValueT>>
VECTOR_ITER = std.vector.iterator<std.pairUIntType<ValueT>>
VECTOR_REVERSE_ITER = std.reverse_iterator<std.pairUIntType<ValueT>>
VECTOR_PAIR = std.pairUIntType<ValueT>
KEY_TYPE = /*uint*/int
VALUE_TYPE = ValueT
VALUE_REFERENCE_TYPE = type$ref<ValueT>
IS_DATA_POINTER_LIKE = false
DEFAULT_VALUE = (ValueT)$Clone((NativeCloneable)defaultValue)
DENSE_MAP_INFO = DenseMapInfoUInt
DEFAULT_DENSE_MAP_INFO = DenseMapInfoUInt.$Info()
EMPTY_DEFAULT_KEY=0
EMPTY_DEFAULT_VALUE=defaultValue
ASSERT_DEFAULT_VALUE= (defaultValue instanceof NativeCloneable) && NativeTrace.assertDefaultValue(defaultValue)
