FILE_NAME = SmallDenseMapTypeInt
CLASS_SUFFIX = <KeyT>
PAIR_TYPE = std.pairTypeInt<KeyT>
PAIR_NAME = std.pairTypeInt
KEY_TYPE = KeyT
RAW_KEY_TYPE = Object
VALUE_TYPE = int
DENSE_MAP_INFO = DenseMapInfo<KeyT>
DENSE_MAP_BASE = DenseMapBaseTypeInt<SmallDenseMapTypeInt<KeyT>, KeyT>
