FILE_NAME = SmallDenseMapTypeBool
CLASS_SUFFIX = <KeyT>
PAIR_TYPE = std.pairTypeBool<KeyT>
PAIR_NAME = std.pairTypeBool
KEY_TYPE = KeyT
RAW_KEY_TYPE = Object
VALUE_TYPE = boolean
DENSE_MAP_INFO = DenseMapInfo<KeyT>
DENSE_MAP_BASE = DenseMapBaseTypeBool<SmallDenseMapTypeBool<KeyT>, KeyT>