# Used directories
mkdir -p ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis
mkdir -p ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses
mkdir -p ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/analyze_format_string
mkdir -p ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/analyze_format_string/impl
mkdir -p ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/analyze_printf
mkdir -p ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/analyze_scanf
mkdir -p ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/consumed
mkdir -p ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/llvm
mkdir -p ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/reachable_code
mkdir -p ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety
mkdir -p ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/impl
mkdir -p ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/lexpr
mkdir -p ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/sx
mkdir -p ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til
mkdir -p ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/ThreadSafetyTIL
mkdir -p ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyze_format_string/impl
mkdir -p ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/consumed/impl
mkdir -p ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/domainspecific
mkdir -p ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/domainspecific/ento
mkdir -p ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl
mkdir -p ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/llvm
mkdir -p ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/llvm/impl
mkdir -p ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/support
mkdir -p ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/threadSafety/impl

# Global and static Enums
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/FormatString.cpp "-nm=_ZN5clang21analyze_format_string15PositionContextE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/analyze_format_string/PositionContext.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/Consumed.cpp "-nm=_ZN5clang8consumed13ConsumedStateE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/consumed/ConsumedState.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ReachableCode.cpp "-nm=_ZN5clang14reachable_code15UnreachableKindE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/reachable_code/UnreachableKind.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN5clang12threadSafety10AccessKindE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/AccessKind.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN5clang12threadSafety13LockErrorKindE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/LockErrorKind.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN5clang12threadSafety8LockKindE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/LockKind.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN5clang12threadSafety22ProtectedOperationKindE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/ProtectedOperationKind.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til16TIL_BinaryOpcodeE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/TIL_BinaryOpcode.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til14TIL_CastOpcodeE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/TIL_CastOpcode.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til10TIL_OpcodeE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/TIL_Opcode.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til15TIL_UnaryOpcodeE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/TIL_UnaryOpcode.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/Consumed.cpp "-nm=_ZN5clang8consumed11EffectiveOpE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/consumed/impl/EffectiveOp.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN12_GLOBAL__N_112CFGBlockSideE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/CFGBlockSide.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/UninitializedValues.cpp "-nm=_Z5Value;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/Value.java

# Global and static CXXRecords, ClassTemplates, ClassTemplateSpecializations
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/AnalysisDeclContext.cpp "-nm=_ZN5clang19AnalysisDeclContextE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/AnalysisDeclContext.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/AnalysisDeclContext.cpp "-nm=_ZN5clang26AnalysisDeclContextManagerE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/AnalysisDeclContextManager.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp "-nm=_ZN5clang9BlockEdgeE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/BlockEdge.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp "-nm=_ZN5clang13BlockEntranceE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/BlockEntrance.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ProgramPoint.cpp "-nm=_ZN5clang9BlockExitE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/BlockExit.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/AnalysisDeclContext.cpp "-nm=_ZN5clang22BlockInvocationContextE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/BlockInvocationContext.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/AnalysisDeclContext.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN5clang3CFGE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/CFG.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN5clang19CFGAutomaticObjDtorE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/CFGAutomaticObjDtor.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN5clang11CFGBaseDtorE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/CFGBaseDtor.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN5clang8CFGBlockE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/CFGBlock.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN5clang11CFGCallbackE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/CFGCallback.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN5clang13CFGDeleteDtorE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/CFGDeleteDtor.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN5clang10CFGElementE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/CFGElement.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Core/CallEvent.cpp "-nm=_ZN5clang15CFGImplicitDtorE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/CFGImplicitDtor.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN5clang14CFGInitializerE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/CFGInitializer.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN5clang13CFGMemberDtorE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/CFGMemberDtor.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN5clang15CFGNewAllocatorE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/CFGNewAllocator.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN5clang7CFGStmtE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/CFGStmt.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFGStmtMap.cpp "-nm=_ZN5clang10CFGStmtMapE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/CFGStmtMap.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN5clang16CFGTemporaryDtorE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/CFGTemporaryDtor.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN5clang13CFGTerminatorE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/CFGTerminator.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngineCallAndReturn.cpp "-nm=_ZN5clang9CallEnterE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/CallEnter.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ProgramPoint.cpp "-nm=_ZN5clang13CallExitBeginE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/CallExitBegin.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp "-nm=_ZN5clang11CallExitEndE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/CallExitEnd.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CallGraph.cpp "-nm=_ZN5clang9CallGraphE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/CallGraph.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CallGraph.cpp "-nm=_ZN5clang13CallGraphNodeE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/CallGraphNode.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CodeInjector.cpp "-nm=_ZN5clang12CodeInjectorE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/CodeInjector.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp "-nm=_ZN5clang12EpsilonPointE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/EpsilonPoint.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp "-nm=_ZN5clang17ImplicitCallPointE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/ImplicitCallPoint.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ProgramPoint.cpp "-nm=_ZN5clang13LocationCheckE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/LocationCheck.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/AnalysisDeclContext.cpp "-nm=_ZN5clang15LocationContextE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/LocationContext.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/AnalysisDeclContext.cpp "-nm=_ZN5clang22LocationContextManagerE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/LocationContextManager.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/AnalysisDeclContext.cpp "-nm=_ZN5clang15ManagedAnalysisE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/ManagedAnalysis.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Core/CheckerManager.cpp "-nm=_ZN5clang13PostConditionE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/PostCondition.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp "-nm=_ZN5clang16PostImplicitCallE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/PostImplicitCall.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp "-nm=_ZN5clang15PostInitializerE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/PostInitializer.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp "-nm=_ZN5clang10PostLValueE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/PostLValue.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp "-nm=_ZN5clang8PostLoadE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/PostLoad.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp "-nm=_ZN5clang8PostStmtE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/PostStmt.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Core/PathDiagnostic.cpp "-nm=_ZN5clang24PostStmtPurgeDeadSymbolsE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/PostStmtPurgeDeadSymbols.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp "-nm=_ZN5clang9PostStoreE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/PostStore.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp "-nm=_ZN5clang15PreImplicitCallE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/PreImplicitCall.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ProgramPoint.cpp "-nm=_ZN5clang7PreLoadE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/PreLoad.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp "-nm=_ZN5clang7PreStmtE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/PreStmt.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngineC.cpp "-nm=_ZN5clang23PreStmtPurgeDeadSymbolsE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/PreStmtPurgeDeadSymbols.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ProgramPoint.cpp "-nm=_ZN5clang8PreStoreE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/PreStore.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngineCallAndReturn.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ProgramPoint.cpp "-nm=_ZN5clang12ProgramPointE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/ProgramPoint.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ProgramPoint.cpp "-nm=_ZN5clang15ProgramPointTagE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/ProgramPointTag.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/AnalysisDeclContext.cpp "-nm=_ZN5clang12ScopeContextE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/ScopeContext.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ProgramPoint.cpp "-nm=_ZN5clang21SimpleProgramPointTagE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/SimpleProgramPointTag.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/AnalysisDeclContext.cpp "-nm=_ZN5clang17StackFrameContextE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/StackFrameContext.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp "-nm=_ZN5clang9StmtPointE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/StmtPoint.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/AnalysisDeclContext.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFGReachabilityAnalysis.cpp "-nm=_ZN5clang35CFGReverseBlockReachabilityAnalysisE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/CFGReverseBlockReachabilityAnalysis.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/Dominators.cpp "-nm=_ZN5clang13DominatorTreeE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/DominatorTree.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Checkers/DeadStoresChecker.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/LiveVariables.cpp "-nm=_ZN5clang13LiveVariablesE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/LiveVariables.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/LiveVariables.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/PostOrderCFGView.cpp "-nm=_ZN5clang16PostOrderCFGViewE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/PostOrderCFGView.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/PseudoConstantAnalysis.cpp "-nm=_ZN5clang22PseudoConstantAnalysisE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/PseudoConstantAnalysis.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/LiveVariables.cpp "-nm=_ZN5clang20RelaxedLiveVariablesE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/RelaxedLiveVariables.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Sema/AnalysisBasedWarnings.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/UninitializedValues.cpp "-nm=_ZN5clang9UninitUseE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/UninitUse.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Sema/AnalysisBasedWarnings.cpp "-nm=_ZN5clang28UninitVariablesAnalysisStatsE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/UninitVariablesAnalysisStats.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/UninitializedValues.cpp "-nm=_ZN5clang22UninitVariablesHandlerE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/UninitVariablesHandler.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/FormatString.cpp "-nm=_ZN5clang21analyze_format_string7ArgTypeE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/analyze_format_string/ArgType.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/FormatString.cpp "-nm=_ZN5clang21analyze_format_string19ConversionSpecifierE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/analyze_format_string/ConversionSpecifier.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/FormatString.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ScanfFormatString.cpp "-nm=_ZN5clang21analyze_format_string15FormatSpecifierE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/analyze_format_string/FormatSpecifier.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/FormatString.cpp "-nm=_ZN5clang21analyze_format_string19FormatStringHandlerE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/analyze_format_string/FormatStringHandler.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/FormatString.cpp "-nm=_ZN5clang21analyze_format_string14LengthModifierE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/analyze_format_string/LengthModifier.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/FormatString.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ScanfFormatString.cpp "-nm=_ZN5clang21analyze_format_string14OptionalAmountE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/analyze_format_string/OptionalAmount.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ScanfFormatString.cpp "-nm=_ZN5clang21analyze_format_string12OptionalFlagE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/analyze_format_string/OptionalFlag.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/FormatString.cpp "-nm=_ZN5clang14analyze_printf25PrintfConversionSpecifierE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/analyze_printf/PrintfConversionSpecifier.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/PrintfFormatString.cpp "-nm=_ZN5clang14analyze_printf15PrintfSpecifierE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/analyze_printf/PrintfSpecifier.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/tools/extra/clang-tidy/cert/StrToNumCheck.cpp "-nm=_ZN5clang13analyze_scanf24ScanfConversionSpecifierE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/analyze_scanf/ScanfConversionSpecifier.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ScanfFormatString.cpp "-nm=_ZN5clang13analyze_scanf14ScanfSpecifierE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/analyze_scanf/ScanfSpecifier.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Sema/AnalysisBasedWarnings.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/Consumed.cpp "-nm=_ZN5clang8consumed16ConsumedAnalyzerE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/consumed/ConsumedAnalyzer.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/Consumed.cpp "-nm=_ZN5clang8consumed17ConsumedBlockInfoE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/consumed/ConsumedBlockInfo.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/Consumed.cpp "-nm=_ZN5clang8consumed16ConsumedStateMapE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/consumed/ConsumedStateMap.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Sema/AnalysisBasedWarnings.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/Consumed.cpp "-nm=_ZN5clang8consumed27ConsumedWarningsHandlerBaseE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/consumed/ConsumedWarningsHandlerBase.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/Dominators.cpp "-nm=_ZN4llvm11GraphTraitsIPNS_15DomTreeNodeBaseIN5clang8CFGBlockEEEEE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/llvm/GraphTraitsDomTreeNodeBase\$CFGBlock\$P.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/Dominators.cpp "-nm=_ZN4llvm11GraphTraitsIPN5clang13DominatorTreeEEE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/llvm/GraphTraitsDominatorTree\$P.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Sema/AnalysisBasedWarnings.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ReachableCode.cpp "-nm=_ZN5clang14reachable_code8CallbackE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/reachable_code/Callback.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyCommon.cpp "-nm=_ZN5clang12threadSafety10CFGVisitorE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/CFGVisitor.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyCommon.cpp "-nm=_ZN5clang12threadSafety9CFGWalkerE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/CFGWalker.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN5clang12threadSafety14CapabilityExprE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/CapabilityExpr.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN5clang12threadSafety17CopyOnWriteVectorE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/CopyOnWriteVector.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyCommon.cpp "-nm=_ZN5clang12threadSafety12SExprBuilderE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/SExprBuilder.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN5clang12threadSafety19ThreadSafetyHandlerE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/ThreadSafetyHandler.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyLogical.cpp "-nm=_ZN5clang12threadSafety5lexpr3AndE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/lexpr/And.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyLogical.cpp "-nm=_ZN5clang12threadSafety5lexpr5BinOpE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/lexpr/BinOp.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyLogical.cpp "-nm=_ZN5clang12threadSafety5lexpr5LExprE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/lexpr/LExpr.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyLogical.cpp "-nm=_ZN5clang12threadSafety5lexpr3NotE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/lexpr/Not.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyLogical.cpp "-nm=_ZN5clang12threadSafety5lexpr2OrE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/lexpr/Or.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyLogical.cpp "-nm=_ZN5clang12threadSafety5lexpr8TerminalE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/lexpr/Terminal.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til5AllocE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/Alloc.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til5ApplyE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/Apply.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til8ArrayAddE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/ArrayAdd.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til10ArrayIndexE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/ArrayIndex.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til10BasicBlockE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/BasicBlock.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til8BinaryOpE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/BinaryOp.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til6BranchE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/Branch.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til4CallE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/Call.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til4CastE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/Cast.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til4CodeE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/Code.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til10ComparatorE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/Comparator.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til15CopyReducerBaseE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/CopyReducerBase.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til16EqualsComparatorE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/EqualsComparator.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til5FieldE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/Field.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til8FunctionE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/Function.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til6FutureE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/Future.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til4GotoE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/Goto.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til10IdentifierE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/Identifier.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til10IfThenElseE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/IfThenElse.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til3LetE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/Let.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til7LiteralE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/Literal.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til10LiteralPtrE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/LiteralPtr.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til8LiteralTE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/LiteralT.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til4LoadE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/Load.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til15MatchComparatorE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/MatchComparator.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN5clang12threadSafety3til12MemRegionRefE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/MemRegionRef.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til3PhiE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/Phi.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til13PrettyPrinterE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/PrettyPrinter.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til7ProjectE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/Project.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til6ReturnE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/Return.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til6SApplyE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/SApply.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til4SCFGE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/SCFG.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til5SExprE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/SExpr.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til9SFunctionE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/SFunction.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN5clang12threadSafety3til11SimpleArrayE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/SimpleArray.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til17SimpleReducerBaseE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/SimpleReducerBase.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN5clang12threadSafety3til10StdPrinterE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/StdPrinter.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til5StoreE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/Store.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til10TerminatorE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/Terminator.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til9TraversalE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/Traversal.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til7UnaryOpE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/UnaryOp.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til9UndefinedE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/Undefined.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til9ValueTypeE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/ValueType.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til8VariableE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/Variable.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til12VisitReducerE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/VisitReducer.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til16VisitReducerBaseE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/VisitReducerBase.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til8WildcardE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/Wildcard.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/FormatString.cpp "-nm=_ZN5clang21analyze_format_string15SpecifierResultE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyze_format_string/impl/SpecifierResult.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/Consumed.cpp "-nm=_ZN5clang8consumed19ConsumedStmtVisitorE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/consumed/impl/ConsumedStmtVisitor.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/Consumed.cpp "-nm=_ZN5clang8consumed15PropagationInfoE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/consumed/impl/PropagationInfo.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ObjCNoReturn.cpp "-nm=_ZN5clang12ObjCNoReturnE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/domainspecific/ObjCNoReturn.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/BodyFarm.cpp "-nm=_ZN12_GLOBAL__N_18ASTMakerE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/ASTMaker.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN12_GLOBAL__N_113AddStmtChoiceE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/AddStmtChoice.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN12_GLOBAL__N_117BlockScopePosPairE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/BlockScopePosPair.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/BodyFarm.cpp "-nm=_ZN5clang8BodyFarmE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/BodyFarm.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN12_GLOBAL__N_112BuildLocksetE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/BuildLockset.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN12_GLOBAL__N_112CFGBlockInfoE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/CFGBlockInfo.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN12_GLOBAL__N_123CFGBlockTerminatorPrintE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/CFGBlockTerminatorPrint.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/UninitializedValues.cpp "-nm=_ZN12_GLOBAL__N_114CFGBlockValuesE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/CFGBlockValues.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN12_GLOBAL__N_110CFGBuilderE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/CFGBuilder.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CallGraph.cpp "-nm=_ZN12_GLOBAL__N_19CGBuilderE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/CGBuilder.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN12_GLOBAL__N_110CapExprSetE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/CapExprSet.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/UninitializedValues.cpp "-nm=_ZN12_GLOBAL__N_112ClassifyRefsE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/ClassifyRefs.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ReachableCode.cpp "-nm=_ZN12_GLOBAL__N_112DeadCodeScanE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/DeadCodeScan.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/UninitializedValues.cpp "-nm=_ZN12_GLOBAL__N_111DeclToIndexE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/DeclToIndex.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN12_GLOBAL__N_19FactEntryE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/FactEntry.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN12_GLOBAL__N_111FactManagerE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/FactManager.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN12_GLOBAL__N_17FactSetE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/FactSet.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/AnalysisDeclContext.cpp "-nm=_ZN12_GLOBAL__N_125FindBlockDeclRefExprsValsE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/FindBlockDeclRefExprsVals.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/UninitializedValues.cpp "-nm=_ZN12_GLOBAL__N_113FindVarResultE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/FindVarResult.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/LiveVariables.cpp "-nm=_ZN12_GLOBAL__N_117LiveVariablesImplE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/LiveVariablesImpl.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN12_GLOBAL__N_110LocalScopeE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/LocalScope.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN12_GLOBAL__N_116LocalVariableMapE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/LocalVariableMap.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN12_GLOBAL__N_117LockableFactEntryE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/LockableFactEntry.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/UninitializedValues.cpp "-nm=_ZN12_GLOBAL__N_118PruneBlocksHandlerE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/PruneBlocksHandler.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN12_GLOBAL__N_123ScopedLockableFactEntryE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/ScopedLockableFactEntry.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN12_GLOBAL__N_117StmtPrinterHelperE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/StmtPrinterHelper.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN12_GLOBAL__N_110TILPrinterE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/TILPrinter.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN12_GLOBAL__N_120ThreadSafetyAnalyzerE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/ThreadSafetyAnalyzer.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN12_GLOBAL__N_19TryResultE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/TryResult.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/FormatString.cpp "-nm=_ZN5clang14UpdateOnReturnE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/UpdateOnReturn.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN12_GLOBAL__N_113VarMapBuilderE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/VarMapBuilder.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/Consumed.cpp "-nm=_ZN12_GLOBAL__N_113VarTestResultE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/VarTestResult.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN12_GLOBAL__N_122has_arg_iterator_rangeE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/has_arg_iterator_range.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN12_GLOBAL__N_116reverse_childrenE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/reverse_children.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ProgramPoint.cpp "-nm=_ZN4llvm12DenseMapInfoIN5clang12ProgramPointEEE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/llvm/DenseMapInfoProgramPoint.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN4llvm11GraphTraitsIPKN5clang3CFGEEE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/llvm/GraphTraitsCFG\$C\$P.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN4llvm11GraphTraitsIPN5clang3CFGEEE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/llvm/GraphTraitsCFG\$P.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN4llvm11GraphTraitsIPKN5clang8CFGBlockEEE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/llvm/GraphTraitsCFGBlock\$C\$P.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN4llvm11GraphTraitsIPN5clang8CFGBlockEEE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/llvm/GraphTraitsCFGBlock\$P.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CallGraph.cpp "-nm=_ZN4llvm11GraphTraitsIPKN5clang9CallGraphEEE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/llvm/GraphTraitsCallGraph\$C\$P.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CallGraph.cpp "-nm=_ZN4llvm11GraphTraitsIPN5clang9CallGraphEEE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/llvm/GraphTraitsCallGraph\$P.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CallGraph.cpp "-nm=_ZN4llvm11GraphTraitsIPKN5clang13CallGraphNodeEEE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/llvm/GraphTraitsCallGraphNode\$C\$P.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CallGraph.cpp "-nm=_ZN4llvm11GraphTraitsIPN5clang13CallGraphNodeEEE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/llvm/GraphTraitsCallGraphNode\$P.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN4llvm11GraphTraitsINS_7InverseIPKN5clang3CFGEEEEE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/llvm/GraphTraitsInverse\$CFG\$C\$P.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN4llvm11GraphTraitsINS_7InverseIPN5clang3CFGEEEEE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/llvm/GraphTraitsInverse\$CFG\$P.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN4llvm11GraphTraitsINS_7InverseIPKN5clang8CFGBlockEEEEE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/llvm/GraphTraitsInverse\$CFGBlock\$C\$P.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN4llvm11GraphTraitsINS_7InverseIPN5clang8CFGBlockEEEEE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/llvm/GraphTraitsInverse\$CFGBlock\$P.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN4llvm14DOTGraphTraitsIPKN5clang3CFGEEE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/llvm/impl/DOTGraphTraitsCFG\$C\$P.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CallGraph.cpp "-nm=_ZN4llvm14DOTGraphTraitsIPKN5clang9CallGraphEEE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/llvm/impl/DOTGraphTraitsCallGraph\$C\$P.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ProgramPoint.cpp "-nm=_ZN4llvm9isPodLikeIN5clang12ProgramPointEEE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/llvm/isPodLikeProgramPoint.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZN4llvm13simplify_typeIN5clang13CFGTerminatorEEE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/llvm/simplify_typeCFGTerminator.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Core/BugReporter.cpp "-nm=_ZN5clang10BumpVectorE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/support/BumpVector.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Core/BugReporter.cpp "-nm=_ZN5clang17BumpVectorContextE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/support/BumpVectorContext.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN5clang12threadSafety9BeforeSetE;" > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/threadSafety/impl/BeforeSet.java

# Global and static namespaces
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CocoaConventions.cpp "-nm=_ZN5clang4ento5cocoa16isCocoaObjectRefENS_8QualTypeE;_ZN5clang4ento5cocoa9isRefTypeENS_8QualTypeEN4llvm9StringRefES4_;" -static-type=cocoa -package=org.clang.analysis.domainspecific.ento > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/domainspecific/ento/cocoa.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CocoaConventions.cpp "-nm=_ZN5clang4ento14coreFoundation13isCFObjectRefENS_8QualTypeE;_ZN5clang4ento14coreFoundation17followsCreateRuleEPKNS_12FunctionDeclE;" -static-type=coreFoundation -package=org.clang.analysis.domainspecific.ento > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/domainspecific/ento/coreFoundation.java

# Static functions/variables
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/AnalysisDeclContext.cpp "-nm=_ZL10isSelfDeclPKN5clang7VarDeclE;_ZL11getBodyFarmRN5clang10ASTContextEPNS_12CodeInjectorE;_ZL27addParentsForSyntheticStmtsPKN5clang3CFGERNS_9ParentMapE;_ZL29LazyInitializeReferencedDeclsPKN5clang9BlockDeclERPvRN4llvm20BumpPtrAllocatorImplINS5_15MallocAllocatorELj4096ELj4096EEE;" -static-type=AnalysisDeclContextStatics -package=org.clang.analysis.impl > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/AnalysisDeclContextStatics.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/BodyFarm.cpp "-nm=_ZL15findBackingIvarPKN5clang16ObjCPropertyDeclE;_ZL15isDispatchBlockN5clang8QualTypeE;_ZL20create_dispatch_onceRN5clang10ASTContextEPKNS_12FunctionDeclE;_ZL20create_dispatch_syncRN5clang10ASTContextEPKNS_12FunctionDeclE;_ZL24createObjCPropertyGetterRN5clang10ASTContextEPKNS_16ObjCPropertyDeclE;_ZL29create_OSAtomicCompareAndSwapRN5clang10ASTContextEPKNS_12FunctionDeclE;" -static-type=BodyFarmStatics -package=org.clang.analysis.impl > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/BodyFarmStatics.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFG.cpp "-nm=_ZL10print_elemRN4llvm11raw_ostreamERN12_GLOBAL__N_117StmtPrinterHelperERKN5clang10CFGElementE;_ZL11GraphHelper;_ZL11print_blockRN4llvm11raw_ostreamEPKN5clang3CFGERKNS2_8CFGBlockERN12_GLOBAL__N_117StmtPrinterHelperEbb;_ZN12_GLOBAL__N_113bothKnownTrueENS_9TryResultES0_;_ZN12_GLOBAL__N_131tryTransformToIntOrEnumConstantEPKN5clang4ExprE;_ZN12_GLOBAL__N_1L13shouldAddCaseERbPKN5clang4Expr10EvalResultEPKNS1_8CaseStmtERNS1_10ASTContextE;_ZN12_GLOBAL__N_1L22areExprTypesCompatibleEPKN5clang4ExprES3_;_ZN12_GLOBAL__N_1L26tryNormalizeBinaryOperatorEPKN5clang14BinaryOperatorE;_ZN12_GLOBAL__N_1L29getReferenceInitTemporaryTypeERN5clang10ASTContextEPKNS0_4ExprE;_ZN12_GLOBAL__N_1L6FindVAEPKN5clang4TypeE;_ZN12_GLOBAL__N_1L8CanThrowEPN5clang4ExprERNS0_10ASTContextE;_ZN12_GLOBAL__N_1L9GetEndLocEPN5clang4DeclE;" -static-type=CFGStatics -package=org.clang.analysis.impl > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/CFGStatics.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CFGStmtMap.cpp "-nm=_ZL10AccumulateRN4llvm8DenseMapIPKN5clang4StmtEPNS1_8CFGBlockENS_12DenseMapInfoIS4_EENS_6detail12DenseMapPairIS4_S6_EEEES6_;_ZL5AsMapPv;" -static-type=CFGStmtMapStatics -package=org.clang.analysis.impl > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/CFGStmtMapStatics.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/CallGraph.cpp "-nm=_ZL16NumObjCCallEdges;_ZL17NumBlockCallEdges;" -static-type=CallGraphStatics -package=org.clang.analysis.impl > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/CallGraphStatics.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/Consumed.cpp "-nm=_ZL11isRValueRefN5clang8QualTypeE;_ZL12isKnownStateN5clang8consumed13ConsumedStateE;_ZL13stateToStringN5clang8consumed13ConsumedStateE;_ZL14getLastStmtLocPKN5clang8CFGBlockE;_ZL14isAutoCastTypeRKN5clang8QualTypeE;_ZL14isPointerOrRefN5clang8QualTypeE;_ZL15getFirstStmtLocPKN5clang8CFGBlockE;_ZL16isConsumableTypeRKN5clang8QualTypeE;_ZL17isCallableInStatePKN5clang16CallableWhenAttrENS_8consumed13ConsumedStateE;_ZL17isTestingFunctionPKN5clang12FunctionDeclE;_ZL18isSetOnReadPtrTypeRKN5clang8QualTypeE;_ZL22mapConsumableAttrStateN5clang8QualTypeE;_ZL24invertConsumedUnconsumedN5clang8consumed13ConsumedStateE;_ZL24mapSetTypestateAttrStatePKN5clang16SetTypestateAttrE;_ZL26mapParamTypestateAttrStatePKN5clang18ParamTypestateAttrE;_ZL27mapReturnTypestateAttrStatePKN5clang19ReturnTypestateAttrE;_ZL8testsForPKN5clang12FunctionDeclE;" -static-type=ConsumedStatics -package=org.clang.analysis.impl > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/ConsumedStatics.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/LiveVariables.cpp "-nm=Tpl__ZN12_GLOBAL__N_19mergeSetsET_S0_;_ZL11AddLiveStmtRN4llvm12ImmutableSetIPKN5clang4StmtENS_17ImutContainerInfoIS4_EEEERNS7_7FactoryES4_;_ZL13isAlwaysAlivePKN5clang7VarDeclE;_ZL15LookThroughStmtPKN5clang4StmtE;_ZL6FindVAN5clang8QualTypeE;_ZL7getImplPv;_ZN12_GLOBAL__N_116DataflowWorklistE;_ZN12_GLOBAL__N_117TransferFunctionsE;" -static-type=LiveVariablesStatics -package=org.clang.analysis.impl > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/LiveVariablesStatics.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ObjCNoReturn.cpp "-nm=_ZL10isSubclassPKN5clang17ObjCInterfaceDeclEPNS_14IdentifierInfoE;" -static-type=ObjCNoReturnStatics -package=org.clang.analysis.impl > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/ObjCNoReturnStatics.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/PrintfFormatString.cpp "-nm=_ZL14ParseObjCFlagsRN5clang21analyze_format_string19FormatStringHandlerERNS_14analyze_printf15PrintfSpecifierEPKcS7_b;_ZL14ParsePrecisionRN5clang21analyze_format_string19FormatStringHandlerERNS_14analyze_printf15PrintfSpecifierEPKcRS7_S7_Pj;_ZL20ParsePrintfSpecifierRN5clang21analyze_format_string19FormatStringHandlerERPKcS4_RjRKNS_11LangOptionsERKNS_10TargetInfoEbb;" -static-type=PrintfFormatStringStatics -package=org.clang.analysis.impl > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/PrintfFormatStringStatics.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ReachableCode.cpp "-nm=_ZL12isDeadReturnPKN5clang8CFGBlockEPKNS_4StmtE;_ZL13scanFromBlockPKN5clang8CFGBlockERN4llvm9BitVectorEPNS_12PreprocessorEb;_ZL14isEnumConstantPKN5clang4ExprE;_ZL15getTopMostMacroN5clang14SourceLocationERNS_13SourceManagerE;_ZL15isValidDeadStmtPKN5clang4StmtE;_ZL16isTrivialDoWhilePKN5clang8CFGBlockEPKNS_4StmtE;_ZL17GetUnreachableLocPKN5clang4StmtERNS_11SourceRangeES4_;_ZL19isTrivialExpressionPKN5clang4ExprE;_ZL20isConfigurationValuePKN5clang4StmtERNS_12PreprocessorEPNS_11SourceRangeEbb;_ZL20isConfigurationValuePKN5clang9ValueDeclERNS_12PreprocessorE;_ZL27scanMaybeReachableFromBlockPKN5clang8CFGBlockERNS_12PreprocessorERN4llvm9BitVectorE;_ZL32isExpandedFromConfigurationMacroPKN5clang4StmtERNS_12PreprocessorEb;_ZL32shouldTreatSuccessorsAsReachablePKN5clang8CFGBlockERNS_12PreprocessorE;_ZL6SrcCmpPKSt4pairIPKN5clang8CFGBlockEPKNS0_4StmtEES9_;" -static-type=ReachableCodeStatics -package=org.clang.analysis.impl > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/ReachableCodeStatics.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ScanfFormatString.cpp "-nm=_ZL13ParseScanListRN5clang21analyze_format_string19FormatStringHandlerERNS_13analyze_scanf24ScanfConversionSpecifierERPKcS7_;_ZL19ParseScanfSpecifierRN5clang21analyze_format_string19FormatStringHandlerERPKcS4_RjRKNS_11LangOptionsERKNS_10TargetInfoE;" -static-type=ScanfFormatStringStatics -package=org.clang.analysis.impl > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/ScanfFormatStringStatics.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyCommon.cpp "-nm=_ZL13isCalleeArrowPKN5clang4ExprE;_ZL13maybeUpdateVDPN5clang12threadSafety3til5SExprEPKNS_9ValueDeclE;_ZL15isIncompletePhiPKN5clang12threadSafety3til5SExprE;_ZL17hasCppPointerTypePKN5clang12threadSafety3til5SExprE;_ZL19getFirstVirtualDeclPKN5clang13CXXMethodDeclE;_ZL21getValueDeclFromSExprPKN5clang12threadSafety3til5SExprE;" -static-type=ThreadSafetyCommonStatics -package=org.clang.analysis.impl > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/ThreadSafetyCommonStatics.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyLogical.cpp "-nm=_ZL7impliesPKN5clang12threadSafety5lexpr5LExprEbS4_b;" -static-type=ThreadSafetyLogicalStatics -package=org.clang.analysis.impl > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/ThreadSafetyLogicalStatics.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=Tpl__ZL18ClassifyDiagnosticPKT_R_ZTSNSt9enable_ifIXntsr22has_arg_iterator_rangeIT_EE5valueEN4llvm9StringRefEE4typeE;Tpl__ZL18ClassifyDiagnosticPKT_R_ZTSNSt9enable_ifIXsr22has_arg_iterator_rangeIT_EE5valueEN4llvm9StringRefEE4typeE;_ZL12getValueDeclPKN5clang4ExprE;_ZL12neverReturnsPKN5clang8CFGBlockE;_ZL18ClassifyDiagnosticN5clang8QualTypeE;_ZL18ClassifyDiagnosticPKN5clang14CapabilityAttrE;_ZL18ClassifyDiagnosticPKN5clang9ValueDeclE;_ZL21getStaticBooleanValuePN5clang4ExprERb;_ZN12_GLOBAL__N_1L15warnInvalidLockERN5clang12threadSafety19ThreadSafetyHandlerEPKNS0_4ExprEPKNS0_9NamedDeclES6_N4llvm9StringRefE;_ZN12_GLOBAL__N_1L18findBlockLocationsEPN5clang3CFGEPKNS0_16PostOrderCFGViewERSt6vectorINS_12CFGBlockInfoESaIS7_EE;" -static-type=ThreadSafetyStatics -package=org.clang.analysis.impl > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/ThreadSafetyStatics.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZL13computeNodeIDPN5clang12threadSafety3til10BasicBlockEMS2_NS2_12TopologyNodeE;_ZL15computeNodeSizePN5clang12threadSafety3til10BasicBlockEMS2_NS2_12TopologyNodeE;" -static-type=ThreadSafetyTILStatics -package=org.clang.analysis.impl > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/ThreadSafetyTILStatics.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/UninitializedValues.cpp "-nm=_ZL10runOnBlockPKN5clang8CFGBlockERKNS_3CFGERNS_19AnalysisDeclContextERN12_GLOBAL__N_114CFGBlockValuesERKNS8_12ClassifyRefsERN4llvm9BitVectorERNS_22UninitVariablesHandlerE;_ZL12isTrackedVarPKN5clang7VarDeclEPKNS_11DeclContextE;_ZL14isAlwaysUninit5Value;_ZL15getSelfInitExprPN5clang7VarDeclE;_ZL15isUninitialized5Value;_ZL16isPointerToConstRKN5clang8QualTypeE;_ZN12_GLOBAL__N_116DataflowWorklistE;_ZN12_GLOBAL__N_117TransferFunctionsE;_ZN12_GLOBAL__N_1L10stripCastsERN5clang10ASTContextEPKNS0_4ExprE;_ZN12_GLOBAL__N_1L7findVarEPKN5clang4ExprEPKNS0_11DeclContextE;" -static-type=UninitializedValuesStatics -package=org.clang.analysis.impl > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/impl/UninitializedValuesStatics.java

# Global functions/variables
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZnwjRN5clang12threadSafety3til12MemRegionRefE;" -static-type=ThreadSafetyUtilGlobals -package=org.clang.analysis.analyses > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/ThreadSafetyUtilGlobals.java

# Global functions/variables for namespace as packages
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/UninitializedValues.cpp "-nm=_ZN5clang33runUninitializedVariablesAnalysisERKNS_11DeclContextERKNS_3CFGERNS_19AnalysisDeclContextERNS_22UninitVariablesHandlerERNS_28UninitVariablesAnalysisStatsE;" -static-type=AnalysisClangGlobals -package=org.clang.analysis.analyses > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/AnalysisClangGlobals.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -body-delegate -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/PrintfFormatString.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ScanfFormatString.cpp "-nm=_ZN5clang21analyze_format_string16ParseScanfStringERNS0_19FormatStringHandlerEPKcS4_RKNS_11LangOptionsERKNS_10TargetInfoE;_ZN5clang21analyze_format_string17ParsePrintfStringERNS0_19FormatStringHandlerEPKcS4_RKNS_11LangOptionsERKNS_10TargetInfoEb;_ZN5clang21analyze_format_string24ParseFormatStringHasSArgEPKcS2_RKNS_11LangOptionsERKNS_10TargetInfoE;" -static-type=Analyze_format_stringGlobals -package=org.clang.analysis.analyses.analyze_format_string > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/analyze_format_string/Analyze_format_stringGlobals.java
#    ${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/PrintfFormatString.cpp "-nm=_ZN5clang21analyze_format_string17ParsePrintfStringERNS0_19FormatStringHandlerEPKcS4_RKNS_11LangOptionsERKNS_10TargetInfoEb;_ZN5clang21analyze_format_string24ParseFormatStringHasSArgEPKcS2_RKNS_11LangOptionsERKNS_10TargetInfoE;" -static-type=PrintfFormatStringAnalyze_format_stringGlobals -package=org.clang.analysis.analyses.analyze_format_string.impl > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/analyze_format_string/impl/PrintfFormatStringAnalyze_format_stringGlobals.java
#    ${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ScanfFormatString.cpp "-nm=_ZN5clang21analyze_format_string16ParseScanfStringERNS0_19FormatStringHandlerEPKcS4_RKNS_11LangOptionsERKNS_10TargetInfoE;" -static-type=ScanfFormatStringAnalyze_format_stringGlobals -package=org.clang.analysis.analyses.analyze_format_string.impl > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/analyze_format_string/impl/ScanfFormatStringAnalyze_format_stringGlobals.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ReachableCode.cpp "-nm=_ZN5clang14reachable_code19FindUnreachableCodeERNS_19AnalysisDeclContextERNS_12PreprocessorERNS0_8CallbackE;_ZN5clang14reachable_code22ScanReachableFromBlockEPKNS_8CFGBlockERN4llvm9BitVectorE;" -static-type=Reachable_codeGlobals -package=org.clang.analysis.analyses.reachable_code > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/reachable_code/Reachable_codeGlobals.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -body-delegate -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyCommon.cpp "-nm=_ZN5clang12threadSafety19threadSafetyCleanupEPNS0_9BeforeSetE;_ZN5clang12threadSafety22getSourceLiteralStringEPKNS_4ExprE;_ZN5clang12threadSafety23runThreadSafetyAnalysisERNS_19AnalysisDeclContextERNS0_19ThreadSafetyHandlerEPPNS0_9BeforeSetE;_ZN5clang12threadSafety25getLockKindFromAccessKindENS0_10AccessKindE;_ZN5clang12threadSafetylsERSoN4llvm9StringRefE;" -static-type=ThreadSafetyGlobals -package=org.clang.analysis.analyses.threadSafety > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/ThreadSafetyGlobals.java
#    ${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN5clang12threadSafety19threadSafetyCleanupEPNS0_9BeforeSetE;_ZN5clang12threadSafety23runThreadSafetyAnalysisERNS_19AnalysisDeclContextERNS0_19ThreadSafetyHandlerEPPNS0_9BeforeSetE;_ZN5clang12threadSafety25getLockKindFromAccessKindENS0_10AccessKindE;" -static-type=ThreadSafetyThreadSafetyGlobals -package=org.clang.analysis.analyses.threadSafety.impl > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/impl/ThreadSafetyThreadSafetyGlobals.java
#    ${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyCommon.cpp "-nm=_ZN5clang12threadSafety22getSourceLiteralStringEPKNS_4ExprE;" -static-type=ThreadSafetyCommonThreadSafetyGlobals -package=org.clang.analysis.analyses.threadSafety.impl > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/impl/ThreadSafetyCommonThreadSafetyGlobals.java
#    ${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafety.cpp "-nm=_ZN5clang12threadSafetylsERSoN4llvm9StringRefE;" -static-type=ThreadSafetyUtilThreadSafetyGlobals -package=org.clang.analysis.analyses.threadSafety.impl > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/impl/ThreadSafetyUtilThreadSafetyGlobals.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyLogical.cpp "-nm=_ZN5clang12threadSafety5lexpr7impliesEPKNS1_5LExprES4_;" -static-type=LexprGlobals -package=org.clang.analysis.analyses.threadSafety.lexpr > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/lexpr/LexprGlobals.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyCommon.cpp "-nm=_ZN5clang12threadSafety2sx16partiallyMatchesEPKNS0_3til5SExprES5_;_ZN5clang12threadSafety2sx6equalsEPKNS0_3til5SExprES5_;_ZN5clang12threadSafety2sx7matchesEPKNS0_3til5SExprES5_;_ZN5clang12threadSafety2sx8toStringEPKNS0_3til5SExprE;" -static-type=SxGlobals -package=org.clang.analysis.analyses.threadSafety.sx > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/sx/SxGlobals.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til15ThreadSafetyTIL9isTrivialEPKNS1_5SExprE;" -static-type=ThreadSafetyTILGlobals -package=org.clang.analysis.analyses.threadSafety.til.ThreadSafetyTIL > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/ThreadSafetyTIL/ThreadSafetyTILGlobals.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/ThreadSafetyTIL.cpp "-nm=_ZN5clang12threadSafety3til15getCanonicalValEPKNS1_5SExprE;_ZN5clang12threadSafety3til20getUnaryOpcodeStringENS1_15TIL_UnaryOpcodeE;_ZN5clang12threadSafety3til21getBinaryOpcodeStringENS1_16TIL_BinaryOpcodeE;_ZN5clang12threadSafety3til21simplifyIncompleteArgEPNS1_3PhiE;_ZN5clang12threadSafety3til22simplifyToCanonicalValEPNS1_5SExprE;_ZN5clang12threadSafety3tilL7BOP_MaxE;_ZN5clang12threadSafety3tilL7BOP_MinE;_ZN5clang12threadSafety3tilL7COP_MaxE;_ZN5clang12threadSafety3tilL7COP_MinE;_ZN5clang12threadSafety3tilL7UOP_MaxE;_ZN5clang12threadSafety3tilL7UOP_MinE;_ZN5clang12threadSafety3tilL8CAST_MaxE;_ZN5clang12threadSafety3tilL8CAST_MinE;" -static-type=TilGlobals -package=org.clang.analysis.analyses.threadSafety.til > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyses/threadSafety/til/TilGlobals.java

# Static functions/variables for namespaces as packages
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/FormatString.cpp "-nm=_ZN5clang21analyze_format_string11ParseAmountERPKcS2_;_ZN5clang21analyze_format_string15ParseFieldWidthERNS0_19FormatStringHandlerERNS0_15FormatSpecifierEPKcRS6_S6_Pj;_ZN5clang21analyze_format_string16ParseArgPositionERNS0_19FormatStringHandlerERNS0_15FormatSpecifierEPKcRS6_S6_;_ZN5clang21analyze_format_string19ParseLengthModifierERNS0_15FormatSpecifierERPKcS4_RKNS_11LangOptionsEb;_ZN5clang21analyze_format_string19ParsePositionAmountERNS0_19FormatStringHandlerEPKcRS4_S4_NS0_15PositionContextE;_ZN5clang21analyze_format_string22ParseNonPositionAmountERPKcS2_Rj;_ZN5clang21analyze_format_string25ParseUTF8InvalidSpecifierEPKcS2_Rj;" -static-type=Analyze_format_stringStatics -package=org.clang.analysis.analyze_format_string.impl > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/analyze_format_string/impl/Analyze_format_stringStatics.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.analysis/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Analysis/Consumed.cpp "-nm=_ZN5clang8consumedL18splitVarStateForIfEPKNS_6IfStmtERKN12_GLOBAL__N_113VarTestResultEPNS0_16ConsumedStateMapES9_;_ZN5clang8consumedL19setStateForVarOrTmpEPNS0_16ConsumedStateMapERKNS0_15PropagationInfoENS0_13ConsumedStateE;_ZN5clang8consumedL23splitVarStateForIfBinOpERKNS0_15PropagationInfoEPNS0_16ConsumedStateMapES5_;" -static-type=ConsumedStatics -package=org.clang.analysis.consumed.impl > ${SPUTNIK}/modules/org.clang.analysis/src/org/clang/analysis/consumed/impl/ConsumedStatics.java

# Global typedefs


