FILE_NAME = StdMapPtrBool
CLASS_SUFFIX = <KeyT>
DUAL_CLASS = std.mapPtrBool<KeyT>
PAIR_TYPE = std.pairPtrBool<KeyT>
ITERATOR = iterator<KeyT>
GENERIC_ITERATOR = type$iterator<?, std.pairPtrBool<KeyT>>
KEY_TYPE = KeyT
VALUE_TYPE = boolean
VALUE_REF = bool$ref
VALUE_PTR = bool$ptr
IS_KEY_POINTER_LIKE = true
IS_DATA_POINTER_LIKE = false
PAIR_FACTORY_METHOD = std.make_pair_Ptr_bool
DEFAULT_KEYS_COMPARATOR = Native::$compare_ptr
ASSERT_DEFAULT_VALUE=true