FILE_NAME = StdMapULongUInt
CLASS_SUFFIX = 
DUAL_CLASS = std.mapULongUInt
PAIR_TYPE = std.pairULongUInt
ITERATOR = iterator
GENERIC_ITERATOR = type$iterator<?, std.pairULongUInt>
KEY_TYPE = Long
VALUE_TYPE = int
VALUE_REF = uint$ref
VALUE_PTR = uint$ptr
IS_KEY_POINTER_LIKE = false
IS_DATA_POINTER_LIKE = false
PAIR_FACTORY_METHOD = std.make_pair_ulong_uint
DEFAULT_KEYS_COMPARATOR = Native::$compare_type_ulong
ASSERT_DEFAULT_VALUE=true