FILE_NAME = StdMapTypeInt
CLASS_SUFFIX = <KeyT>
DUAL_CLASS = std.mapTypeInt<KeyT>
PAIR_TYPE = std.pairTypeInt<KeyT>
ITERATOR = iterator<KeyT>
GENERIC_ITERATOR = type$iterator<?, std.pairTypeInt<KeyT>>
KEY_TYPE = KeyT
VALUE_TYPE = int
VALUE_REF = int$ref
VALUE_PTR = int$ptr
IS_KEY_POINTER_LIKE = false
IS_DATA_POINTER_LIKE = false
PAIR_FACTORY_METHOD = std.make_pair_T_int
DEFAULT_KEYS_COMPARATOR = Native::$compare_type
ASSERT_DEFAULT_VALUE=true