FILE_NAME = StdMapIntInt
CLASS_SUFFIX = 
DUAL_CLASS = std.mapIntInt
PAIR_TYPE = std.pairIntInt
ITERATOR = iterator
GENERIC_ITERATOR = type$iterator<?, std.pairIntInt>
KEY_TYPE = Integer
VALUE_TYPE = int
VALUE_REF = int$ref
VALUE_PTR = int$ptr
IS_KEY_POINTER_LIKE = false
IS_DATA_POINTER_LIKE = false
PAIR_FACTORY_METHOD = std.make_pair_int_int
DEFAULT_KEYS_COMPARATOR = Native::$compare_type_int
ASSERT_DEFAULT_VALUE=true