FILE_NAME = StdReverseIteratorInt
CLASS_SUFFIX =
INTERFACE_ITERATOR = int$iterator<std.reverse_iteratorInt>
STD_DUAL_ITERATOR = std.reverse_iteratorInt
VALUE_TYPE = int
VALUE_ITERATOR = int$iterator<?>
VALUE_ITERATOR_GENERIC = int$iterator
VALUE_REFERENCE = int$ref
VALUE_POINTER = int$ptr