FILE_NAME = StdReverseIteratorLong
CLASS_SUFFIX =
INTERFACE_ITERATOR = long$iterator<std.reverse_iteratorLong>
STD_DUAL_ITERATOR = std.reverse_iteratorLong
VALUE_TYPE = long
VALUE_ITERATOR = long$iterator<?>
VALUE_ITERATOR_GENERIC = long$iterator
VALUE_REFERENCE = long$ref
VALUE_POINTER = long$ptr