FILE_NAME = StdReverseIteratorUChar
CLASS_SUFFIX =
INTERFACE_ITERATOR = uchar$iterator<std.reverse_iteratorUChar>
STD_DUAL_ITERATOR = std.reverse_iteratorUChar
VALUE_TYPE = byte
VALUE_ITERATOR = uchar$iterator<?>
VALUE_ITERATOR_GENERIC = uchar$iterator
VALUE_REFERENCE = uchar$ref
VALUE_POINTER = uchar$ptr