FILE_NAME = StdReverseIteratorULLong
CLASS_SUFFIX =
INTERFACE_ITERATOR = ullong$iterator<std.reverse_iteratorULLong>
STD_DUAL_ITERATOR = std.reverse_iteratorULLong
VALUE_TYPE = long
VALUE_ITERATOR = ullong$iterator<?>
VALUE_ITERATOR_GENERIC = ullong$iterator
VALUE_REFERENCE = ullong$ref
VALUE_POINTER = ullong$ptr