FILE_NAME = StdUnorderedMapTypePtr
CLASS_SUFFIX = <K, V>
DUAL_CLASS = std.unordered_mapTypePtr<K, V>
GENERIC_DUAL_CLASS = std.unordered_mapTypePtr<K, ?>
PAIR_TYPE = std.pairTypePtr<K, V>
ITERATOR = iterator<K, V>
GENERIC_ITERATOR = type$iterator<iterator<K, V>, std.pairTypePtr<K, V>>
KEY_TYPE = K
WRAPPED_KEY_NAME = WrappedKey
WRAPPED_KEY_TYPE = WrappedKey<K>
VALUE_TYPE = V
VALUE_REF = type$ref<V>
VALUE_REF_IMPL = type$ptr$inout<V>
VALUE_SUPPLIER = Supplier<V>
IS_KEY_POINTER_LIKE = false
IS_DATA_POINTER_LIKE = true
PAIR_FACTORY_METHOD = std.make_pair_T_Ptr
HASH_FUN_TYPE = std.hash<K>
EQUAL_FUN_TYPE = std.binary_functionBoolean<K>