# Used directories
mkdir -p ${SPUTNIK}/modules/org.clang.edit/src/org/clang/edit
mkdir -p ${SPUTNIK}/modules/org.clang.edit/src/org/clang/edit/impl

# Global and static Enums

# Global and static CXXRecords, ClassTemplates, ClassTemplateSpecializations
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.edit/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Edit/Commit.cpp ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ObjCMT.cpp "-nm=_ZN5clang4edit6CommitE;" > ${SPUTNIK}/modules/org.clang.edit/src/org/clang/edit/Commit.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.edit/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Edit/EditedSource.cpp ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ObjCMT.cpp "-nm=_ZN5clang4edit12EditedSourceE;" > ${SPUTNIK}/modules/org.clang.edit/src/org/clang/edit/EditedSource.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.edit/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Edit/EditedSource.cpp ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ObjCMT.cpp "-nm=_ZN5clang4edit13EditsReceiverE;" > ${SPUTNIK}/modules/org.clang.edit/src/org/clang/edit/EditsReceiver.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.edit/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Edit/Commit.cpp "-nm=_ZN5clang4edit10FileOffsetE;" > ${SPUTNIK}/modules/org.clang.edit/src/org/clang/edit/FileOffset.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.edit/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Edit/RewriteObjCFoundationAPI.cpp "-nm=_ZN12_GLOBAL__N_111LiteralInfoE;" > ${SPUTNIK}/modules/org.clang.edit/src/org/clang/edit/impl/LiteralInfo.java

# Global and static namespaces

# Static functions/variables
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.edit/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Edit/EditedSource.cpp "-nm=_ZL11canBeJoinedccRKN5clang11LangOptionsE;_ZL12applyRewriteRN5clang4edit13EditsReceiverEN4llvm9StringRefENS0_10FileOffsetEjRKNS_13SourceManagerERKNS_11LangOptionsE;_ZL13adjustRemovalRKN5clang13SourceManagerERKNS_11LangOptionsENS_14SourceLocationENS_4edit10FileOffsetERjRN4llvm9StringRefE;_ZL19canRemoveWhitespacecccRKN5clang11LangOptionsE;" -static-type=EditedSourceStatics -package=org.clang.edit.impl > ${SPUTNIK}/modules/org.clang.edit/src/org/clang/edit/impl/EditedSourceStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.edit/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Edit/RewriteObjCFoundationAPI.cpp "-nm=_ZL13objectifyExprPKN5clang4ExprERNS_4edit6CommitE;_ZL14getLiteralInfoN5clang11SourceRangeEbbRNS_10ASTContextERN12_GLOBAL__N_111LiteralInfoE;_ZL14isEnumConstantPKN5clang4ExprE;_ZL17getNSArrayObjectsPKN5clang4ExprERKNS_5NSAPIERN4llvm15SmallVectorImplIS2_EE;_ZL20rewriteToBoolLiteralPKN5clang15ObjCMessageExprEPKNS_4ExprERKNS_5NSAPIERNS_4edit6CommitE;_ZL20rewriteToCharLiteralPKN5clang15ObjCMessageExprEPKNS_16CharacterLiteralERKNS_5NSAPIERNS_4edit6CommitE;_ZL21rewriteToArrayLiteralPKN5clang15ObjCMessageExprERKNS_5NSAPIERNS_4edit6CommitEPKNS_9ParentMapE;_ZL22rewriteToNumberLiteralPKN5clang15ObjCMessageExprERKNS_5NSAPIERNS_4edit6CommitE;_ZL23castOperatorNeedsParensPKN5clang4ExprE;_ZL23checkForLiteralCreationPKN5clang15ObjCMessageExprERPNS_14IdentifierInfoERKNS_11LangOptionsE;_ZL24maybePutParensOnReceiverPKN5clang4ExprERNS_4edit6CommitE;_ZL26rewriteToArraySubscriptGetPKN5clang17ObjCInterfaceDeclEPKNS_15ObjCMessageExprERKNS_5NSAPIERNS_4edit6CommitE;_ZL26rewriteToArraySubscriptSetPKN5clang17ObjCInterfaceDeclEPKNS_15ObjCMessageExprERKNS_5NSAPIERNS_4edit6CommitE;_ZL26rewriteToDictionaryLiteralPKN5clang15ObjCMessageExprERKNS_5NSAPIERNS_4edit6CommitE;_ZL27canRewriteToSubscriptSyntaxRPKN5clang17ObjCInterfaceDeclEPKNS_15ObjCMessageExprERNS_10ASTContextENS_8SelectorE;_ZL27rewriteToSubscriptGetCommonPKN5clang15ObjCMessageExprERNS_4edit6CommitE;_ZL28subscriptOperatorNeedsParensPKN5clang4ExprE;_ZL30rewriteToStringBoxedExpressionPKN5clang15ObjCMessageExprERKNS_5NSAPIERNS_4edit6CommitE;_ZL31rewriteToDictionarySubscriptGetPKN5clang17ObjCInterfaceDeclEPKNS_15ObjCMessageExprERKNS_5NSAPIERNS_4edit6CommitE;_ZL31rewriteToDictionarySubscriptSetPKN5clang17ObjCInterfaceDeclEPKNS_15ObjCMessageExprERKNS_5NSAPIERNS_4edit6CommitE;_ZL31rewriteToNumericBoxedExpressionPKN5clang15ObjCMessageExprERKNS_5NSAPIERNS_4edit6CommitE;_ZL36shouldNotRewriteImmediateMessageArgsPKN5clang15ObjCMessageExprERKNS_5NSAPIE;_ZL40maybeAdjustInterfaceForSubscriptingCheckPKN5clang17ObjCInterfaceDeclEPKNS_4ExprERNS_10ASTContextE;_ZL42doRewriteToUTF8StringBoxedExpressionHelperPKN5clang15ObjCMessageExprERKNS_5NSAPIERNS_4edit6CommitE;" -static-type=RewriteObjCFoundationAPIStatics -package=org.clang.edit.impl > ${SPUTNIK}/modules/org.clang.edit/src/org/clang/edit/impl/RewriteObjCFoundationAPIStatics.java

# Global functions/variables

# Global functions/variables for namespace as packages
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.edit/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Edit/RewriteObjCFoundationAPI.cpp "-nm=_ZN5clang4edit26rewriteToObjCLiteralSyntaxEPKNS_15ObjCMessageExprERKNS_5NSAPIERNS0_6CommitEPKNS_9ParentMapE;_ZN5clang4edit28rewriteToObjCSubscriptSyntaxEPKNS_15ObjCMessageExprERKNS_5NSAPIERNS0_6CommitE;_ZN5clang4edit35rewriteObjCRedundantCallWithLiteralEPKNS_15ObjCMessageExprERKNS_5NSAPIERNS0_6CommitE;" -static-type=EditGlobals -package=org.clang.edit > ${SPUTNIK}/modules/org.clang.edit/src/org/clang/edit/EditGlobals.java

# Static functions/variables for namespaces as packages

