# Used directories
mkdir -p ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser
mkdir -p ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/impl
mkdir -p ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/lltok/impl

# Global and static Enums
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/LLLexer.cpp "-nm=_ZN4llvm5lltok4KindE;" > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/lltok/impl/Kind.java

# Global and static CXXRecords, ClassTemplates, ClassTemplateSpecializations
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/LLParser.cpp "-nm=_ZN4llvm11SlotMappingE;" > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/SlotMapping.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/LLParser.cpp "-nm=_ZN12_GLOBAL__N_111ColumnFieldE;" > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/impl/ColumnField.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/LLParser.cpp "-nm=_ZN12_GLOBAL__N_111DIFlagFieldE;" > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/impl/DIFlagField.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/LLParser.cpp "-nm=_ZN12_GLOBAL__N_121DwarfAttEncodingFieldE;" > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/impl/DwarfAttEncodingField.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/LLParser.cpp "-nm=_ZN12_GLOBAL__N_112DwarfCCFieldE;" > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/impl/DwarfCCField.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/LLParser.cpp "-nm=_ZN12_GLOBAL__N_114DwarfLangFieldE;" > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/impl/DwarfLangField.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/LLParser.cpp "-nm=_ZN12_GLOBAL__N_121DwarfMacinfoTypeFieldE;" > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/impl/DwarfMacinfoTypeField.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/LLParser.cpp "-nm=_ZN12_GLOBAL__N_113DwarfTagFieldE;" > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/impl/DwarfTagField.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/LLParser.cpp "-nm=_ZN12_GLOBAL__N_120DwarfVirtualityFieldE;" > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/impl/DwarfVirtualityField.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/LLParser.cpp "-nm=_ZN12_GLOBAL__N_117EmissionKindFieldE;" > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/impl/EmissionKindField.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/LLLexer.cpp ${LLVM_SRC}/llvm/lib/AsmParser/LLParser.cpp "-nm=_ZN4llvm7LLLexerE;" > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/impl/LLLexer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/LLParser.cpp ${LLVM_SRC}/llvm/lib/AsmParser/Parser.cpp "-nm=_ZN4llvm8LLParserE;" > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/impl/LLParser.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/LLParser.cpp "-nm=_ZN12_GLOBAL__N_19LineFieldE;" > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/impl/LineField.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/LLParser.cpp "-nm=_ZN12_GLOBAL__N_111MDBoolFieldE;" > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/impl/MDBoolField.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/LLParser.cpp "-nm=_ZN12_GLOBAL__N_110MDConstantE;" > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/impl/MDConstant.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/LLParser.cpp "-nm=_ZN12_GLOBAL__N_17MDFieldE;" > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/impl/MDField.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/LLParser.cpp "-nm=_ZN12_GLOBAL__N_111MDFieldImplE;" > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/impl/MDFieldImpl.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/LLParser.cpp "-nm=_ZN12_GLOBAL__N_111MDFieldListE;" > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/impl/MDFieldList.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/LLParser.cpp "-nm=_ZN12_GLOBAL__N_113MDSignedFieldE;" > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/impl/MDSignedField.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/LLParser.cpp "-nm=_ZN12_GLOBAL__N_113MDStringFieldE;" > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/impl/MDStringField.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/LLParser.cpp "-nm=_ZN12_GLOBAL__N_115MDUnsignedFieldE;" > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/impl/MDUnsignedField.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/LLParser.cpp "-nm=_ZN4llvm5ValIDE;" > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/impl/ValID.java

# Static functions/variables
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/LLLexer.cpp "-nm=_ZL11isLabelCharc;_ZL11isLabelTailPKc;_ZL13UnEscapeLexedRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE;" -static-type=LLLexerStatics -package=org.llvm.asmparser.impl > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/impl/LLLexerStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/LLParser.cpp "-nm=_ZL13getTypeStringB5cxx11PN4llvm4TypeE;_ZL18createGlobalFwdRefPN4llvm6ModuleEPNS_11PointerTypeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE;_ZL23parseOptionalLinkageAuxN4llvm5lltok4KindERb;_ZL27isValidVisibilityForLinkagejj;" -static-type=LLParserStatics -package=org.llvm.asmparser.impl > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/impl/LLParserStatics.java

# Global functions/variables for namespace as packages
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.asmparser/llvmToClangType ${LLVM_SRC}/llvm/lib/AsmParser/Parser.cpp "-nm=_ZN4llvm13parseAssemblyENS_15MemoryBufferRefERNS_12SMDiagnosticERNS_11LLVMContextEPNS_11SlotMappingE;_ZN4llvm17parseAssemblyFileENS_9StringRefERNS_12SMDiagnosticERNS_11LLVMContextEPNS_11SlotMappingE;_ZN4llvm17parseAssemblyIntoENS_15MemoryBufferRefERNS_6ModuleERNS_12SMDiagnosticEPNS_11SlotMappingE;_ZN4llvm18parseConstantValueENS_9StringRefERNS_12SMDiagnosticERKNS_6ModuleEPKNS_11SlotMappingE;_ZN4llvm19parseAssemblyStringENS_9StringRefERNS_12SMDiagnosticERNS_11LLVMContextEPNS_11SlotMappingE;_ZN4llvm20parseTypeAtBeginningENS_9StringRefERjRNS_12SMDiagnosticERKNS_6ModuleEPKNS_11SlotMappingE;_ZN4llvm9parseTypeENS_9StringRefERNS_12SMDiagnosticERKNS_6ModuleEPKNS_11SlotMappingE;" -static-type=AsmparserLlvmGlobals -package=org.llvm.asmparser > ${SPUTNIK}/modules/org.llvm.asmparser/src/org/llvm/asmparser/AsmparserLlvmGlobals.java

