# Used directories
mkdir -p ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/core
mkdir -p ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend
mkdir -p ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/impl

# Global and static Enums

# Global and static CXXRecords, ClassTemplates, ClassTemplateSpecializations
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/DeltaTree.cpp "-nm=_ZN5clang9DeltaTreeE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/core/DeltaTree.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/Rewriter.cpp "-nm=_ZN5clang13RewriteBufferE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/core/RewriteBuffer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/RewriteRope.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/Rewriter.cpp "-nm=_ZN5clang11RewriteRopeE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/core/RewriteRope.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMT.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/Rewriter.cpp "-nm=_ZN5clang8RewriterE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/core/Rewriter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/RewriteRope.cpp "-nm=_ZN5clang9RopePieceE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/core/RopePiece.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/RewriteRope.cpp "-nm=_ZN5clang14RopePieceBTreeE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/core/RopePieceBTree.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/RewriteRope.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/Rewriter.cpp "-nm=_ZN5clang22RopePieceBTreeIteratorE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/core/RopePieceBTreeIterator.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/RewriteRope.cpp "-nm=_ZN5clang18RopeRefCountStringE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/core/RopeRefCountString.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/TokenRewriter.cpp "-nm=_ZN5clang13TokenRewriterE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/core/TokenRewriter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp "-nm=_ZN5clang11FixItActionE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/FixItAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp "-nm=_ZN5clang14FixItRecompileE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/FixItRecompile.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp "-nm=_ZN5clang15HTMLPrintActionE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/HTMLPrintAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp "-nm=_ZN5clang21RewriteIncludesActionE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/RewriteIncludesAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp "-nm=_ZN5clang19RewriteMacrosActionE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/RewriteMacrosAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp "-nm=_ZN5clang17RewriteObjCActionE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/RewriteObjCAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp "-nm=_ZN5clang17RewriteTestActionE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/RewriteTestAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/Rewriter.cpp "-nm=_ZN12_GLOBAL__N_119AtomicallyMovedFileE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/impl/AtomicallyMovedFile.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/DeltaTree.cpp "-nm=_ZN12_GLOBAL__N_121DeltaTreeInteriorNodeE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/impl/DeltaTreeInteriorNode.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/DeltaTree.cpp "-nm=_ZN12_GLOBAL__N_113DeltaTreeNodeE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/impl/DeltaTreeNode.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/RewriteRope.cpp "-nm=_ZN12_GLOBAL__N_122RopePieceBTreeInteriorE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/impl/RopePieceBTreeInterior.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/RewriteRope.cpp "-nm=_ZN12_GLOBAL__N_118RopePieceBTreeLeafE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/impl/RopePieceBTreeLeaf.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/RewriteRope.cpp "-nm=_ZN12_GLOBAL__N_118RopePieceBTreeNodeE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/impl/RopePieceBTreeNode.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/DeltaTree.cpp "-nm=_ZN12_GLOBAL__N_111SourceDeltaE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/impl/SourceDelta.java

# Global and static namespaces
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/HTMLRewrite.cpp "-nm=_ZN5clang4html14HighlightRangeERNS_8RewriterENS_14SourceLocationES3_PKcS5_;_ZN5clang4html14HighlightRangeERNS_8RewriterENS_11SourceRangeEPKcS5_;_ZN5clang4html14HighlightRangeERNS_13RewriteBufferEjjPKcS4_S4_;_ZN5clang4html10EscapeTextERNS_8RewriterENS_6FileIDEbb;_ZN5clang4html10EscapeTextEN4llvm9StringRefEbb;_ZN5clang4html14AddLineNumbersERNS_8RewriterENS_6FileIDE;_ZN5clang4html33AddHeaderFooterInternalBuiltinCSSERNS_8RewriterENS_6FileIDEPKc;_ZN5clang4html15SyntaxHighlightERNS_8RewriterENS_6FileIDERKNS_12PreprocessorE;_ZN5clang4html15HighlightMacrosERNS_8RewriterENS_6FileIDERKNS_12PreprocessorE;" -static-type=html -package=org.clang.rewrite.impl > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/impl/html.java

# Static functions/variables
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/DeltaTree.cpp "-nm=_ZL7getRootPv;" -static-type=DeltaTreeStatics -package=org.clang.rewrite.impl > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/impl/DeltaTreeStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/HTMLRewrite.cpp "-nm=_ZL13AddLineNumberRN5clang13RewriteBufferEjjj;" -static-type=HTMLRewriteStatics -package=org.clang.rewrite.impl > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/impl/HTMLRewriteStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/RewriteRope.cpp "-nm=_ZL7getRootPv;_ZL5getCNPKv;" -static-type=RewriteRopeStatics -package=org.clang.rewrite.impl > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/impl/RewriteRopeStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/Rewriter.cpp "-nm=_ZL12isWhitespaceh;" -static-type=RewriterStatics -package=org.clang.rewrite.impl > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/impl/RewriterStatics.java

# Global functions/variables

# Global functions/variables for namespace as packages

# Static functions/variables for namespaces as packages

