# Used directories
mkdir -p ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/core
mkdir -p ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend
mkdir -p ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/impl
mkdir -p ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/impl

# Global and static Enums
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/RewriteModernObjC.cpp "-nm=_Z13MetaDataDlags;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/impl/MetaDataDlags.java

# Global and static CXXRecords, ClassTemplates, ClassTemplateSpecializations
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/DeltaTree.cpp "-nm=_ZN5clang9DeltaTreeE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/core/DeltaTree.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/Rewriter.cpp "-nm=_ZN5clang13RewriteBufferE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/core/RewriteBuffer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/RewriteRope.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/Rewriter.cpp "-nm=_ZN5clang11RewriteRopeE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/core/RewriteRope.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/RewriteObjC.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/Rewriter.cpp "-nm=_ZN5clang8RewriterE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/core/Rewriter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/RewriteRope.cpp "-nm=_ZN5clang9RopePieceE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/core/RopePiece.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/RewriteRope.cpp "-nm=_ZN5clang14RopePieceBTreeE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/core/RopePieceBTree.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/RewriteRope.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/Rewriter.cpp "-nm=_ZN5clang22RopePieceBTreeIteratorE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/core/RopePieceBTreeIterator.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/RewriteRope.cpp "-nm=_ZN5clang18RopeRefCountStringE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/core/RopeRefCountString.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/TokenRewriter.cpp "-nm=_ZN5clang13TokenRewriterE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/core/TokenRewriter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/FrontendActions.cpp "-nm=_ZN5clang11FixItActionE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/FixItAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/FixItRewriter.cpp "-nm=_ZN5clang12FixItOptionsE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/FixItOptions.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/FrontendActions.cpp "-nm=_ZN5clang14FixItRecompileE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/FixItRecompile.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/FixItRewriter.cpp "-nm=_ZN5clang13FixItRewriterE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/FixItRewriter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/FrontendActions.cpp "-nm=_ZN5clang15HTMLPrintActionE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/HTMLPrintAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/FrontendActions.cpp "-nm=_ZN5clang21RewriteIncludesActionE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/RewriteIncludesAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/FrontendActions.cpp "-nm=_ZN5clang19RewriteMacrosActionE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/RewriteMacrosAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/FrontendActions.cpp "-nm=_ZN5clang17RewriteObjCActionE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/RewriteObjCAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/FrontendActions.cpp "-nm=_ZN5clang17RewriteTestActionE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/RewriteTestAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/FrontendActions.cpp "-nm=_ZN12_GLOBAL__N_125FixItActionSuffixInserterE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/impl/FixItActionSuffixInserter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/FrontendActions.cpp "-nm=_ZN12_GLOBAL__N_119FixItRewriteInPlaceE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/impl/FixItRewriteInPlace.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/FrontendActions.cpp "-nm=_ZN12_GLOBAL__N_118FixItRewriteToTempE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/impl/FixItRewriteToTemp.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/HTMLPrint.cpp "-nm=_ZN12_GLOBAL__N_111HTMLPrinterE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/impl/HTMLPrinter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/InclusionRewriter.cpp "-nm=_ZN12_GLOBAL__N_117InclusionRewriterE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/impl/InclusionRewriter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/RewriteModernObjC.cpp "-nm=_ZN12_GLOBAL__N_117RewriteModernObjCE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/impl/RewriteModernObjC.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/RewriteObjC.cpp "-nm=_ZN12_GLOBAL__N_111RewriteObjCE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/impl/RewriteObjC.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/RewriteObjC.cpp "-nm=_ZN12_GLOBAL__N_121RewriteObjCFragileABIE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/impl/RewriteObjCFragileABI.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/FixItRewriter.cpp "-nm=_ZN12_GLOBAL__N_116RewritesReceiverE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/impl/RewritesReceiver.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/Rewriter.cpp "-nm=_ZN12_GLOBAL__N_119AtomicallyMovedFileE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/impl/AtomicallyMovedFile.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/DeltaTree.cpp "-nm=_ZN12_GLOBAL__N_121DeltaTreeInteriorNodeE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/impl/DeltaTreeInteriorNode.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/DeltaTree.cpp "-nm=_ZN12_GLOBAL__N_113DeltaTreeNodeE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/impl/DeltaTreeNode.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/RewriteRope.cpp "-nm=_ZN12_GLOBAL__N_122RopePieceBTreeInteriorE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/impl/RopePieceBTreeInterior.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/RewriteRope.cpp "-nm=_ZN12_GLOBAL__N_118RopePieceBTreeLeafE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/impl/RopePieceBTreeLeaf.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/RewriteRope.cpp "-nm=_ZN12_GLOBAL__N_118RopePieceBTreeNodeE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/impl/RopePieceBTreeNode.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/DeltaTree.cpp "-nm=_ZN12_GLOBAL__N_111SourceDeltaE;" > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/impl/SourceDelta.java

# Global and static namespaces
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/HTMLRewrite.cpp "-nm=_ZN5clang4html10EscapeTextEN4llvm9StringRefEbb;_ZN5clang4html10EscapeTextERNS_8RewriterENS_6FileIDEbb;_ZN5clang4html14AddLineNumbersERNS_8RewriterENS_6FileIDE;_ZN5clang4html14HighlightRangeERNS_13RewriteBufferEjjPKcS4_S4_;_ZN5clang4html14HighlightRangeERNS_8RewriterENS_11SourceRangeEPKcS5_;_ZN5clang4html14HighlightRangeERNS_8RewriterENS_14SourceLocationES3_PKcS5_;_ZN5clang4html15HighlightMacrosERNS_8RewriterENS_6FileIDERKNS_12PreprocessorE;_ZN5clang4html15SyntaxHighlightERNS_8RewriterENS_6FileIDERKNS_12PreprocessorE;_ZN5clang4html33AddHeaderFooterInternalBuiltinCSSERNS_8RewriterENS_6FileIDEPKc;" -static-type=html -package=org.clang.rewrite.core > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/core/html.java

# Static functions/variables
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/InclusionRewriter.cpp "-nm=_ZL9DetectEOLRKN4llvm12MemoryBufferE;" -static-type=InclusionRewriterStatics -package=org.clang.rewrite.frontend.impl > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/impl/InclusionRewriterStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/RewriteMacros.cpp "-nm=_ZL11isSameTokenRN5clang5TokenES1_;_ZL13GetNextRawTokRKSt6vectorIN5clang5TokenESaIS1_EERjb;_ZL24LexRawTokensFromMainFileRN5clang12PreprocessorERSt6vectorINS_5TokenESaIS3_EE;" -static-type=RewriteMacrosStatics -package=org.clang.rewrite.frontend.impl > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/impl/RewriteMacrosStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/RewriteModernObjC.cpp "-nm=_ZL12IsHeaderFileRKSs;_ZL13Write_class_tPN5clang10ASTContextERSsN4llvm9StringRefEPKNS_17ObjCInterfaceDeclEb;_ZL16Write_category_tRN12_GLOBAL__N_117RewriteModernObjCEPN5clang10ASTContextERSsPNS2_16ObjCCategoryDeclEPNS2_17ObjCInterfaceDeclEN4llvm8ArrayRefIPNS2_14ObjCMethodDeclEEESE_NSB_IPNS2_16ObjCProtocolDeclEEENSB_IPNS2_16ObjCPropertyDeclEEE;_ZL18scanToNextArgumentRPKc;_ZL19Write_IvarOffsetVarRN12_GLOBAL__N_117RewriteModernObjCEPN5clang10ASTContextERSsN4llvm8ArrayRefIPNS2_12ObjCIvarDeclEEEPNS2_17ObjCInterfaceDeclE;_ZL19Write_RethrowObjectRSs;_ZL19scanForProtocolRefsPKcS0_RS0_S1_;_ZL21BuildUniqueMethodNameRSsPN5clang14ObjCMethodDeclE;_ZL21WriteInternalIvarNamePKN5clang17ObjCInterfaceDeclEPNS_12ObjCIvarDeclERSs;_ZL25getFunctionSourceLocationRN12_GLOBAL__N_117RewriteModernObjCEPN5clang12FunctionDeclE;_ZL25hasObjCExceptionAttributeRN5clang10ASTContextEPKNS_17ObjCInterfaceDeclE;_ZL26RewriteOneForwardClassDeclPN5clang17ObjCInterfaceDeclERSs;_ZL27Write__ivar_list_t_TypeDeclRSsj;_ZL27Write__prop_list_t_TypeDeclRSsj;_ZL28Write_method_list_t_TypeDeclRSsj;_ZL29Write__class_ro_t_initializerPN5clang10ASTContextERSsjRKSsS4_N4llvm8ArrayRefIPNS_14ObjCMethodDeclEEENS6_IPNS_16ObjCProtocolDeclEEENS6_IPNS_12ObjCIvarDeclEEENS6_IPNS_16ObjCPropertyDeclEEENS5_9StringRefESJ_;_ZL29Write_prop_list_t_initializerRN12_GLOBAL__N_117RewriteModernObjCEPN5clang10ASTContextERSsN4llvm8ArrayRefIPNS2_16ObjCPropertyDeclEEEPKNS2_4DeclENS6_9StringRefESE_;_ZL30Write__ivar_list_t_initializerRN12_GLOBAL__N_117RewriteModernObjCEPN5clang10ASTContextERSsN4llvm8ArrayRefIPNS2_12ObjCIvarDeclEEENS6_9StringRefEPNS2_17ObjCInterfaceDeclE;_ZL30Write_protocol_list_t_TypeDeclRSsl;_ZL31HasLocalVariableExternalStoragePN5clang9ValueDeclE;_ZL31WriteModernMetadataDeclarationsPN5clang10ASTContextERSs;_ZL31Write_method_list_t_initializerRN12_GLOBAL__N_117RewriteModernObjCEPN5clang10ASTContextERSsN4llvm8ArrayRefIPNS2_14ObjCMethodDeclEEENS6_9StringRefESB_b;_ZL31Write_protocol_list_initializerPN5clang10ASTContextERSsN4llvm8ArrayRefIPNS_16ObjCProtocolDeclEEENS3_9StringRefES8_;_ZL32mustSynthesizeSetterGetterMethodPN5clang22ObjCImplementationDeclEPNS_16ObjCPropertyDeclEb;_ZL36Write_ProtocolExprReferencedMetadataPN5clang10ASTContextEPNS_16ObjCProtocolDeclERSs;_ZL38Write__extendedMethodTypes_initializerRN12_GLOBAL__N_117RewriteModernObjCEPN5clang10ASTContextERSsN4llvm8ArrayRefIPNS2_14ObjCMethodDeclEEENS6_9StringRefESB_;" -static-type=RewriteModernObjCStatics -package=org.clang.rewrite.frontend.impl > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/impl/RewriteModernObjCStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/RewriteObjC.cpp "-nm=_ZL12IsHeaderFileRKSs;_ZL18scanToNextArgumentRPKc;_ZL19getIvarAccessStringPN5clang12ObjCIvarDeclE;_ZL19scanForProtocolRefsPKcS0_RS0_S1_;_ZL21BuildUniqueMethodNameRSsPN5clang14ObjCMethodDeclE;_ZL26RewriteOneForwardClassDeclPN5clang17ObjCInterfaceDeclERSs;_ZL31HasLocalVariableExternalStoragePN5clang9ValueDeclE;" -static-type=RewriteObjCStatics -package=org.clang.rewrite.frontend.impl > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/impl/RewriteObjCStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/DeltaTree.cpp "-nm=_ZL7getRootPv;" -static-type=DeltaTreeStatics -package=org.clang.rewrite.impl > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/impl/DeltaTreeStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/HTMLRewrite.cpp "-nm=_ZL13AddLineNumberRN5clang13RewriteBufferEjjj;" -static-type=HTMLRewriteStatics -package=org.clang.rewrite.impl > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/impl/HTMLRewriteStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/RewriteRope.cpp "-nm=_ZL5getCNPKv;_ZL7getRootPv;" -static-type=RewriteRopeStatics -package=org.clang.rewrite.impl > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/impl/RewriteRopeStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Rewrite/Rewriter.cpp "-nm=_ZL20isWhitespaceExceptNLh;" -static-type=RewriterStatics -package=org.clang.rewrite.impl > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/impl/RewriterStatics.java

# Global functions/variables

# Global functions/variables for namespace as packages
${SPUTNIK}/contrib/JConvert/jclank.sh -body-delegate -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/HTMLPrint.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/InclusionRewriter.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/RewriteMacros.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/RewriteModernObjC.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/RewriteObjC.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/RewriteTest.cpp "-nm=_ZN5clang13DoRewriteTestERNS_12PreprocessorEPN4llvm11raw_ostreamE;_ZN5clang17CreateHTMLPrinterESt10unique_ptrIN4llvm11raw_ostreamESt14default_deleteIS2_EERNS_12PreprocessorEbb;_ZN5clang18CreateObjCRewriterERKSsSt10unique_ptrIN4llvm11raw_ostreamESt14default_deleteIS4_EERNS_17DiagnosticsEngineERKNS_11LangOptionsEb;_ZN5clang20RewriteMacrosInInputERNS_12PreprocessorEPN4llvm11raw_ostreamE;_ZN5clang22RewriteIncludesInInputERNS_12PreprocessorEPN4llvm11raw_ostreamERKNS_25PreprocessorOutputOptionsE;_ZN5clang24CreateModernObjCRewriterERKSsSt10unique_ptrIN4llvm11raw_ostreamESt14default_deleteIS4_EERNS_17DiagnosticsEngineERKNS_11LangOptionsEbb;" -static-type=RewriteClangGlobals -package=org.clang.rewrite.frontend > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/RewriteClangGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/RewriteObjC.cpp "-nm=_ZN5clang18CreateObjCRewriterERKSsSt10unique_ptrIN4llvm11raw_ostreamESt14default_deleteIS4_EERNS_17DiagnosticsEngineERKNS_11LangOptionsEb;" -static-type=RewriteObjCClangGlobals -package=org.clang.rewrite.frontend.impl > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/impl/RewriteObjCClangGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/RewriteTest.cpp "-nm=_ZN5clang13DoRewriteTestERNS_12PreprocessorEPN4llvm11raw_ostreamE;" -static-type=RewriteTestClangGlobals -package=org.clang.rewrite.frontend.impl > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/impl/RewriteTestClangGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/InclusionRewriter.cpp "-nm=_ZN5clang22RewriteIncludesInInputERNS_12PreprocessorEPN4llvm11raw_ostreamERKNS_25PreprocessorOutputOptionsE;" -static-type=InclusionRewriterClangGlobals -package=org.clang.rewrite.frontend.impl > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/impl/InclusionRewriterClangGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/RewriteModernObjC.cpp "-nm=_ZN5clang24CreateModernObjCRewriterERKSsSt10unique_ptrIN4llvm11raw_ostreamESt14default_deleteIS4_EERNS_17DiagnosticsEngineERKNS_11LangOptionsEbb;" -static-type=RewriteModernObjCClangGlobals -package=org.clang.rewrite.frontend.impl > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/impl/RewriteModernObjCClangGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/HTMLPrint.cpp "-nm=_ZN5clang17CreateHTMLPrinterESt10unique_ptrIN4llvm11raw_ostreamESt14default_deleteIS2_EERNS_12PreprocessorEbb;" -static-type=HTMLPrintClangGlobals -package=org.clang.rewrite.frontend.impl > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/impl/HTMLPrintClangGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.rewrite/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/Rewrite/RewriteMacros.cpp "-nm=_ZN5clang20RewriteMacrosInInputERNS_12PreprocessorEPN4llvm11raw_ostreamE;" -static-type=RewriteMacrosClangGlobals -package=org.clang.rewrite.frontend.impl > ${SPUTNIK}/modules/org.clang.rewrite/src/org/clang/rewrite/frontend/impl/RewriteMacrosClangGlobals.java

# Static functions/variables for namespaces as packages

