# Used directories
mkdir -p ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend
mkdir -p ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl
mkdir -p ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/llvm

# Global and static Enums
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendOptions.cpp "-nm=_ZN5clang9InputKindE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/InputKind.java

# Global and static CXXRecords, ClassTemplates, ClassTemplateSpecializations
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang17ASTDeclListActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/ASTDeclListAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang13ASTDumpActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/ASTDumpAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendAction.cpp "-nm=_ZN5clang17ASTFrontendActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/ASTFrontendAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTMerge.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang14ASTMergeActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/ASTMergeAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang14ASTPrintActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/ASTPrintAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp "-nm=_ZN5clang7ASTUnitE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/ASTUnit.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang13ASTViewActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/ASTViewAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ChainedDiagnosticConsumer.cpp "-nm=_ZN5clang25ChainedDiagnosticConsumerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/ChainedDiagnosticConsumer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/CodeGen/CodeGenAction.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CodeGenOptions.cpp ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Frontend/ModelInjector.cpp "-nm=_ZN5clang14CodeGenOptionsE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/CodeGenOptions.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CodeGenOptions.cpp ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Frontend/ModelInjector.cpp "-nm=_ZN5clang18CodeGenOptionsBaseE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/CodeGenOptionsBase.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp "-nm=_ZN5clang16CompilerInstanceE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/CompilerInstance.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CompilerInvocation.cpp "-nm=_ZN5clang18CompilerInvocationE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/CompilerInvocation.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CompilerInvocation.cpp "-nm=_ZN5clang22CompilerInvocationBaseE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/CompilerInvocationBase.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang22DeclContextPrintActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/DeclContextPrintAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMT.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DependencyFile.cpp "-nm=_ZN5clang19DependencyCollectorE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/DependencyCollector.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMT.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DependencyFile.cpp "-nm=_ZN5clang23DependencyFileGeneratorE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/DependencyFileGenerator.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DependencyFile.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Tooling/Tooling.cpp "-nm=_ZN5clang23DependencyOutputOptionsE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/DependencyOutputOptions.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DiagnosticRenderer.cpp "-nm=_ZN5clang22DiagnosticNoteRendererE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/DiagnosticNoteRenderer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DiagnosticRenderer.cpp "-nm=_ZN5clang18DiagnosticRendererE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/DiagnosticRenderer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang20DumpModuleInfoActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/DumpModuleInfoAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang19DumpRawTokensActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/DumpRawTokensAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang16DumpTokensActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/DumpTokensAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendAction.cpp "-nm=_ZN5clang14FrontendActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/FrontendAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendAction.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendOptions.cpp ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Frontend/ModelInjector.cpp "-nm=_ZN5clang17FrontendInputFileE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/FrontendInputFile.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendOptions.cpp "-nm=_ZN5clang15FrontendOptionsE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/FrontendOptions.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang20GenerateModuleActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/GenerateModuleAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang17GeneratePCHActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/GeneratePCHAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang17GeneratePTHActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/GeneratePTHAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang14InitOnlyActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/InitOnlyAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/LangStandards.cpp "-nm=_ZN5clang12LangStandardE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/LangStandard.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/LayoutOverrideSource.cpp "-nm=_ZN5clang20LayoutOverrideSourceE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/LayoutOverrideSource.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/LogDiagnosticPrinter.cpp "-nm=_ZN5clang20LogDiagnosticPrinterE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/LogDiagnosticPrinter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Frontend/ModelInjector.cpp ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransformActions.cpp "-nm=_ZN5clang15MigratorOptionsE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/MigratorOptions.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMT.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ModuleDependencyCollector.cpp "-nm=_ZN5clang25ModuleDependencyCollectorE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/ModuleDependencyCollector.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/MultiplexConsumer.cpp "-nm=_ZN5clang17MultiplexConsumerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/MultiplexConsumer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Tooling/CommonOptionsParser.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp "-nm=_ZN5clang20ParsedSourceLocationE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/ParsedSourceLocation.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendAction.cpp "-nm=_ZN5clang15PluginASTActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/PluginASTAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang20PreprocessOnlyActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/PreprocessOnlyAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendAction.cpp "-nm=_ZN5clang26PreprocessorFrontendActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/PreprocessorFrontendAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/StaticAnalyzer/Frontend/ModelInjector.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/PrintPreprocessedOutput.cpp "-nm=_ZN5clang25PreprocessorOutputOptionsE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/PreprocessorOutputOptions.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang19PrintPreambleActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/PrintPreambleAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang23PrintPreprocessedActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/PrintPreprocessedAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang16SyntaxOnlyActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/SyntaxOnlyAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/TextDiagnostic.cpp "-nm=_ZN5clang14TextDiagnosticE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/TextDiagnostic.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/TextDiagnosticBuffer.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/VerifyDiagnosticConsumer.cpp "-nm=_ZN5clang20TextDiagnosticBufferE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/TextDiagnosticBuffer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/TextDiagnosticPrinter.cpp "-nm=_ZN5clang21TextDiagnosticPrinterE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/TextDiagnosticPrinter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/VerifyDiagnosticConsumer.cpp "-nm=_ZN5clang24VerifyDiagnosticConsumerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/VerifyDiagnosticConsumer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang15VerifyPCHActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/VerifyPCHAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendAction.cpp "-nm=_ZN5clang21WrapperFrontendActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/WrapperFrontendAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTConsumers.cpp "-nm=_ZN12_GLOBAL__N_117ASTDeclNodeListerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/ASTDeclNodeLister.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp "-nm=_ZN12_GLOBAL__N_116ASTInfoCollectorE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/ASTInfoCollector.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTConsumers.cpp "-nm=_ZN12_GLOBAL__N_110ASTPrinterE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/ASTPrinter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTConsumers.cpp "-nm=_ZN12_GLOBAL__N_19ASTViewerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/ASTViewer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/SerializedDiagnosticPrinter.cpp "-nm=_ZN12_GLOBAL__N_115AbbreviationMapE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/AbbreviationMap.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp "-nm=_ZN12_GLOBAL__N_129AugmentedCodeCompleteConsumerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/AugmentedCodeCompleteConsumer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp "-nm=_ZN12_GLOBAL__N_125CaptureDroppedDiagnosticsE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/CaptureDroppedDiagnostics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ChainedIncludesSource.cpp "-nm=_ZN12_GLOBAL__N_121ChainedIncludesSourceE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/ChainedIncludesSource.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DependencyFile.cpp "-nm=_ZN12_GLOBAL__N_120DFGASTReaderListenerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/DFGASTReaderListener.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DependencyFile.cpp "-nm=_ZN12_GLOBAL__N_17DFGImplE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/DFGImpl.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTConsumers.cpp "-nm=_ZN12_GLOBAL__N_118DeclContextPrinterE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/DeclContextPrinter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendAction.cpp "-nm=_ZN12_GLOBAL__N_133DelegatingDeserializationListenerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/DelegatingDeserializationListener.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DependencyFile.cpp "-nm=_ZN12_GLOBAL__N_123DepCollectorASTListenerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/DepCollectorASTListener.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DependencyFile.cpp "-nm=_ZN12_GLOBAL__N_123DepCollectorPPCallbacksE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/DepCollectorPPCallbacks.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DependencyGraph.cpp "-nm=_ZN12_GLOBAL__N_123DependencyGraphCallbackE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/DependencyGraphCallback.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendAction.cpp "-nm=_ZN12_GLOBAL__N_124DeserializedDeclsCheckerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/DeserializedDeclsChecker.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendAction.cpp "-nm=_ZN12_GLOBAL__N_123DeserializedDeclsDumperE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/DeserializedDeclsDumper.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN12_GLOBAL__N_122DumpModuleInfoListenerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/DumpModuleInfoListener.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CacheTokens.cpp "-nm=_ZN12_GLOBAL__N_121FileEntryPTHEntryInfoE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/FileEntryPTHEntryInfo.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DiagnosticRenderer.cpp "-nm=_ZN12_GLOBAL__N_113FixitReceiverE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/FixitReceiver.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/HeaderIncludeGen.cpp "-nm=_ZN12_GLOBAL__N_122HeaderIncludesCallbackE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/HeaderIncludesCallback.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/InitHeaderSearch.cpp "-nm=_ZN12_GLOBAL__N_116InitHeaderSearchE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/InitHeaderSearch.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp "-nm=_ZN12_GLOBAL__N_133MacroDefinitionTrackerPPCallbacksE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/MacroDefinitionTrackerPPCallbacks.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ModuleDependencyCollector.cpp "-nm=_ZN12_GLOBAL__N_124ModuleDependencyListenerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/ModuleDependencyListener.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CompilerInvocation.cpp "-nm=_ZN12_GLOBAL__N_115ModuleSignatureE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/ModuleSignature.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/MultiplexConsumer.cpp "-nm=_ZN5clang35MultiplexASTDeserializationListenerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/MultiplexASTDeserializationListener.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/MultiplexConsumer.cpp "-nm=_ZN5clang28MultiplexASTMutationListenerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/MultiplexASTMutationListener.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CacheTokens.cpp "-nm=_ZN12_GLOBAL__N_19OffsetOptE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/OffsetOpt.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp "-nm=_ZN12_GLOBAL__N_110OnDiskDataE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/OnDiskData.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp "-nm=_ZN12_GLOBAL__N_114PCHLocatorInfoE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/PCHLocatorInfo.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CacheTokens.cpp "-nm=_ZN12_GLOBAL__N_18PTHEntryE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/PTHEntry.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CacheTokens.cpp "-nm=_ZN12_GLOBAL__N_118PTHEntryKeyVariantE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/PTHEntryKeyVariant.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CacheTokens.cpp "-nm=_ZN12_GLOBAL__N_18PTHIdKeyE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/PTHIdKey.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CacheTokens.cpp "-nm=_ZN12_GLOBAL__N_123PTHIdentifierTableTraitE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/PTHIdentifierTableTrait.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CacheTokens.cpp "-nm=_ZN12_GLOBAL__N_19PTHWriterE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/PTHWriter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/VerifyDiagnosticConsumer.cpp "-nm=_ZN12_GLOBAL__N_111ParseHelperE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/ParseHelper.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp "-nm=_ZN12_GLOBAL__N_124PrecompilePreambleActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/PrecompilePreambleAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp "-nm=_ZN12_GLOBAL__N_126PrecompilePreambleConsumerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/PrecompilePreambleConsumer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/PrintPreprocessedOutput.cpp "-nm=_ZN12_GLOBAL__N_124PrintPPOutputPPCallbacksE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/PrintPPOutputPPCallbacks.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/VerifyDiagnosticConsumer.cpp "-nm=_ZN12_GLOBAL__N_114RegexDirectiveE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/RegexDirective.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/SerializedDiagnosticReader.cpp "-nm=_ZN12_GLOBAL__N_119SDErrorCategoryTypeE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/SDErrorCategoryType.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/SerializedDiagnosticPrinter.cpp "-nm=_ZN12_GLOBAL__N_112SDiagsMergerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/SDiagsMerger.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/SerializedDiagnosticPrinter.cpp "-nm=_ZN12_GLOBAL__N_114SDiagsRendererE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/SDiagsRenderer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/SerializedDiagnosticPrinter.cpp "-nm=_ZN12_GLOBAL__N_112SDiagsWriterE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/SDiagsWriter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp "-nm=_ZN12_GLOBAL__N_111SimpleTimerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/SimpleTimer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/TextDiagnostic.cpp "-nm=_ZN12_GLOBAL__N_115SourceColumnMapE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/SourceColumnMap.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/VerifyDiagnosticConsumer.cpp "-nm=_ZN12_GLOBAL__N_117StandardDirectiveE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/StandardDirective.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CacheTokens.cpp "-nm=_ZN12_GLOBAL__N_112StatListenerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/StatListener.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp "-nm=_ZN12_GLOBAL__N_124StoredDiagnosticConsumerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/StoredDiagnosticConsumer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp "-nm=_ZN12_GLOBAL__N_125TopLevelDeclTrackerActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/TopLevelDeclTrackerAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp "-nm=_ZN12_GLOBAL__N_127TopLevelDeclTrackerConsumerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/TopLevelDeclTrackerConsumer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/PrintPreprocessedOutput.cpp "-nm=_ZN12_GLOBAL__N_120UnknownPragmaHandlerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/UnknownPragmaHandler.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/VerifyDiagnosticConsumer.cpp "-nm=_ZN12_GLOBAL__N_117VerifyFileTrackerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/VerifyFileTracker.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/SerializedDiagnosticReader.cpp "-nm=_ZSt18is_error_code_enumIN5clang16serialized_diags7SDErrorEE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/is_error_code_enumSDError.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendAction.cpp "-nm=_ZN4llvm8RegistryIN5clang15PluginASTActionENS_14RegistryTraitsIS2_EEEE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/llvm/Registry.java

# Global and static namespaces
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendOptions.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/LangStandards.cpp "-nm=_ZN5clang8frontend10ActionKindE;_ZN5clang8frontend12LangFeaturesE;" -static-type=frontend -package=org.clang.frontend > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/frontend.java
${SPUTNIK}/contrib/JConvert/jclank.sh -body-delegate -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/SerializedDiagnosticPrinter.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/SerializedDiagnosticReader.cpp "-nm=_ZN5clang16serialized_diags6createEN4llvm9StringRefEPNS_17DiagnosticOptionsEb;_ZN5clang16serialized_diags7SDErrorE;_ZN5clang16serialized_diags15SDErrorCategoryEv;_ZN5clang16serialized_diags15make_error_codeENS0_7SDErrorE;_ZN5clang16serialized_diags8LocationE;_ZN5clang16serialized_diags26SerializedDiagnosticReaderE;_ZN5clang16serialized_diags8BlockIDsE;_ZN5clang16serialized_diags9RecordIDsE;_ZN5clang16serialized_diags5LevelE;_ZN5clang16serialized_diagsE_SerializedDiagnostics_h_Unnamed_enum3;" -static-type=serialized_diags -package=org.clang.frontend > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/serialized_diags.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/SerializedDiagnosticReader.cpp "-nm=_ZN5clang16serialized_diags15SDErrorCategoryEv;_ZN5clang16serialized_diags15make_error_codeENS0_7SDErrorE;" -static-type=SerializedDiagnosticReaderSerialized_diagsGlobals -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/SerializedDiagnosticReaderSerialized_diagsGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/SerializedDiagnosticPrinter.cpp "-nm=_ZN5clang16serialized_diags6createEN4llvm9StringRefEPNS_17DiagnosticOptionsEb;" -static-type=SerializedDiagnosticPrinterSerialized_diagsGlobals -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/SerializedDiagnosticPrinterSerialized_diagsGlobals.java

# Static functions/variables
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp "-nm=_ZL14getOnDiskMutexv;_ZL22cleanupOnDiskMapAtExitv;_ZL16getOnDiskDataMapv;_ZL13getOnDiskDataPKN5clang7ASTUnitE;_ZL17erasePreambleFilePKN5clang7ASTUnitE;_ZL17removeOnDiskEntryPKN5clang7ASTUnitE;_ZL15setPreambleFilePKN5clang7ASTUnitEN4llvm9StringRefE;_ZL15getPreambleFilePKN5clang7ASTUnitE;_ZL30DefaultPreambleRebuildInterval;_ZL20ActiveASTUnitObjects;_ZL19getDeclShowContextsPKN5clang9NamedDeclERKNS_11LangOptionsERb;_ZN12_GLOBAL__N_128AddTopLevelDeclarationToHashEPN5clang4DeclERj;_ZL15isNonDriverDiagRKN5clang16StoredDiagnosticE;_ZL28checkAndRemoveNonDriverDiagsRN4llvm15SmallVectorImplIN5clang16StoredDiagnosticEEE;_ZL21checkAndSanitizeDiagsRN4llvm15SmallVectorImplIN5clang16StoredDiagnosticEEERNS1_13SourceManagerE;_ZL18GetPreamblePCHPathv;_ZL19makeStandaloneRangeN5clang15CharSourceRangeERKNS_13SourceManagerERKNS_11LangOptionsE;_ZL19makeStandaloneFixItRKN5clang13SourceManagerERKNS_11LangOptionsERKNS_9FixItHintE;_ZL24makeStandaloneDiagnosticRKN5clang11LangOptionsERKNS_16StoredDiagnosticE;_ZL20CalculateHiddenNamesRKN5clang21CodeCompletionContextEPNS_20CodeCompletionResultEjRNS_10ASTContextERN4llvm9StringSetINS7_20BumpPtrAllocatorImplINS7_15MallocAllocatorELm4096ELm4096EEEEE;_ZL13serializeUnitRN5clang9ASTWriterERN4llvm15SmallVectorImplIcEERNS_4SemaEbRNS2_11raw_ostreamE;_ZL10PCHLocatorRN5clang13serialization10ModuleFileEPv;" -static-type=ASTUnitStatics -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/ASTUnitStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ChainedIncludesSource.cpp "-nm=_ZL15createASTReaderRN5clang16CompilerInstanceEN4llvm9StringRefERNS2_15SmallVectorImplISt10unique_ptrINS2_12MemoryBufferESt14default_deleteIS6_EEEERNS4_ISsEEPNS_26ASTDeserializationListenerE;" -static-type=ChainedIncludesSourceStatics -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/ChainedIncludesSourceStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp "-nm=_ZL18SetUpDiagnosticLogPN5clang17DiagnosticOptionsEPKNS_14CodeGenOptionsERNS_17DiagnosticsEngineE;_ZL26SetupSerializedDiagnosticsPN5clang17DiagnosticOptionsERNS_17DiagnosticsEngineEN4llvm9StringRefE;_ZL23InitializeFileRemappingRN5clang17DiagnosticsEngineERNS_13SourceManagerERNS_11FileManagerERKNS_19PreprocessorOptionsE;_ZL20EnableCodeCompletionRN5clang12PreprocessorERKSsjj;_ZL29getSourceInputKindFromOptionsRKN5clang11LangOptionsE;_ZL17compileModuleImplRN5clang16CompilerInstanceENS_14SourceLocationEPNS_6ModuleEN4llvm9StringRefE;_ZL20compileAndLoadModuleRN5clang16CompilerInstanceENS_14SourceLocationES2_PNS_6ModuleEN4llvm9StringRefE;_ZL16checkConfigMacroRN5clang12PreprocessorEN4llvm9StringRefEPNS_6ModuleENS_14SourceLocationE;_ZL18writeTimestampFileN4llvm9StringRefE;_ZL16pruneModuleCacheRKN5clang19HeaderSearchOptionsE;" -static-type=CompilerInstanceStatics -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/CompilerInstanceStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CompilerInvocation.cpp "-nm=_ZL20getOptimizationLevelRN4llvm3opt7ArgListEN5clang9InputKindERNS3_17DiagnosticsEngineE;_ZL24getOptimizationLevelSizeRN4llvm3opt7ArgListE;_ZL17addDiagnosticArgsRN4llvm3opt7ArgListENS0_12OptSpecifierES3_RSt6vectorISsSaISsEE;_ZL17ParseAnalyzerArgsRN5clang15AnalyzerOptionsERN4llvm3opt7ArgListERNS_17DiagnosticsEngineE;_ZL17ParseMigratorArgsRN5clang15MigratorOptionsERN4llvm3opt7ArgListE;_ZL16ParseCommentArgsRN5clang14CommentOptionsERN4llvm3opt7ArgListE;_ZL12getCodeModelRN4llvm3opt7ArgListERN5clang17DiagnosticsEngineE;_ZL31GenerateOptimizationRemarkRegexRN5clang17DiagnosticsEngineERN4llvm3opt7ArgListEPNS3_3ArgE;_ZL19parseSanitizerKindsN4llvm9StringRefERKSt6vectorISsSaISsEERN5clang17DiagnosticsEngineERNS6_12SanitizerSetE;_ZL16ParseCodeGenArgsRN5clang14CodeGenOptionsERN4llvm3opt7ArgListENS_9InputKindERNS_17DiagnosticsEngineERKNS_13TargetOptionsE;_ZL25ParseDependencyOutputArgsRN5clang23DependencyOutputOptionsERN4llvm3opt7ArgListE;_ZL19ParseFileSystemArgsRN5clang17FileSystemOptionsERN4llvm3opt7ArgListE;_ZL17ParseFrontendArgsRN5clang15FrontendOptionsERN4llvm3opt7ArgListERNS_17DiagnosticsEngineE;_ZL21ParseHeaderSearchArgsRN5clang19HeaderSearchOptionsERN4llvm3opt7ArgListE;_ZL15parseVisibilityPN4llvm3opt3ArgERNS0_7ArgListERN5clang17DiagnosticsEngineE;_ZL15parseMSCVersionRN4llvm3opt7ArgListERN5clang17DiagnosticsEngineE;_ZL13ParseLangArgsRN5clang11LangOptionsERN4llvm3opt7ArgListENS_9InputKindERNS_17DiagnosticsEngineE;_ZL21ParsePreprocessorArgsRN5clang19PreprocessorOptionsERN4llvm3opt7ArgListERNS_11FileManagerERNS_17DiagnosticsEngineE;_ZL27ParsePreprocessorOutputArgsRN5clang25PreprocessorOutputOptionsERN4llvm3opt7ArgListENS_8frontend10ActionKindE;_ZL15ParseTargetArgsRN5clang13TargetOptionsERN4llvm3opt7ArgListE;" -static-type=CompilerInvocationStatics -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/CompilerInvocationStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DependencyFile.cpp "-nm=_ZL17isSpecialFilenameN4llvm9StringRefE;_ZL13PrintFilenameRN4llvm11raw_ostreamENS_9StringRefE;" -static-type=DependencyFileStatics -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/DependencyFileStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DiagnosticRenderer.cpp "-nm=_ZL21getImmediateMacroNameN5clang14SourceLocationERKNS_13SourceManagerERKNS_11LangOptionsE;_ZL11mergeFixitsN4llvm8ArrayRefIN5clang9FixItHintEEERKNS1_13SourceManagerERKNS1_11LangOptionsERNS_15SmallVectorImplIS2_EE;_ZL19mapDiagnosticRangesN5clang14SourceLocationEN4llvm8ArrayRefINS_15CharSourceRangeEEERNS1_15SmallVectorImplIS3_EEPKNS_13SourceManagerE;" -static-type=DiagnosticRendererStatics -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/DiagnosticRendererStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZpLRN4llvm15SmallVectorImplIcEENS_9StringRefE;_ZL16addHeaderIncludeN4llvm9StringRefERNS_15SmallVectorImplIcEERKN5clang11LangOptionsEb;_ZL16addHeaderIncludePKN5clang9FileEntryERN4llvm15SmallVectorImplIcEERKNS_11LangOptionsEb;_ZL27collectModuleHeaderIncludesRKN5clang11LangOptionsERNS_11FileManagerERNS_9ModuleMapEPNS_6ModuleERN4llvm15SmallVectorImplIcEE;" -static-type=FrontendActionsStatics -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/FrontendActionsStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/InitHeaderSearch.cpp "-nm=_ZL16CanPrefixSysrootN4llvm9StringRefE;_ZL16RemoveDuplicatesRSt6vectorIN5clang15DirectoryLookupESaIS1_EEjb;" -static-type=InitHeaderSearchStatics -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/InitHeaderSearchStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/InitPreprocessor.cpp "-nm=_ZL24MacroBodyEndsInBackslashN4llvm9StringRefE;_ZL18DefineBuiltinMacroRN5clang12MacroBuilderEN4llvm9StringRefERNS_17DiagnosticsEngineE;_ZL18AddImplicitIncludeRN5clang12MacroBuilderEN4llvm9StringRefE;_ZL24AddImplicitIncludeMacrosRN5clang12MacroBuilderEN4llvm9StringRefE;_ZL21AddImplicitIncludePTHRN5clang12MacroBuilderERNS_12PreprocessorEN4llvm9StringRefE;_ZL21AddImplicitIncludePCHRN5clang12MacroBuilderERNS_12PreprocessorEN4llvm9StringRefE;_ZL6PickFPPKN4llvm12fltSemanticsET_S3_S3_S3_S3_;_ZL17DefineFloatMacrosRN5clang12MacroBuilderEN4llvm9StringRefEPKNS2_12fltSemanticsES3_;_ZL14DefineTypeSizeRKN4llvm5TwineEjNS_9StringRefEbRN5clang12MacroBuilderE;_ZL14DefineTypeSizeRKN4llvm5TwineEN5clang10TargetInfo7IntTypeERKS4_RNS3_12MacroBuilderE;_ZL9DefineFmtRKN4llvm5TwineEN5clang10TargetInfo7IntTypeERKS4_RNS3_12MacroBuilderE;_ZL10DefineTypeRKN4llvm5TwineEN5clang10TargetInfo7IntTypeERNS3_12MacroBuilderE;_ZL15DefineTypeWidthN4llvm9StringRefEN5clang10TargetInfo7IntTypeERKS2_RNS1_12MacroBuilderE;_ZL16DefineTypeSizeofN4llvm9StringRefEjRKN5clang10TargetInfoERNS1_12MacroBuilderE;_ZL23DefineExactWidthIntTypeN5clang10TargetInfo7IntTypeERKS0_RNS_12MacroBuilderE;_ZL27DefineExactWidthIntTypeSizeN5clang10TargetInfo7IntTypeERKS0_RNS_12MacroBuilderE;_ZL23DefineLeastWidthIntTypejbRKN5clang10TargetInfoERNS_12MacroBuilderE;_ZL17DefineFastIntTypejbRKN5clang10TargetInfoERNS_12MacroBuilderE;_ZL16getLockFreeValuejjj;_ZL28AddObjCXXARCLibstdcxxDefinesRKN5clang11LangOptionsERNS_12MacroBuilderE;_ZL34InitializeStandardPredefinedMacrosRKN5clang10TargetInfoERKNS_11LangOptionsERKNS_15FrontendOptionsERNS_12MacroBuilderE;_ZL36InitializeCPlusPlusFeatureTestMacrosRKN5clang11LangOptionsERNS_12MacroBuilderE;_ZL26InitializePredefinedMacrosRKN5clang10TargetInfoERKNS_11LangOptionsERKNS_15FrontendOptionsERNS_12MacroBuilderE;" -static-type=InitPreprocessorStatics -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/InitPreprocessorStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/LayoutOverrideSource.cpp "-nm=_ZL9parseNameN4llvm9StringRefE;" -static-type=LayoutOverrideSourceStatics -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/LayoutOverrideSourceStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/PrintPreprocessedOutput.cpp "-nm=_ZL20PrintMacroDefinitionRKN5clang14IdentifierInfoERKNS_9MacroInfoERNS_12PreprocessorERN4llvm11raw_ostreamE;_ZL15outputPrintableRN4llvm11raw_ostreamERKSs;_ZL23PrintPreprocessedTokensRN5clang12PreprocessorERNS_5TokenEPN12_GLOBAL__N_124PrintPPOutputPPCallbacksERN4llvm11raw_ostreamE;_ZL14MacroIDComparePKSt4pairIPKN5clang14IdentifierInfoEPNS0_9MacroInfoEES8_;_ZL13DoPrintMacrosRN5clang12PreprocessorEPN4llvm11raw_ostreamE;" -static-type=PrintPreprocessedOutputStatics -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/PrintPreprocessedOutputStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/SerializedDiagnosticPrinter.cpp "-nm=_ZL23AddSourceLocationAbbrevPN4llvm13BitCodeAbbrevE;_ZL22AddRangeLocationAbbrevPN4llvm13BitCodeAbbrevE;_ZL14getStableLevelN5clang17DiagnosticsEngine5LevelE;" -static-type=SerializedDiagnosticPrinterStatics -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/SerializedDiagnosticPrinterStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/SerializedDiagnosticReader.cpp "-nm=_ZL13ErrorCategory;" -static-type=SerializedDiagnosticReaderStatics -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/SerializedDiagnosticReaderStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/TextDiagnosticPrinter.cpp "-nm=_ZL22printDiagnosticOptionsRN4llvm11raw_ostreamEN5clang17DiagnosticsEngine5LevelERKNS2_10DiagnosticERKNS2_17DiagnosticOptionsE;" -static-type=TextDiagnosticPrinterStatics -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/TextDiagnosticPrinterStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/TextDiagnostic.cpp "-nm=_ZL9noteColor;_ZL11remarkColor;_ZL10fixitColor;_ZL10caretColor;_ZL12warningColor;_ZL13templateColor;_ZL10errorColor;_ZL10fatalColor;_ZL10savedColor;_ZL25applyTemplateHighlightingRN4llvm11raw_ostreamENS_9StringRefERbb;_ZL19WordWrapIndentation;_ZL32bytesSincePreviousTabOrLineBeginN4llvm9StringRefEm;_ZL29printableTextForNextCharacterN4llvm9StringRefEPmj;_ZL10expandTabsRSsj;_ZL12byteToColumnN4llvm9StringRefEjRNS_15SmallVectorImplIiEE;_ZL12columnToByteN4llvm9StringRefEjRNS_15SmallVectorImplIiEE;_ZL29selectInterestingSourceRegionRSsS_S_jRKN12_GLOBAL__N_115SourceColumnMapE;_ZL14skipWhitespacejN4llvm9StringRefEj;_ZL23findMatchingPunctuationc;_ZL13findEndOfWordjN4llvm9StringRefEjjj;_ZL16printWordWrappedRN4llvm11raw_ostreamENS_9StringRefEjjbj;_ZL14highlightRangeRKN5clang15CharSourceRangeEjNS_6FileIDERKN12_GLOBAL__N_115SourceColumnMapERSsRKNS_13SourceManagerERKNS_11LangOptionsE;_ZL23buildFixItInsertionLinejRKN12_GLOBAL__N_115SourceColumnMapEN4llvm8ArrayRefIN5clang9FixItHintEEERKNS5_13SourceManagerEPKNS5_17DiagnosticOptionsE;" -static-type=TextDiagnosticStatics -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/TextDiagnosticStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/VerifyDiagnosticConsumer.cpp "-nm=_ZL14ParseDirectiveN4llvm9StringRefEPN5clang24VerifyDiagnosticConsumer12ExpectedDataERNS1_13SourceManagerEPNS1_12PreprocessorENS1_14SourceLocationERNS2_15DirectiveStatusE;_ZL14findDirectivesRN5clang13SourceManagerENS_6FileIDERKNS_11LangOptionsE;_ZL15PrintUnexpectedRN5clang17DiagnosticsEngineEPNS_13SourceManagerEN9__gnu_cxx17__normal_iteratorIPKSt4pairINS_14SourceLocationESsESt6vectorIS8_SaIS8_EEEESE_PKc;_ZL13PrintExpectedRN5clang17DiagnosticsEngineERNS_13SourceManagerERSt6vectorIPNS_24VerifyDiagnosticConsumer9DirectiveESaIS7_EEPKc;_ZL14IsFromSameFileRN5clang13SourceManagerENS_14SourceLocationES2_;_ZL10CheckListsRN5clang17DiagnosticsEngineERNS_13SourceManagerEPKcRSt6vectorISt10unique_ptrINS_24VerifyDiagnosticConsumer9DirectiveESt14default_deleteIS9_EESaISC_EEN9__gnu_cxx17__normal_iteratorIPKSt4pairINS_14SourceLocationESsES6_ISK_SaISK_EEEESP_;_ZL12CheckResultsRN5clang17DiagnosticsEngineERNS_13SourceManagerERKNS_20TextDiagnosticBufferERNS_24VerifyDiagnosticConsumer12ExpectedDataE;" -static-type=VerifyDiagnosticConsumerStatics -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/VerifyDiagnosticConsumerStatics.java

# Global functions/variables
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/LangStandards.cpp "-nm=_ZL8Lang_c89;_ZL8Lang_c90;_ZL17Lang_iso9899_1990;_ZL8Lang_c94;_ZL10Lang_gnu89;_ZL10Lang_gnu90;_ZL8Lang_c99;_ZL8Lang_c9x;_ZL17Lang_iso9899_1999;_ZL17Lang_iso9899_199x;_ZL10Lang_gnu99;_ZL10Lang_gnu9x;_ZL8Lang_c11;_ZL8Lang_c1x;_ZL17Lang_iso9899_2011;_ZL17Lang_iso9899_201x;_ZL10Lang_gnu11;_ZL10Lang_gnu1x;_ZL10Lang_cxx98;_ZL10Lang_cxx03;_ZL13Lang_gnucxx98;_ZL10Lang_cxx0x;_ZL10Lang_cxx11;_ZL13Lang_gnucxx0x;_ZL13Lang_gnucxx11;_ZL10Lang_cxx1y;_ZL10Lang_cxx14;_ZL13Lang_gnucxx1y;_ZL13Lang_gnucxx14;_ZL10Lang_cxx1z;_ZL13Lang_gnucxx1z;_ZL11Lang_opencl;_ZL13Lang_opencl11;_ZL13Lang_opencl12;_ZL13Lang_opencl20;_ZL9Lang_cuda;" -static-type=LangStandardsGlobals -package=org.clang.frontend > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/LangStandardsGlobals.java

# Global functions/variables for namespace as packages
${SPUTNIK}/contrib/JConvert/jclank.sh -body-delegate -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMT.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTConsumers.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CacheTokens.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ChainedIncludesSource.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CreateInvocationFromCommandLine.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DependencyGraph.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/HeaderIncludeGen.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/InitHeaderSearch.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/InitPreprocessor.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/PrintPreprocessedOutput.cpp "-nm=_ZN5clang16CreateASTPrinterEPN4llvm11raw_ostreamENS0_9StringRefE;_ZN5clang15CreateASTDumperEN4llvm9StringRefEbb;_ZN5clang23CreateASTDeclNodeListerEv;_ZN5clang15CreateASTViewerEv;_ZN5clang24CreateDeclContextPrinterEv;_ZN5clang19ParseDiagnosticArgsERNS_17DiagnosticOptionsERN4llvm3opt7ArgListEPNS_17DiagnosticsEngineE;_ZN5clang31createVFSFromCompilerInvocationERKNS_18CompilerInvocationERNS_17DiagnosticsEngineE;_ZN5clang24ApplyHeaderSearchOptionsERNS_12HeaderSearchERKNS_19HeaderSearchOptionsERKNS_11LangOptionsERKN4llvm6TripleE;_ZN5clang22InitializePreprocessorERNS_12PreprocessorERKNS_19PreprocessorOptionsERKNS_15FrontendOptionsE;_ZN5clang24DoPrintPreprocessedInputERNS_12PreprocessorEPN4llvm11raw_ostreamERKNS_25PreprocessorOutputOptionsE;_ZN5clang24AttachDependencyGraphGenERNS_12PreprocessorEN4llvm9StringRefES3_;_ZN5clang22AttachHeaderIncludeGenERNS_12PreprocessorEbN4llvm9StringRefEbb;_ZN5clang11CacheTokensERNS_12PreprocessorEPN4llvm14raw_fd_ostreamE;_ZN5clang27createChainedIncludesSourceERNS_16CompilerInstanceERN4llvm18IntrusiveRefCntPtrINS_18ExternalSemaSourceEEE;_ZN5clang31createInvocationFromCommandLineEN4llvm8ArrayRefIPKcEENS0_18IntrusiveRefCntPtrINS_17DiagnosticsEngineEEE;_ZN5clang18getLastArgIntValueERKN4llvm3opt7ArgListENS1_12OptSpecifierEiPNS_17DiagnosticsEngineE;_ZN5clang18getLastArgIntValueERKN4llvm3opt7ArgListENS1_12OptSpecifierEiRNS_17DiagnosticsEngineE;_ZN5clang21getLastArgUInt64ValueERKN4llvm3opt7ArgListENS1_12OptSpecifierEmPNS_17DiagnosticsEngineE;_ZN5clang21getLastArgUInt64ValueERKN4llvm3opt7ArgListENS1_12OptSpecifierEmRNS_17DiagnosticsEngineE;_ZN5clang11BuryPointerEPKv;_ZN5clang11BuryPointerESt10unique_ptrIT_St14default_deleteIS1_EE;" -static-type=ClangGlobals -package=org.clang.frontend > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/ClangGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.ast/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CompilerInvocation.cpp "-nm=_ZN5clang19ParseDiagnosticArgsERNS_17DiagnosticOptionsERN4llvm3opt7ArgListEPNS_17DiagnosticsEngineE;_ZN5clang31createVFSFromCompilerInvocationERKNS_18CompilerInvocationERNS_17DiagnosticsEngineE;_ZN5clang18getLastArgIntValueERKN4llvm3opt7ArgListENS1_12OptSpecifierEiPNS_17DiagnosticsEngineE;_ZN5clang21getLastArgUInt64ValueERKN4llvm3opt7ArgListENS1_12OptSpecifierEmPNS_17DiagnosticsEngineE;_ZN5clang11BuryPointerEPKv;" -static-type=CompilerInvocationClangGlobals -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/CompilerInvocationClangGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.ast/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DependencyGraph.cpp "-nm=_ZN5clang24AttachDependencyGraphGenERNS_12PreprocessorEN4llvm9StringRefES3_;" -static-type=DependencyGraphClangGlobals -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/DependencyGraphClangGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.ast/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/InitPreprocessor.cpp "-nm=_ZN5clang22InitializePreprocessorERNS_12PreprocessorERKNS_19PreprocessorOptionsERKNS_15FrontendOptionsE;" -static-type=InitPreprocessorClangGlobals -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/InitPreprocessorClangGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.ast/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/InitHeaderSearch.cpp "-nm=_ZN5clang24ApplyHeaderSearchOptionsERNS_12HeaderSearchERKNS_19HeaderSearchOptionsERKNS_11LangOptionsERKN4llvm6TripleE;" -static-type=InitHeaderSearchClangGlobals -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/InitHeaderSearchClangGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.ast/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ChainedIncludesSource.cpp "-nm=_ZN5clang27createChainedIncludesSourceERNS_16CompilerInstanceERN4llvm18IntrusiveRefCntPtrINS_18ExternalSemaSourceEEE;" -static-type=ChainedIncludesSourceClangGlobals -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/ChainedIncludesSourceClangGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.ast/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/HeaderIncludeGen.cpp "-nm=_ZN5clang22AttachHeaderIncludeGenERNS_12PreprocessorEbN4llvm9StringRefEbb;" -static-type=HeaderIncludeGenClangGlobals -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/HeaderIncludeGenClangGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.ast/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CacheTokens.cpp "-nm=_ZN5clang11CacheTokensERNS_12PreprocessorEPN4llvm14raw_fd_ostreamE;" -static-type=CacheTokensClangGlobals -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/CacheTokensClangGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.ast/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/PrintPreprocessedOutput.cpp "-nm=_ZN5clang24DoPrintPreprocessedInputERNS_12PreprocessorEPN4llvm11raw_ostreamERKNS_25PreprocessorOutputOptionsE;" -static-type=PrintPreprocessedOutputClangGlobals -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/PrintPreprocessedOutputClangGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.ast/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMT.cpp "-nm=_ZN5clang18getLastArgIntValueERKN4llvm3opt7ArgListENS1_12OptSpecifierEiRNS_17DiagnosticsEngineE;_ZN5clang21getLastArgUInt64ValueERKN4llvm3opt7ArgListENS1_12OptSpecifierEmRNS_17DiagnosticsEngineE;_ZN5clang11BuryPointerESt10unique_ptrIT_St14default_deleteIS1_EE;" -static-type=UtilsClangGlobals -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/UtilsClangGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.ast/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTConsumers.cpp "-nm=_ZN5clang16CreateASTPrinterEPN4llvm11raw_ostreamENS0_9StringRefE;_ZN5clang15CreateASTDumperEN4llvm9StringRefEbb;_ZN5clang23CreateASTDeclNodeListerEv;_ZN5clang15CreateASTViewerEv;_ZN5clang24CreateDeclContextPrinterEv;" -static-type=ASTConsumersClangGlobals -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/ASTConsumersClangGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.ast/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CreateInvocationFromCommandLine.cpp "-nm=_ZN5clang31createInvocationFromCommandLineEN4llvm8ArrayRefIPKcEENS0_18IntrusiveRefCntPtrINS_17DiagnosticsEngineEEE;" -static-type=CreateInvocationFromCommandLineClangGlobals -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/CreateInvocationFromCommandLineClangGlobals.java

# Static functions/variables for namespaces as packages
${SPUTNIK}/contrib/JConvert/jclank.sh -body-delegate -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CompilerInvocation.cpp "-nm=_ZN5clangeqERKNS_7ASTUnit16PreambleFileHashES3_;_ZN5clangL22getLastArgIntValueImplERKN4llvm3opt7ArgListENS1_12OptSpecifierET_PNS_17DiagnosticsEngineE;" -static-type=ClangStatics -package=org.clang.frontend > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/ClangStatics.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.ast/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CompilerInvocation.cpp "-nm=_ZN5clangL22getLastArgIntValueImplERKN4llvm3opt7ArgListENS1_12OptSpecifierET_PNS_17DiagnosticsEngineE;" -static-type=CompilerInvocationClangStatics -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/CompilerInvocationClangStatics.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.ast/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp "-nm=_ZN5clangeqERKNS_7ASTUnit16PreambleFileHashES3_;" -static-type=ASTUnitClangStatics -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/ASTUnitClangStatics.java

