# Used directories
mkdir -p ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend
mkdir -p ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl

# Global and static Enums
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DependencyFile.cpp "-nm=_ZN5clang22DependencyOutputFormatE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/DependencyOutputFormat.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendOptions.cpp "-nm=_ZN5clang9InputKindE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/InputKind.java

# Global and static CXXRecords, ClassTemplates, ClassTemplateSpecializations
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTMerge.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang14ASTMergeActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/ASTMergeAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp "-nm=_ZN5clang7ASTUnitE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/ASTUnit.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CodeGenOptions.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang14CodeGenOptionsE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/CodeGenOptions.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CodeGenOptions.cpp "-nm=_ZN5clang18CodeGenOptionsBaseE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/CodeGenOptionsBase.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp "-nm=_ZN5clang16CompilerInstanceE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/CompilerInstance.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CompilerInvocation.cpp "-nm=_ZN5clang18CompilerInvocationE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/CompilerInvocation.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CompilerInvocation.cpp "-nm=_ZN5clang22CompilerInvocationBaseE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/CompilerInvocationBase.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DependencyFile.cpp ${LLVM_SRC}/llvm/tools/clang/tools/driver/driver.cpp "-nm=_ZN5clang19DependencyCollectorE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/DependencyCollector.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DependencyFile.cpp ${LLVM_SRC}/llvm/tools/clang/tools/driver/driver.cpp "-nm=_ZN5clang23DependencyFileGeneratorE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/DependencyFileGenerator.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DependencyFile.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang23DependencyOutputOptionsE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/DependencyOutputOptions.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DiagnosticRenderer.cpp "-nm=_ZN5clang22DiagnosticNoteRendererE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/DiagnosticNoteRenderer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DiagnosticRenderer.cpp "-nm=_ZN5clang18DiagnosticRendererE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/DiagnosticRenderer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang20DumpModuleInfoActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/DumpModuleInfoAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendAction.cpp "-nm=_ZN5clang14FrontendActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/FrontendAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendAction.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendOptions.cpp "-nm=_ZN5clang17FrontendInputFileE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/FrontendInputFile.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendOptions.cpp "-nm=_ZN5clang15FrontendOptionsE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/FrontendOptions.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang20GenerateModuleActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/GenerateModuleAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang17GeneratePCHActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/GeneratePCHAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang17GeneratePTHActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/GeneratePTHAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/LogDiagnosticPrinter.cpp "-nm=_ZN5clang20LogDiagnosticPrinterE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/LogDiagnosticPrinter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/MultiplexConsumer.cpp "-nm=_ZN5clang17MultiplexConsumerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/MultiplexConsumer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/PCHContainerOperations.cpp "-nm=_ZN5clang9PCHBufferE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/PCHBuffer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/PCHContainerOperations.cpp ${LLVM_SRC}/llvm/tools/clang/tools/driver/cc1_main.cpp "-nm=_ZN5clang22PCHContainerOperationsE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/PCHContainerOperations.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Basic/FileManager.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/PCHContainerOperations.cpp "-nm=_ZN5clang18PCHContainerReaderE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/PCHContainerReader.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Basic/FileManager.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/PCHContainerOperations.cpp "-nm=_ZN5clang18PCHContainerWriterE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/PCHContainerWriter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/PrintPreprocessedOutput.cpp "-nm=_ZN5clang25PreprocessorOutputOptionsE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/PreprocessorOutputOptions.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang19PrintPreambleActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/PrintPreambleAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/PCHContainerOperations.cpp "-nm=_ZN5clang21RawPCHContainerReaderE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/RawPCHContainerReader.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/PCHContainerOperations.cpp "-nm=_ZN5clang21RawPCHContainerWriterE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/RawPCHContainerWriter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/TextDiagnostic.cpp "-nm=_ZN5clang14TextDiagnosticE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/TextDiagnostic.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/TextDiagnosticBuffer.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/VerifyDiagnosticConsumer.cpp "-nm=_ZN5clang20TextDiagnosticBufferE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/TextDiagnosticBuffer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/VerifyDiagnosticConsumer.cpp "-nm=_ZN5clang24VerifyDiagnosticConsumerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/VerifyDiagnosticConsumer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN5clang15VerifyPCHActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/VerifyPCHAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp "-nm=_ZN12_GLOBAL__N_116ASTInfoCollectorE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/ASTInfoCollector.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp "-nm=_ZN12_GLOBAL__N_129AugmentedCodeCompleteConsumerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/AugmentedCodeCompleteConsumer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ChainedIncludesSource.cpp "-nm=_ZN12_GLOBAL__N_121ChainedIncludesSourceE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/ChainedIncludesSource.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DependencyFile.cpp "-nm=_ZN12_GLOBAL__N_120DFGASTReaderListenerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/DFGASTReaderListener.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DependencyFile.cpp "-nm=_ZN12_GLOBAL__N_17DFGImplE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/DFGImpl.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DependencyFile.cpp "-nm=_ZN12_GLOBAL__N_113DFGMMCallbackE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/DFGMMCallback.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendAction.cpp "-nm=_ZN12_GLOBAL__N_133DelegatingDeserializationListenerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/DelegatingDeserializationListener.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DependencyFile.cpp "-nm=_ZN12_GLOBAL__N_123DepCollectorASTListenerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/DepCollectorASTListener.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DependencyFile.cpp "-nm=_ZN12_GLOBAL__N_123DepCollectorMMCallbacksE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/DepCollectorMMCallbacks.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DependencyFile.cpp "-nm=_ZN12_GLOBAL__N_123DepCollectorPPCallbacksE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/DepCollectorPPCallbacks.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZN12_GLOBAL__N_122DumpModuleInfoListenerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/DumpModuleInfoListener.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/HeaderIncludeGen.cpp "-nm=_ZN12_GLOBAL__N_122HeaderIncludesCallbackE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/HeaderIncludesCallback.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/InitHeaderSearch.cpp "-nm=_ZN12_GLOBAL__N_116InitHeaderSearchE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/InitHeaderSearch.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ModuleDependencyCollector.cpp "-nm=_ZN12_GLOBAL__N_124ModuleDependencyListenerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/ModuleDependencyListener.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CompilerInvocation.cpp "-nm=_ZN12_GLOBAL__N_115ModuleSignatureE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/ModuleSignature.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/MultiplexConsumer.cpp "-nm=_ZN5clang35MultiplexASTDeserializationListenerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/MultiplexASTDeserializationListener.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/MultiplexConsumer.cpp "-nm=_ZN5clang28MultiplexASTMutationListenerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/MultiplexASTMutationListener.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp "-nm=_ZN12_GLOBAL__N_110OnDiskDataE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/OnDiskData.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CacheTokens.cpp "-nm=_ZN12_GLOBAL__N_118PTHEntryKeyVariantE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/PTHEntryKeyVariant.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CacheTokens.cpp "-nm=_ZN12_GLOBAL__N_19PTHWriterE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/PTHWriter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp "-nm=_ZN12_GLOBAL__N_124PrecompilePreambleActionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/PrecompilePreambleAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp "-nm=_ZN12_GLOBAL__N_126PrecompilePreambleConsumerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/PrecompilePreambleConsumer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/PrintPreprocessedOutput.cpp "-nm=_ZN12_GLOBAL__N_124PrintPPOutputPPCallbacksE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/PrintPPOutputPPCallbacks.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/PCHContainerOperations.cpp "-nm=_ZN12_GLOBAL__N_124RawPCHContainerGeneratorE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/RawPCHContainerGenerator.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/VerifyDiagnosticConsumer.cpp "-nm=_ZN12_GLOBAL__N_114RegexDirectiveE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/RegexDirective.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/SerializedDiagnosticPrinter.cpp "-nm=_ZN12_GLOBAL__N_112SDiagsMergerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/SDiagsMerger.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/SerializedDiagnosticPrinter.cpp "-nm=_ZN12_GLOBAL__N_112SDiagsWriterE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/SDiagsWriter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp "-nm=_ZN12_GLOBAL__N_124StoredDiagnosticConsumerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/StoredDiagnosticConsumer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/TestModuleFileExtension.cpp "-nm=_ZN5clang23TestModuleFileExtensionE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/TestModuleFileExtension.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp "-nm=_ZN12_GLOBAL__N_127TopLevelDeclTrackerConsumerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/TopLevelDeclTrackerConsumer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/PrintPreprocessedOutput.cpp "-nm=_ZN12_GLOBAL__N_120UnknownPragmaHandlerE;" > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/UnknownPragmaHandler.java

# Global and static namespaces
${SPUTNIK}/contrib/JConvert/jclank.sh -body-delegate -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/SerializedDiagnosticPrinter.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/SerializedDiagnosticReader.cpp "-nm=_ZN5clang16serialized_diags6createEN4llvm9StringRefEPNS_17DiagnosticOptionsEb;_ZN5clang16serialized_diags7SDErrorE;_ZN5clang16serialized_diags15SDErrorCategoryEv;_ZN5clang16serialized_diags15make_error_codeENS0_7SDErrorE;_ZN5clang16serialized_diags8LocationE;_ZN5clang16serialized_diags26SerializedDiagnosticReaderE;_ZN5clang16serialized_diags8BlockIDsE;_ZN5clang16serialized_diags9RecordIDsE;_ZN5clang16serialized_diags5LevelE;_ZN5clang16serialized_diagsE_SerializedDiagnostics_h_Unnamed_enum3;" -static-type=serialized_diags > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/serialized_diags.java

# Static functions/variables
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp "-nm=_ZL14getOnDiskMutexv;_ZL22cleanupOnDiskMapAtExitv;_ZL16getOnDiskDataMapv;_ZL13getOnDiskDataPKN5clang7ASTUnitE;_ZL17erasePreambleFilePKN5clang7ASTUnitE;_ZL17removeOnDiskEntryPKN5clang7ASTUnitE;_ZL15setPreambleFilePKN5clang7ASTUnitEN4llvm9StringRefE;_ZL15getPreambleFilePKN5clang7ASTUnitE;_ZL30DefaultPreambleRebuildInterval;_ZL20ActiveASTUnitObjects;_ZL19getDeclShowContextsPKN5clang9NamedDeclERKNS_11LangOptionsERb;_ZN12_GLOBAL__N_128AddTopLevelDeclarationToHashEPN5clang4DeclERj;_ZL15isNonDriverDiagRKN5clang16StoredDiagnosticE;_ZL28checkAndRemoveNonDriverDiagsRN4llvm15SmallVectorImplIN5clang16StoredDiagnosticEEE;_ZL21checkAndSanitizeDiagsRN4llvm15SmallVectorImplIN5clang16StoredDiagnosticEEERNS1_13SourceManagerE;_ZL18GetPreamblePCHPathv;_ZL19makeStandaloneRangeN5clang15CharSourceRangeERKNS_13SourceManagerERKNS_11LangOptionsE;_ZL19makeStandaloneFixItRKN5clang13SourceManagerERKNS_11LangOptionsERKNS_9FixItHintE;_ZL24makeStandaloneDiagnosticRKN5clang11LangOptionsERKNS_16StoredDiagnosticE;_ZL20CalculateHiddenNamesRKN5clang21CodeCompletionContextEPNS_20CodeCompletionResultEjRNS_10ASTContextERN4llvm9StringSetINS7_20BumpPtrAllocatorImplINS7_15MallocAllocatorELm4096ELm4096EEEEE;_ZL13serializeUnitRN5clang9ASTWriterERN4llvm15SmallVectorImplIcEERNS_4SemaEbRNS2_11raw_ostreamE;" -static-type=ASTUnitStatics > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/ASTUnitStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CacheTokens.cpp "-nm=_ZL8swap32lej;_ZL10pwrite32leRN4llvm17raw_pwrite_streamEjRm;" -static-type=CacheTokensStatics > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/CacheTokensStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ChainedIncludesSource.cpp "-nm=_ZL15createASTReaderRN5clang16CompilerInstanceEN4llvm9StringRefERNS2_15SmallVectorImplISt10unique_ptrINS2_12MemoryBufferESt14default_deleteIS6_EEEERNS4_ISsEEPNS_26ASTDeserializationListenerE;" -static-type=ChainedIncludesSourceStatics > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/ChainedIncludesSourceStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp "-nm=_ZL18SetUpDiagnosticLogPN5clang17DiagnosticOptionsEPKNS_14CodeGenOptionsERNS_17DiagnosticsEngineE;_ZL26SetupSerializedDiagnosticsPN5clang17DiagnosticOptionsERNS_17DiagnosticsEngineEN4llvm9StringRefE;_ZL23InitializeFileRemappingRN5clang17DiagnosticsEngineERNS_13SourceManagerERNS_11FileManagerERKNS_19PreprocessorOptionsE;_ZL20EnableCodeCompletionRN5clang12PreprocessorERKSsjj;_ZL29getSourceInputKindFromOptionsRKN5clang11LangOptionsE;_ZL17compileModuleImplRN5clang16CompilerInstanceENS_14SourceLocationEPNS_6ModuleEN4llvm9StringRefE;_ZL20compileAndLoadModuleRN5clang16CompilerInstanceENS_14SourceLocationES2_PNS_6ModuleEN4llvm9StringRefE;_ZL16checkConfigMacroRN5clang12PreprocessorEN4llvm9StringRefEPNS_6ModuleENS_14SourceLocationE;_ZL18writeTimestampFileN4llvm9StringRefE;_ZL16pruneModuleCacheRKN5clang19HeaderSearchOptionsE;" -static-type=CompilerInstanceStatics > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/CompilerInstanceStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CompilerInvocation.cpp "-nm=_ZL20getOptimizationLevelRN4llvm3opt7ArgListEN5clang9InputKindERNS3_17DiagnosticsEngineE;_ZL24getOptimizationLevelSizeRN4llvm3opt7ArgListE;_ZL17addDiagnosticArgsRN4llvm3opt7ArgListENS0_12OptSpecifierES3_RSt6vectorISsSaISsEE;_ZL25getAllNoBuiltinFuncValuesRN4llvm3opt7ArgListERSt6vectorISsSaISsEE;_ZL17ParseAnalyzerArgsRN5clang15AnalyzerOptionsERN4llvm3opt7ArgListERNS_17DiagnosticsEngineE;_ZL17ParseMigratorArgsRN5clang15MigratorOptionsERN4llvm3opt7ArgListE;_ZL16ParseCommentArgsRN5clang14CommentOptionsERN4llvm3opt7ArgListE;_ZL12getCodeModelRN4llvm3opt7ArgListERN5clang17DiagnosticsEngineE;_ZL31GenerateOptimizationRemarkRegexRN5clang17DiagnosticsEngineERN4llvm3opt7ArgListEPNS3_3ArgE;_ZL24parseDiagnosticLevelMaskN4llvm9StringRefERKSt6vectorISsSaISsEEPN5clang17DiagnosticsEngineERNS6_19DiagnosticLevelMaskE;_ZL19parseSanitizerKindsN4llvm9StringRefERKSt6vectorISsSaISsEERN5clang17DiagnosticsEngineERNS6_12SanitizerSetE;_ZL16ParseCodeGenArgsRN5clang14CodeGenOptionsERN4llvm3opt7ArgListENS_9InputKindERNS_17DiagnosticsEngineERKNS_13TargetOptionsE;_ZL25ParseDependencyOutputArgsRN5clang23DependencyOutputOptionsERN4llvm3opt7ArgListE;_ZL19ParseFileSystemArgsRN5clang17FileSystemOptionsERN4llvm3opt7ArgListE;_ZL31parseTestModuleFileExtensionArgN4llvm9StringRefERSsRjS2_RbS1_;_ZL17ParseFrontendArgsRN5clang15FrontendOptionsERN4llvm3opt7ArgListERNS_17DiagnosticsEngineE;_ZL21ParseHeaderSearchArgsRN5clang19HeaderSearchOptionsERN4llvm3opt7ArgListE;_ZL15parseVisibilityPN4llvm3opt3ArgERNS0_7ArgListERN5clang17DiagnosticsEngineE;_ZL13ParseLangArgsRN5clang11LangOptionsERN4llvm3opt7ArgListENS_9InputKindERNS_17DiagnosticsEngineE;_ZL21ParsePreprocessorArgsRN5clang19PreprocessorOptionsERN4llvm3opt7ArgListERNS_11FileManagerERNS_17DiagnosticsEngineE;_ZL27ParsePreprocessorOutputArgsRN5clang25PreprocessorOutputOptionsERN4llvm3opt7ArgListENS_8frontend10ActionKindE;_ZL15ParseTargetArgsRN5clang13TargetOptionsERN4llvm3opt7ArgListE;" -static-type=CompilerInvocationStatics > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/CompilerInvocationStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DependencyFile.cpp "-nm=_ZL17isSpecialFilenameN4llvm9StringRefE;_ZL13PrintFilenameRN4llvm11raw_ostreamENS_9StringRefEN5clang22DependencyOutputFormatE;" -static-type=DependencyFileStatics > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/DependencyFileStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DiagnosticRenderer.cpp "-nm=_ZL21getImmediateMacroNameN5clang14SourceLocationERKNS_13SourceManagerERKNS_11LangOptionsE;_ZL11mergeFixitsN4llvm8ArrayRefIN5clang9FixItHintEEERKNS1_13SourceManagerERKNS1_11LangOptionsERNS_15SmallVectorImplIS2_EE;_ZL21retrieveMacroLocationN5clang14SourceLocationENS_6FileIDES1_RKN4llvm15SmallVectorImplIS1_EEbPKNS_13SourceManagerE;_ZL27getMacroArgExpansionFileIDsN5clang14SourceLocationERN4llvm15SmallVectorImplINS_6FileIDEEEbPKNS_13SourceManagerE;_ZL37computeCommonMacroArgExpansionFileIDsN5clang14SourceLocationES0_PKNS_13SourceManagerERN4llvm15SmallVectorImplINS_6FileIDEEE;_ZL19mapDiagnosticRangesN5clang14SourceLocationEN4llvm8ArrayRefINS_15CharSourceRangeEEERNS1_15SmallVectorImplIS3_EEPKNS_13SourceManagerE;_ZL28checkLocForMacroArgExpansionN5clang14SourceLocationERKNS_13SourceManagerES0_;_ZL30checkRangeForMacroArgExpansionN5clang15CharSourceRangeERKNS_13SourceManagerENS_14SourceLocationE;_ZL31checkRangesForMacroArgExpansionN5clang14SourceLocationEN4llvm8ArrayRefINS_15CharSourceRangeEEERKNS_13SourceManagerE;" -static-type=DiagnosticRendererStatics > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/DiagnosticRendererStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp "-nm=_ZpLRN4llvm15SmallVectorImplIcEENS_9StringRefE;_ZL16addHeaderIncludeN4llvm9StringRefERNS_15SmallVectorImplIcEERKN5clang11LangOptionsEb;_ZL27collectModuleHeaderIncludesRKN5clang11LangOptionsERNS_11FileManagerERNS_9ModuleMapEPNS_6ModuleERN4llvm15SmallVectorImplIcEE;" -static-type=FrontendActionsStatics > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/FrontendActionsStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/HeaderIncludeGen.cpp "-nm=_ZL15PrintHeaderInfoPN4llvm11raw_ostreamEPKcbjb;" -static-type=HeaderIncludeGenStatics > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/HeaderIncludeGenStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/InitPreprocessor.cpp "-nm=_ZL24MacroBodyEndsInBackslashN4llvm9StringRefE;_ZL18DefineBuiltinMacroRN5clang12MacroBuilderEN4llvm9StringRefERNS_17DiagnosticsEngineE;_ZL18AddImplicitIncludeRN5clang12MacroBuilderEN4llvm9StringRefE;_ZL24AddImplicitIncludeMacrosRN5clang12MacroBuilderEN4llvm9StringRefE;_ZL21AddImplicitIncludePTHRN5clang12MacroBuilderERNS_12PreprocessorEN4llvm9StringRefE;_ZL21AddImplicitIncludePCHRN5clang12MacroBuilderERNS_12PreprocessorERKNS_18PCHContainerReaderEN4llvm9StringRefE;_ZL6PickFPPKN4llvm12fltSemanticsET_S3_S3_S3_S3_;_ZL17DefineFloatMacrosRN5clang12MacroBuilderEN4llvm9StringRefEPKNS2_12fltSemanticsES3_;_ZL14DefineTypeSizeRKN4llvm5TwineEjNS_9StringRefEbRN5clang12MacroBuilderE;_ZL14DefineTypeSizeRKN4llvm5TwineEN5clang10TargetInfo7IntTypeERKS4_RNS3_12MacroBuilderE;_ZL9DefineFmtRKN4llvm5TwineEN5clang10TargetInfo7IntTypeERKS4_RNS3_12MacroBuilderE;_ZL10DefineTypeRKN4llvm5TwineEN5clang10TargetInfo7IntTypeERNS3_12MacroBuilderE;_ZL15DefineTypeWidthN4llvm9StringRefEN5clang10TargetInfo7IntTypeERKS2_RNS1_12MacroBuilderE;_ZL16DefineTypeSizeofN4llvm9StringRefEjRKN5clang10TargetInfoERNS1_12MacroBuilderE;_ZL23DefineExactWidthIntTypeN5clang10TargetInfo7IntTypeERKS0_RNS_12MacroBuilderE;_ZL27DefineExactWidthIntTypeSizeN5clang10TargetInfo7IntTypeERKS0_RNS_12MacroBuilderE;_ZL23DefineLeastWidthIntTypejbRKN5clang10TargetInfoERNS_12MacroBuilderE;_ZL17DefineFastIntTypejbRKN5clang10TargetInfoERNS_12MacroBuilderE;_ZL16getLockFreeValuejjj;_ZL28AddObjCXXARCLibstdcxxDefinesRKN5clang11LangOptionsERNS_12MacroBuilderE;_ZL34InitializeStandardPredefinedMacrosRKN5clang10TargetInfoERKNS_11LangOptionsERKNS_15FrontendOptionsERNS_12MacroBuilderE;_ZL36InitializeCPlusPlusFeatureTestMacrosRKN5clang11LangOptionsERNS_12MacroBuilderE;_ZL26InitializePredefinedMacrosRKN5clang10TargetInfoERKNS_11LangOptionsERKNS_15FrontendOptionsERNS_12MacroBuilderE;" -static-type=InitPreprocessorStatics > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/InitPreprocessorStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/PrintPreprocessedOutput.cpp "-nm=_ZL20PrintMacroDefinitionRKN5clang14IdentifierInfoERKNS_9MacroInfoERNS_12PreprocessorERN4llvm11raw_ostreamE;_ZL15outputPrintableRN4llvm11raw_ostreamERKSs;_ZL23PrintPreprocessedTokensRN5clang12PreprocessorERNS_5TokenEPN12_GLOBAL__N_124PrintPPOutputPPCallbacksERN4llvm11raw_ostreamE;_ZL14MacroIDComparePKSt4pairIPKN5clang14IdentifierInfoEPNS0_9MacroInfoEES8_;_ZL13DoPrintMacrosRN5clang12PreprocessorEPN4llvm11raw_ostreamE;" -static-type=PrintPreprocessedOutputStatics > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/PrintPreprocessedOutputStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/VerifyDiagnosticConsumer.cpp "-nm=_ZL14ParseDirectiveN4llvm9StringRefEPN5clang24VerifyDiagnosticConsumer12ExpectedDataERNS1_13SourceManagerEPNS1_12PreprocessorENS1_14SourceLocationERNS2_15DirectiveStatusE;_ZL14findDirectivesRN5clang13SourceManagerENS_6FileIDERKNS_11LangOptionsE;_ZL15PrintUnexpectedRN5clang17DiagnosticsEngineEPNS_13SourceManagerEN9__gnu_cxx17__normal_iteratorIPKSt4pairINS_14SourceLocationESsESt6vectorIS8_SaIS8_EEEESE_PKc;_ZL13PrintExpectedRN5clang17DiagnosticsEngineERNS_13SourceManagerERSt6vectorIPNS_24VerifyDiagnosticConsumer9DirectiveESaIS7_EEPKc;_ZL14IsFromSameFileRN5clang13SourceManagerENS_14SourceLocationES2_;_ZL10CheckListsRN5clang17DiagnosticsEngineERNS_13SourceManagerEPKcRSt6vectorISt10unique_ptrINS_24VerifyDiagnosticConsumer9DirectiveESt14default_deleteIS9_EESaISC_EEN9__gnu_cxx17__normal_iteratorIPKSt4pairINS_14SourceLocationESsES6_ISK_SaISK_EEEESP_b;_ZL12CheckResultsRN5clang17DiagnosticsEngineERNS_13SourceManagerERKNS_20TextDiagnosticBufferERNS_24VerifyDiagnosticConsumer12ExpectedDataE;" -static-type=VerifyDiagnosticConsumerStatics > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/VerifyDiagnosticConsumerStatics.java

# Global functions/variables

# Global functions/variables for namespace as packages
${SPUTNIK}/contrib/JConvert/jclank.sh -body-delegate -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTConsumers.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CacheTokens.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ChainedIncludesSource.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CreateInvocationFromCommandLine.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DependencyGraph.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/HeaderIncludeGen.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/InitHeaderSearch.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/InitPreprocessor.cpp ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/PrintPreprocessedOutput.cpp ${LLVM_SRC}/llvm/tools/clang/tools/driver/driver.cpp "-nm=_ZN5clang16CreateASTPrinterEPN4llvm11raw_ostreamENS0_9StringRefE;_ZN5clang15CreateASTDumperEN4llvm9StringRefEbb;_ZN5clang23CreateASTDeclNodeListerEv;_ZN5clang15CreateASTViewerEv;_ZN5clang24CreateDeclContextPrinterEv;_ZN5clang19ParseDiagnosticArgsERNS_17DiagnosticOptionsERN4llvm3opt7ArgListEPNS_17DiagnosticsEngineE;_ZN5clang31createVFSFromCompilerInvocationERKNS_18CompilerInvocationERNS_17DiagnosticsEngineE;_ZN5clang24ApplyHeaderSearchOptionsERNS_12HeaderSearchERKNS_19HeaderSearchOptionsERKNS_11LangOptionsERKN4llvm6TripleE;_ZN5clang22InitializePreprocessorERNS_12PreprocessorERKNS_19PreprocessorOptionsERKNS_18PCHContainerReaderERKNS_15FrontendOptionsE;_ZN5clang24DoPrintPreprocessedInputERNS_12PreprocessorEPN4llvm11raw_ostreamERKNS_25PreprocessorOutputOptionsE;_ZN5clang24AttachDependencyGraphGenERNS_12PreprocessorEN4llvm9StringRefES3_;_ZN5clang22AttachHeaderIncludeGenERNS_12PreprocessorERKSt6vectorISsSaISsEEbN4llvm9StringRefEbb;_ZN5clang11CacheTokensERNS_12PreprocessorEPN4llvm17raw_pwrite_streamE;_ZN5clang27createChainedIncludesSourceERNS_16CompilerInstanceERN4llvm18IntrusiveRefCntPtrINS_18ExternalSemaSourceEEE;_ZN5clang31createInvocationFromCommandLineEN4llvm8ArrayRefIPKcEENS0_18IntrusiveRefCntPtrINS_17DiagnosticsEngineEEE;_ZN5clang18getLastArgIntValueERKN4llvm3opt7ArgListENS1_12OptSpecifierEiPNS_17DiagnosticsEngineE;_ZN5clang18getLastArgIntValueERKN4llvm3opt7ArgListENS1_12OptSpecifierEiRNS_17DiagnosticsEngineE;_ZN5clang21getLastArgUInt64ValueERKN4llvm3opt7ArgListENS1_12OptSpecifierEmPNS_17DiagnosticsEngineE;_ZN5clang21getLastArgUInt64ValueERKN4llvm3opt7ArgListENS1_12OptSpecifierEmRNS_17DiagnosticsEngineE;_ZN5clang11BuryPointerEPKv;_ZN5clang11BuryPointerESt10unique_ptrIT_St14default_deleteIS1_EE;" -static-type=ClangGlobals > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/ClangGlobals.java

# Static functions/variables for namespaces as packages

# Delegated symbols

# Unhandled removed symbols
#[Function,CheckLists,${LLVM_SRC}/llvm/tools/clang/lib/Frontend/VerifyDiagnosticConsumer.cpp:690,_ZL10CheckListsRN5clang17DiagnosticsEngineERNS_13SourceManagerEPKcRSt6vectorISt10unique_ptrINS_24VerifyDiagnosticConsumer9DirectiveESt14default_deleteIS9_EESaISC_EEN9__gnu_cxx17__normal_iteratorIPKSt4pairINS_14SourceLocationESsES6_ISK_SaISK_EEEESP_]
#[Function,parseMSCVersion,${LLVM_SRC}/llvm/tools/clang/lib/Frontend/CompilerInvocation.cpp:1262,_ZL15parseMSCVersionRN4llvm3opt7ArgListERN5clang17DiagnosticsEngineE]
#[CXXRecord,(anonymous namespace)::PCHLocatorInfo,${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp:2779,_ZN12_GLOBAL__N_114PCHLocatorInfoE]
#[Function,AddImplicitIncludePCH,${LLVM_SRC}/llvm/tools/clang/lib/Frontend/InitPreprocessor.cpp:99,_ZL21AddImplicitIncludePCHRN5clang12MacroBuilderERNS_12PreprocessorEN4llvm9StringRefE]
#[Function,clang::CacheTokens,${LLVM_SRC}/llvm/tools/clang/include/clang/Frontend/Utils.h:164,_ZN5clang11CacheTokensERNS_12PreprocessorEPN4llvm14raw_fd_ostreamE]
#[Function,addHeaderInclude,${LLVM_SRC}/llvm/tools/clang/lib/Frontend/FrontendActions.cpp:154,_ZL16addHeaderIncludePKN5clang9FileEntryERN4llvm15SmallVectorImplIcEERKNS_11LangOptionsEb]
#[Function,clang::InitializePreprocessor,${LLVM_SRC}/llvm/tools/clang/include/clang/Frontend/Utils.h:64,_ZN5clang22InitializePreprocessorERNS_12PreprocessorERKNS_19PreprocessorOptionsERKNS_15FrontendOptionsE]
#[Function,clang::AttachHeaderIncludeGen,${LLVM_SRC}/llvm/tools/clang/include/clang/Frontend/Utils.h:158,_ZN5clang22AttachHeaderIncludeGenERNS_12PreprocessorEbN4llvm9StringRefEbb]
#[Function,PCHLocator,${LLVM_SRC}/llvm/tools/clang/lib/Frontend/ASTUnit.cpp:2785,_ZL10PCHLocatorRN5clang13serialization10ModuleFileEPv]
#[Function,PrintFilename,${LLVM_SRC}/llvm/tools/clang/lib/Frontend/DependencyFile.cpp:294,_ZL13PrintFilenameRN4llvm11raw_ostreamENS_9StringRefE]


