# Used directories
mkdir -p ${SPUTNIK}/modules/org.clang.tools.driver/src/org/clang/tools/driver

# Global and static CXXRecords, ClassTemplates, ClassTemplateSpecializations
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.tools.driver/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/tools/driver/cc1as_main.cpp "-nm=_ZN12_GLOBAL__N_119AssemblerInvocationE;" > ${SPUTNIK}/modules/org.clang.tools.driver/src/org/clang/tools/driver/AssemblerInvocation.java

# Global functions/variables
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.tools.driver/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/tools/driver/cc1_main.cpp "-nm=_Z8cc1_mainN4llvm8ArrayRefIPKcEES2_Pv;_ZL16LLVMErrorHandlerPvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb;" -static-type=cc1_mainGlobals -package=org.clang.tools.driver > ${SPUTNIK}/modules/org.clang.tools.driver/src/org/clang/tools/driver/cc1_mainGlobals.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.tools.driver/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/tools/driver/cc1as_main.cpp "-nm=_Z10cc1as_mainN4llvm8ArrayRefIPKcEES2_Pv;_ZL15getOutputStreamRN12_GLOBAL__N_119AssemblerInvocationERN5clang17DiagnosticsEngineEb;_ZL16ExecuteAssemblerRN12_GLOBAL__N_119AssemblerInvocationERN5clang17DiagnosticsEngineE;_ZL16LLVMErrorHandlerPvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb;" -static-type=cc1as_mainGlobals -package=org.clang.tools.driver > ${SPUTNIK}/modules/org.clang.tools.driver/src/org/clang/tools/driver/cc1as_mainGlobals.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.clang.tools.driver/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/tools/driver/driver.cpp "-nm=_Z17GetExecutablePathB5cxx11PKcb;_Z4main;_ZL13GetStableCStrRSt3setINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4lessIS5_ESaIS5_EEN4llvm9StringRefE;_ZL13SetInstallDirRN4llvm15SmallVectorImplIPKcEERN5clang6driver6DriverEb;_ZL14ExecuteCC1ToolN4llvm8ArrayRefIPKcEENS_9StringRefE;_ZL15ApplyQAOverrideRN4llvm15SmallVectorImplIPKcEES2_RSt3setINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4lessISB_ESaISB_EE;_ZL18ApplyOneQAOverrideRN4llvm11raw_ostreamERNS_15SmallVectorImplIPKcEENS_9StringRefERSt3setINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4lessISE_ESaISE_EE;_ZL18getCLEnvVarOptionsRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERN4llvm11StringSaverERNS6_15SmallVectorImplIPKcEE;_ZL22FixupDiagPrefixExeNamePN5clang21TextDiagnosticPrinterERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE;_ZL23insertTargetAndModeArgsN4llvm9StringRefES0_RNS_15SmallVectorImplIPKcEERSt3setINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4lessISC_ESaISC_EE;_ZL25CreateAndPopulateDiagOptsN4llvm8ArrayRefIPKcEE;_ZL35SetBackdoorDriverOutputsFromEnvVarsRN5clang6driver6DriverE;" -static-type=driverGlobals -package=org.clang.tools.driver > ${SPUTNIK}/modules/org.clang.tools.driver/src/org/clang/tools/driver/driverGlobals.java

