FILE_NAME = short$ptr$single
CLASS_SUFFIX=
POINTER_NAME = short$ptr
REFERENCE_NAME = short$ref
TYPE = short
DEFAULT_VALUE = 0
BUILTIN_TYPE_MODIFY_VALUE_SECTION_START=
BUILTIN_TYPE_MODIFY_VALUE_SECTION_END=
ADDITIONAL_MODIFY_VALUE_SECTION_START =
ADDITIONAL_MODIFY_VALUE_SECTION_END =
STRING_VAL=val
SET_IMPL=val = value;
IS_NULL_CHECK = /*this pointer is never null*/false
