FILE_NAME = type$ref$single
CLASS_SUFFIX=<T>
POINTER_NAME = type$ptr<T>
REFERENCE_NAME = type$ref<T>
TYPE = T
DEFAULT_VALUE = null
BUILTIN_TYPE_MODIFY_VALUE_SECTION_START=/*
BUILTIN_TYPE_MODIFY_VALUE_SECTION_END=*/
ADDITIONAL_MODIFY_VALUE_SECTION_START = /*
ADDITIONAL_MODIFY_VALUE_SECTION_END = */
STRING_VAL=val
SET_IMPL=val = value;
IS_NULL_CHECK = val == null
