FILE_NAME = ushort$ptr$single
CLASS_SUFFIX=
POINTER_NAME = ushort$ptr
REFERENCE_NAME = ushort$ref
TYPE = char
DEFAULT_VALUE = 0
BUILTIN_TYPE_MODIFY_VALUE_SECTION_START=
BUILTIN_TYPE_MODIFY_VALUE_SECTION_END=
ADDITIONAL_MODIFY_VALUE_SECTION_START =
ADDITIONAL_MODIFY_VALUE_SECTION_END =
STRING_VAL=val
SET_IMPL=val = value;
IS_NULL_CHECK = /*this pointer is never null*/false
