FILE_NAME = type$ref
CLASS_SUFFIX = <T>
TYPE = T
POINTER = type$ptr<T>
BUILTIN_TYPE_MODIFY_VALUE_SECTION_START=/*
BUILTIN_TYPE_MODIFY_VALUE_SECTION_END=*/
ADDITIONAL_MODIFY_VALUE_SECTION_START = /*
ADDITIONAL_MODIFY_VALUE_SECTION_END = */
