FILE_NAME = bool$ref
CLASS_SUFFIX =
TYPE = boolean
POINTER = bool$ptr
BUILTIN_TYPE_MODIFY_VALUE_SECTION_START=
BUILTIN_TYPE_MODIFY_VALUE_SECTION_END=
ADDITIONAL_MODIFY_VALUE_SECTION_START = /*
ADDITIONAL_MODIFY_VALUE_SECTION_END = */
