# Used directories
mkdir -p ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt
mkdir -p ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/impl
mkdir -p ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/trans/impl
mkdir -p ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl
mkdir -p ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/llvm/impl
mkdir -p ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl

# Global and static Enums

# Global and static CXXRecords, ClassTemplates, ClassTemplateSpecializations
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMTActions.cpp "-nm=_ZN5clang5arcmt11CheckActionE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/CheckAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/FileRemapper.cpp "-nm=_ZN5clang5arcmt12FileRemapperE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/FileRemapper.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMTActions.cpp "-nm=_ZN5clang5arcmt13MigrateActionE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/MigrateAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMTActions.cpp ${LLVM_SRC}/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ObjCMT.cpp "-nm=_ZN5clang5arcmt19MigrateSourceActionE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/MigrateSourceAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMT.cpp "-nm=_ZN5clang5arcmt16MigrationProcessE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/MigrationProcess.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMTActions.cpp "-nm=_ZN5clang5arcmt12ModifyActionE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/ModifyAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMTActions.cpp ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ObjCMT.cpp "-nm=_ZN5clang5arcmt17ObjCMigrateActionE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/ObjCMigrateAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMT.cpp "-nm=_ZN5clang5arcmt16CapturedDiagListE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/impl/CapturedDiagList.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMT.cpp ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/Transforms.cpp "-nm=_ZN5clang5arcmt13MigrationPassE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/impl/MigrationPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMT.cpp "-nm=_ZN5clang5arcmt11TransactionE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/impl/Transaction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMT.cpp ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransformActions.cpp "-nm=_ZN5clang5arcmt16TransformActionsE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/impl/TransformActions.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/Transforms.cpp "-nm=_ZN5clang5arcmt5trans12ASTTraverserE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/trans/impl/ASTTraverser.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransBlockObjCVariable.cpp ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/Transforms.cpp "-nm=_ZN5clang5arcmt5trans26BlockObjCVariableTraverserE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/trans/impl/BlockObjCVariableTraverser.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/Transforms.cpp "-nm=_ZN5clang5arcmt5trans11BodyContextE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/trans/impl/BodyContext.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/Transforms.cpp "-nm=_ZN5clang5arcmt5trans13BodyTransformE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/trans/impl/BodyTransform.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransGCAttrs.cpp ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/Transforms.cpp "-nm=_ZN5clang5arcmt5trans16GCAttrsTraverserE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/trans/impl/GCAttrsTraverser.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransGCCalls.cpp ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/Transforms.cpp "-nm=_ZN5clang5arcmt5trans27GCCollectableCallsTraverserE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/trans/impl/GCCollectableCallsTraverser.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransGCAttrs.cpp ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/Transforms.cpp "-nm=_ZN5clang5arcmt5trans16MigrationContextE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/trans/impl/MigrationContext.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/Transforms.cpp "-nm=_ZN5clang5arcmt5trans25ObjCImplementationContextE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/trans/impl/ObjCImplementationContext.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransProperties.cpp ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/Transforms.cpp "-nm=_ZN5clang5arcmt5trans24PropertyRewriteTraverserE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/trans/impl/PropertyRewriteTraverser.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransProtectedScope.cpp ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/Transforms.cpp "-nm=_ZN5clang5arcmt5trans23ProtectedScopeTraverserE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/trans/impl/ProtectedScopeTraverser.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransAPIUses.cpp "-nm=_ZN12_GLOBAL__N_110APICheckerE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/APIChecker.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransARCAssign.cpp "-nm=_ZN12_GLOBAL__N_116ARCAssignCheckerE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/ARCAssignChecker.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMT.cpp "-nm=_ZN12_GLOBAL__N_123ARCMTMacroTrackerActionE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/ARCMTMacroTrackerAction.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMT.cpp "-nm=_ZN12_GLOBAL__N_128ARCMTMacroTrackerPPCallbacksE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/ARCMTMacroTrackerPPCallbacks.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/Transforms.cpp "-nm=_ZN12_GLOBAL__N_112ASTTransformE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/ASTTransform.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransAutoreleasePool.cpp "-nm=_ZN12_GLOBAL__N_123AutoreleasePoolRewriterE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/AutoreleasePoolRewriter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransBlockObjCVariable.cpp "-nm=_ZN12_GLOBAL__N_120BlockObjCVarRewriterE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/BlockObjCVarRewriter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ObjCMT.cpp "-nm=_ZN12_GLOBAL__N_112BodyMigratorE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/BodyMigrator.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMT.cpp "-nm=_ZN12_GLOBAL__N_125CaptureDiagnosticConsumerE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/CaptureDiagnosticConsumer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransProtectedScope.cpp "-nm=_ZN12_GLOBAL__N_113CaseCollectorE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/CaseCollector.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransProtectedScope.cpp "-nm=_ZN12_GLOBAL__N_18CaseInfoE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/CaseInfo.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ObjCMT.cpp "-nm=_ZN12_GLOBAL__N_19EditEntryE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/EditEntry.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransEmptyStatementsAndDealloc.cpp "-nm=_ZN12_GLOBAL__N_112EmptyCheckerE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/EmptyChecker.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransEmptyStatementsAndDealloc.cpp "-nm=_ZN12_GLOBAL__N_122EmptyStatementsRemoverE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/EmptyStatementsRemover.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransGCAttrs.cpp "-nm=_ZN12_GLOBAL__N_116GCAttrsCollectorE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/GCAttrsCollector.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransGCCalls.cpp "-nm=_ZN12_GLOBAL__N_125GCCollectableCallsCheckerE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/GCCollectableCallsChecker.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ObjCMT.cpp "-nm=_ZN12_GLOBAL__N_114JSONEditWriterE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/JSONEditWriter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransProtectedScope.cpp "-nm=_ZN12_GLOBAL__N_118LocalRefsCollectorE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/LocalRefsCollector.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ObjCMT.cpp "-nm=_ZN12_GLOBAL__N_122ObjCMigrateASTConsumerE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/ObjCMigrateASTConsumer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ObjCMT.cpp "-nm=_ZN12_GLOBAL__N_112ObjCMigratorE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/ObjCMigrator.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransProperties.cpp "-nm=_ZN12_GLOBAL__N_118PropertiesRewriterE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/PropertiesRewriter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransProtectedScope.cpp "-nm=_ZN12_GLOBAL__N_119ProtectedScopeFixerE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/ProtectedScopeFixer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/Transforms.cpp "-nm=_ZN12_GLOBAL__N_114ReferenceClearE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/ReferenceClear.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/Transforms.cpp "-nm=_ZN12_GLOBAL__N_118ReferenceCollectorE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/ReferenceCollector.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransAutoreleasePool.cpp "-nm=_ZN12_GLOBAL__N_116ReleaseCollectorE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/ReleaseCollector.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ObjCMT.cpp "-nm=_ZN12_GLOBAL__N_115RemapFileParserE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/RemapFileParser.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/Transforms.cpp "-nm=_ZN12_GLOBAL__N_119RemovablesCollectorE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/RemovablesCollector.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransRetainReleaseDealloc.cpp "-nm=_ZN12_GLOBAL__N_127RetainReleaseDeallocRemoverE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/RetainReleaseDeallocRemover.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMT.cpp "-nm=_ZN12_GLOBAL__N_118RewritesApplicatorE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/RewritesApplicator.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ObjCMT.cpp "-nm=_ZN12_GLOBAL__N_116RewritesReceiverE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/RewritesReceiver.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransBlockObjCVariable.cpp "-nm=_ZN12_GLOBAL__N_124RootBlockObjCVarRewriterE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/RootBlockObjCVarRewriter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ObjCMT.cpp "-nm=_ZN12_GLOBAL__N_116SuperInitCheckerE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/SuperInitChecker.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransformActions.cpp "-nm=_ZN12_GLOBAL__N_120TransformActionsImplE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/TransformActionsImpl.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransUnbridgedCasts.cpp "-nm=_ZN12_GLOBAL__N_121UnbridgedCastRewriterE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/UnbridgedCastRewriter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransUnusedInitDelegate.cpp "-nm=_ZN12_GLOBAL__N_118UnusedInitRewriterE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/UnusedInitRewriter.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransZeroOutPropsInDealloc.cpp "-nm=_ZN12_GLOBAL__N_123ZeroOutInDeallocRemoverE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/ZeroOutInDeallocRemover.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ObjCMT.cpp "-nm=_ZN4llvm12DenseMapInfoIN12_GLOBAL__N_19EditEntryEEE;" > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/llvm/impl/DenseMapInfoEditEntry.java

# Global and static namespaces

# Static functions/variables
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMT.cpp "-nm=_ZL13HasARCRuntimeRN5clang18CompilerInvocationE;_ZL28createInvocationForMigrationRN5clang18CompilerInvocationE;_ZL22emitPremigrationErrorsRKN5clang5arcmt16CapturedDiagListEPNS_17DiagnosticOptionsERNS_12PreprocessorE;_ZL15applyTransformsRN5clang18CompilerInvocationERKNS_17FrontendInputFileEPNS_18DiagnosticConsumerEN4llvm9StringRefEbS8_;" -static-type=ARCMTStatics -package=org.clang.arcmigrate.impl > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/ARCMTStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ObjCMT.cpp "-nm=_ZN12_GLOBAL__N_128subscriptOperatorNeedsParensEPKN5clang4ExprE;_ZN12_GLOBAL__N_126rewriteToPropertyDotSyntaxEPKN5clang15ObjCMessageExprERNS0_12PreprocessorERKNS0_5NSAPIERNS0_4edit6CommitEPKNS0_9ParentMapE;_ZL11append_attrRSsPKcRb;_ZL41MigrateBlockOrFunctionPointerTypeVariableRSsRKSsPKc;_ZL23PropertyMemoryAttributeRN5clang10ASTContextENS_8QualTypeE;_ZL21rewriteToObjCPropertyPKN5clang14ObjCMethodDeclES2_RKNS_5NSAPIERNS_4edit6CommitEjbbb;_ZL34IsCategoryNameWithDeprecatedSuffixPN5clang17ObjCContainerDeclE;_ZL38ClassImplementsAllMethodsAndPropertiesRN5clang10ASTContextEPKNS_22ObjCImplementationDeclEPKNS_17ObjCInterfaceDeclEPNS_16ObjCProtocolDeclE;_ZL26rewriteToObjCInterfaceDeclPKN5clang17ObjCInterfaceDeclERN4llvm15SmallVectorImplIPNS_16ObjCProtocolDeclEEERKNS_5NSAPIERNS_4edit6CommitE;_ZL15GetUnsignedNameN4llvm9StringRefE;_ZL19rewriteToNSEnumDeclPKN5clang8EnumDeclEPKNS_11TypedefDeclERKNS_5NSAPIERNS_4edit6CommitEN4llvm9StringRefEb;_ZL20rewriteToNSMacroDeclRN5clang10ASTContextEPKNS_8EnumDeclEPKNS_11TypedefDeclERKNS_5NSAPIERNS_4edit6CommitEb;_ZL17UseNSOptionsMacroRN5clang12PreprocessorERNS_10ASTContextEPKNS_8EnumDeclE;_ZL23ReplaceWithInstancetypeRN5clang10ASTContextERKN12_GLOBAL__N_122ObjCMigrateASTConsumerEPNS_14ObjCMethodDeclE;_ZL20ReplaceWithClasstypeRKN12_GLOBAL__N_122ObjCMigrateASTConsumerEPN5clang14ObjCMethodDeclE;_ZL18TypeIsInnerPointerN5clang8QualTypeE;_ZL13versionsMatchRKN5clang12VersionTupleES2_;_ZL22AvailabilityAttrsMatchPN5clang4AttrES1_;_ZL22MatchTwoAttributeListsRKN4llvm11SmallVectorIPN5clang4AttrELj2EEES6_Rb;_ZL15AttributesMatchPKN5clang4DeclES2_Rb;_ZL17IsValidIdentifierRN5clang10ASTContextEPKc;_ZL14IsVoidStarTypeN5clang8QualTypeE;_ZL11AuditedTypeN5clang8QualTypeE;_ZL16hasSuperInitCallPKN5clang14ObjCMethodDeclE;_ZL21getWhiteListFilenamesN4llvm9StringRefE;_ZL10reportDiagRKN4llvm5TwineERN5clang17DiagnosticsEngineE;_ZL16applyEditsToTempPKN5clang9FileEntryEN4llvm8ArrayRefIN12_GLOBAL__N_19EditEntryEEERNS_11FileManagerERNS_17DiagnosticsEngineE;" -static-type=ObjCMTStatics -package=org.clang.arcmigrate.impl > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/ObjCMTStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/PlistReporter.cpp "-nm=_ZL12getLevelNameN5clang17DiagnosticsEngine5LevelE;" -static-type=PlistReporterStatics -package=org.clang.arcmigrate.impl > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/PlistReporterStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransEmptyStatementsAndDealloc.cpp "-nm=_ZL26isEmptyARCMTMacroStatementPN5clang8NullStmtERSt6vectorINS_14SourceLocationESaIS3_EERNS_10ASTContextE;_ZL11isBodyEmptyPN5clang12CompoundStmtERNS_10ASTContextERSt6vectorINS_14SourceLocationESaIS5_EE;_ZL24cleanupDeallocOrFinalizeRN5clang5arcmt13MigrationPassE;" -static-type=TransEmptyStatementsAndDeallocStatics -package=org.clang.arcmigrate.impl > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/TransEmptyStatementsAndDeallocStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransGCAttrs.cpp "-nm=_ZL24errorForGCAttrsOnNonObjCRN5clang5arcmt5trans16MigrationContextE;_ZL16checkWeakGCAttrsRN5clang5arcmt5trans16MigrationContextE;_ZL15checkAllAtPropsRN5clang5arcmt5trans16MigrationContextENS_14SourceLocationERN4llvm13TinyPtrVectorIPNS_16ObjCPropertyDeclEEE;_ZL13checkAllPropsRN5clang5arcmt5trans16MigrationContextERSt6vectorIPNS_16ObjCPropertyDeclESaIS6_EE;" -static-type=TransGCAttrsStatics -package=org.clang.arcmigrate.impl > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/TransGCAttrsStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/Transforms.cpp "-nm=_ZL17GCRewriteFinalizeRN5clang5arcmt13MigrationPassE;_ZL11traverseASTRN5clang5arcmt13MigrationPassE;_ZL21independentTransformsRN5clang5arcmt13MigrationPassE;" -static-type=TransformsStatics -package=org.clang.arcmigrate.impl > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/impl/TransformsStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.frontend/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/Frontend/LogDiagnosticPrinter.cpp "-nm=_ZL12getLevelNameN5clang17DiagnosticsEngine5LevelE;" -static-type=LogDiagnosticPrinterStatics -package=org.clang.frontend.impl > ${SPUTNIK}/modules/org.clang.frontend/src/org/clang/frontend/impl/LogDiagnosticPrinterStatics.java

# Global functions/variables

# Global functions/variables for namespace as packages
${SPUTNIK}/contrib/JConvert/jclank.sh -body-delegate -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMT.cpp ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ObjCMT.cpp ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/Transforms.cpp "-nm=_ZN5clang5arcmt20checkForManualIssuesERNS_18CompilerInvocationERKNS_17FrontendInputFileEPNS_18DiagnosticConsumerEbN4llvm9StringRefE;_ZN5clang5arcmt20applyTransformationsERNS_18CompilerInvocationERKNS_17FrontendInputFileEPNS_18DiagnosticConsumerE;_ZN5clang5arcmt25migrateWithTemporaryFilesERNS_18CompilerInvocationERKNS_17FrontendInputFileEPNS_18DiagnosticConsumerEN4llvm9StringRefEbS9_;_ZN5clang5arcmt17getFileRemappingsERSt6vectorISt4pairISsSsESaIS3_EEN4llvm9StringRefEPNS_18DiagnosticConsumerE;_ZN5clang5arcmt29getFileRemappingsFromFileListERSt6vectorISt4pairISsSsESaIS3_EEN4llvm8ArrayRefINS7_9StringRefEEEPNS_18DiagnosticConsumerE;_ZN5clang5arcmt21getAllTransformationsENS_11LangOptions6GCModeEb;" -static-type=ArcmtGlobals -package=org.clang.arcmigrate.arcmt > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/ArcmtGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMT.cpp "-nm=_ZN5clang5arcmt20checkForManualIssuesERNS_18CompilerInvocationERKNS_17FrontendInputFileEPNS_18DiagnosticConsumerEbN4llvm9StringRefE;_ZN5clang5arcmt20applyTransformationsERNS_18CompilerInvocationERKNS_17FrontendInputFileEPNS_18DiagnosticConsumerE;_ZN5clang5arcmt25migrateWithTemporaryFilesERNS_18CompilerInvocationERKNS_17FrontendInputFileEPNS_18DiagnosticConsumerEN4llvm9StringRefEbS9_;_ZN5clang5arcmt17getFileRemappingsERSt6vectorISt4pairISsSsESaIS3_EEN4llvm9StringRefEPNS_18DiagnosticConsumerE;" -static-type=ARCMTArcmtGlobals -package=org.clang.arcmigrate.arcmt.impl > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/impl/ARCMTArcmtGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/Transforms.cpp "-nm=_ZN5clang5arcmt21getAllTransformationsENS_11LangOptions6GCModeEb;" -static-type=TransformsArcmtGlobals -package=org.clang.arcmigrate.arcmt.impl > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/impl/TransformsArcmtGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ObjCMT.cpp "-nm=_ZN5clang5arcmt29getFileRemappingsFromFileListERSt6vectorISt4pairISsSsESaIS3_EEN4llvm8ArrayRefINS7_9StringRefEEEPNS_18DiagnosticConsumerE;" -static-type=ObjCMTArcmtGlobals -package=org.clang.arcmigrate.arcmt.impl > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/impl/ObjCMTArcmtGlobals.java

# Static functions/variables for namespaces as packages
${SPUTNIK}/contrib/JConvert/jclank.sh -body-delegate -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMT.cpp ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/PlistReporter.cpp "-nm=_ZN5clang5arcmt20writeARCDiagsToPlistERKSsN4llvm8ArrayRefINS_16StoredDiagnosticEEERNS_13SourceManagerERKNS_11LangOptionsE;_ZN5clang5arcmtL17getARCMTMacroNameEv;" -static-type=ArcmtStatics -package=org.clang.arcmigrate.arcmt.impl > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/impl/ArcmtStatics.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/ARCMT.cpp "-nm=_ZN5clang5arcmtL17getARCMTMacroNameEv;" -static-type=InternalsArcmtStatics -package=org.clang.arcmigrate.arcmt.impl > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/impl/InternalsArcmtStatics.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/PlistReporter.cpp "-nm=_ZN5clang5arcmt20writeARCDiagsToPlistERKSsN4llvm8ArrayRefINS_16StoredDiagnosticEEERNS_13SourceManagerERKNS_11LangOptionsE;" -static-type=PlistReporterArcmtStatics -package=org.clang.arcmigrate.arcmt.impl > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/impl/PlistReporterArcmtStatics.java
${SPUTNIK}/contrib/JConvert/jclank.sh -body-delegate -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransAPIUses.cpp ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransARCAssign.cpp ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransAutoreleasePool.cpp ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransEmptyStatementsAndDealloc.cpp ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransRetainReleaseDealloc.cpp ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransUnbridgedCasts.cpp ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransUnusedInitDelegate.cpp ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransZeroOutPropsInDealloc.cpp ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/Transforms.cpp "-nm=_ZN5clang5arcmt5trans22rewriteAutoreleasePoolERNS0_13MigrationPassE;_ZN5clang5arcmt5trans21rewriteUnbridgedCastsERNS0_13MigrationPassE;_ZN5clang5arcmt5trans17makeAssignARCSafeERNS0_13MigrationPassE;_ZN5clang5arcmt5trans34removeRetainReleaseDeallocFinalizeERNS0_13MigrationPassE;_ZN5clang5arcmt5trans35removeZeroOutPropsInDeallocFinalizeERNS0_13MigrationPassE;_ZN5clang5arcmt5trans25rewriteUnusedInitDelegateERNS0_13MigrationPassE;_ZN5clang5arcmt5trans12checkAPIUsesERNS0_13MigrationPassE;_ZN5clang5arcmt5trans39removeEmptyStatementsAndDeallocFinalizeERNS0_13MigrationPassE;_ZN5clang5arcmt5trans12canApplyWeakERNS_10ASTContextENS_8QualTypeEb;_ZN5clang5arcmt5trans15isPlusOneAssignEPKNS_14BinaryOperatorE;_ZN5clang5arcmt5trans9isPlusOneEPKNS_4ExprE;_ZN5clang5arcmt5trans21findLocationAfterSemiENS_14SourceLocationERNS_10ASTContextEb;_ZN5clang5arcmt5trans21findSemiAfterLocationENS_14SourceLocationERNS_10ASTContextEb;_ZN5clang5arcmt5trans14hasSideEffectsEPNS_4ExprERNS_10ASTContextE;_ZN5clang5arcmt5trans11isGlobalVarEPNS_4ExprE;_ZN5clang5arcmt5trans12getNilStringERNS_10ASTContextE;_ZN5clang5arcmt5trans11clearRefsInEPNS_4StmtERN4llvm8DenseSetIPNS_4ExprENS4_12DenseMapInfoIS7_EEEE;_ZN5clang5arcmt5trans11clearRefsInET_S2_RN4llvm8DenseSetIPNS_4ExprENS3_12DenseMapInfoIS6_EEEE;_ZN5clang5arcmt5trans11collectRefsEPNS_9ValueDeclEPNS_4StmtERN4llvm8DenseSetIPNS_4ExprENS6_12DenseMapInfoIS9_EEEE;_ZN5clang5arcmt5trans17collectRemovablesEPNS_4StmtERN4llvm8DenseSetIPNS_4ExprENS4_12DenseMapInfoIS7_EEEE;" -static-type=TransStatics -package=org.clang.arcmigrate.arcmt.trans.impl > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/trans/impl/TransStatics.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransUnusedInitDelegate.cpp "-nm=_ZN5clang5arcmt5trans25rewriteUnusedInitDelegateERNS0_13MigrationPassE;" -static-type=TransUnusedInitDelegateTransStatics -package=org.clang.arcmigrate.arcmt.trans.impl > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/trans/impl/TransUnusedInitDelegateTransStatics.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransUnbridgedCasts.cpp "-nm=_ZN5clang5arcmt5trans21rewriteUnbridgedCastsERNS0_13MigrationPassE;" -static-type=TransUnbridgedCastsTransStatics -package=org.clang.arcmigrate.arcmt.trans.impl > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/trans/impl/TransUnbridgedCastsTransStatics.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransARCAssign.cpp "-nm=_ZN5clang5arcmt5trans17makeAssignARCSafeERNS0_13MigrationPassE;" -static-type=TransARCAssignTransStatics -package=org.clang.arcmigrate.arcmt.trans.impl > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/trans/impl/TransARCAssignTransStatics.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/Transforms.cpp "-nm=_ZN5clang5arcmt5trans12canApplyWeakERNS_10ASTContextENS_8QualTypeEb;_ZN5clang5arcmt5trans15isPlusOneAssignEPKNS_14BinaryOperatorE;_ZN5clang5arcmt5trans9isPlusOneEPKNS_4ExprE;_ZN5clang5arcmt5trans21findLocationAfterSemiENS_14SourceLocationERNS_10ASTContextEb;_ZN5clang5arcmt5trans21findSemiAfterLocationENS_14SourceLocationERNS_10ASTContextEb;_ZN5clang5arcmt5trans14hasSideEffectsEPNS_4ExprERNS_10ASTContextE;_ZN5clang5arcmt5trans11isGlobalVarEPNS_4ExprE;_ZN5clang5arcmt5trans12getNilStringERNS_10ASTContextE;_ZN5clang5arcmt5trans11clearRefsInEPNS_4StmtERN4llvm8DenseSetIPNS_4ExprENS4_12DenseMapInfoIS7_EEEE;_ZN5clang5arcmt5trans11clearRefsInET_S2_RN4llvm8DenseSetIPNS_4ExprENS3_12DenseMapInfoIS6_EEEE;_ZN5clang5arcmt5trans11collectRefsEPNS_9ValueDeclEPNS_4StmtERN4llvm8DenseSetIPNS_4ExprENS6_12DenseMapInfoIS9_EEEE;_ZN5clang5arcmt5trans17collectRemovablesEPNS_4StmtERN4llvm8DenseSetIPNS_4ExprENS4_12DenseMapInfoIS7_EEEE;" -static-type=TransformsTransStatics -package=org.clang.arcmigrate.arcmt.trans.impl > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/trans/impl/TransformsTransStatics.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransZeroOutPropsInDealloc.cpp "-nm=_ZN5clang5arcmt5trans35removeZeroOutPropsInDeallocFinalizeERNS0_13MigrationPassE;" -static-type=TransZeroOutPropsInDeallocTransStatics -package=org.clang.arcmigrate.arcmt.trans.impl > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/trans/impl/TransZeroOutPropsInDeallocTransStatics.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransAPIUses.cpp "-nm=_ZN5clang5arcmt5trans12checkAPIUsesERNS0_13MigrationPassE;" -static-type=TransAPIUsesTransStatics -package=org.clang.arcmigrate.arcmt.trans.impl > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/trans/impl/TransAPIUsesTransStatics.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransEmptyStatementsAndDealloc.cpp "-nm=_ZN5clang5arcmt5trans39removeEmptyStatementsAndDeallocFinalizeERNS0_13MigrationPassE;" -static-type=TransEmptyStatementsAndDeallocTransStatics -package=org.clang.arcmigrate.arcmt.trans.impl > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/trans/impl/TransEmptyStatementsAndDeallocTransStatics.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransAutoreleasePool.cpp "-nm=_ZN5clang5arcmt5trans22rewriteAutoreleasePoolERNS0_13MigrationPassE;" -static-type=TransAutoreleasePoolTransStatics -package=org.clang.arcmigrate.arcmt.trans.impl > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/trans/impl/TransAutoreleasePoolTransStatics.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.clang.arcmigrate/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/ARCMigrate/TransRetainReleaseDealloc.cpp "-nm=_ZN5clang5arcmt5trans34removeRetainReleaseDeallocFinalizeERNS0_13MigrationPassE;" -static-type=TransRetainReleaseDeallocTransStatics -package=org.clang.arcmigrate.arcmt.trans.impl > ${SPUTNIK}/modules/org.clang.arcmigrate/src/org/clang/arcmigrate/arcmt/trans/impl/TransRetainReleaseDeallocTransStatics.java

