# Used directories
mkdir -p ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms
mkdir -p ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/impl
mkdir -p ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/instcombine
mkdir -p ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo
mkdir -p ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/impl
mkdir -p ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/lowertypetests
mkdir -p ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/wholeprogramdevirt
mkdir -p ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar
mkdir -p ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/consthoist
mkdir -p ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/jumpthreading
mkdir -p ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/reassociate
mkdir -p ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils
mkdir -p ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/SymbolRewriter
mkdir -p ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/impl
mkdir -p ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/vectorize

# Global and static Enums
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm13jumpthreading18ConstantPreferenceE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/jumpthreading/ConstantPreference.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Linker/IRMover.cpp "-nm=_ZN4llvm10RemapFlagsE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/RemapFlags.java
${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/CodeGen/SanitizerMetadata.cpp "-nm=_ZN4llvm17SanitizerStatKindE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/SanitizerStatKind.java

# Global and static CXXRecords, ClassTemplates, ClassTemplateSpecializations
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/CodeGen/BackendUtil.cpp "-nm=_ZN4llvm26EfficiencySanitizerOptionsE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/EfficiencySanitizerOptions.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/CodeGen/BackendUtil.cpp ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm11GCOVOptionsE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/GCOVOptions.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm16GCOVProfilerPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/GCOVProfilerPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm16InstrProfOptionsE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/InstrProfOptions.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm14InstrProfilingE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/InstrProfiling.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm24PGOIndirectCallPromotionE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/PGOIndirectCallPromotion.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm21PGOInstrumentationGenE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/PGOInstrumentationGen.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm21PGOInstrumentationUseE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/PGOInstrumentationUse.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm23SampleProfileLoaderPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/SampleProfileLoaderPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/CodeGen/BackendUtil.cpp "-nm=_ZN4llvm24SanitizerCoverageOptionsE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/SanitizerCoverageOptions.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/tools/driver/cc1_main.cpp "-nm=_ZN4llvm15VectorizeConfigE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/VectorizeConfig.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm15InstCombinePassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/instcombine/InstCombinePass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm19InstCombineWorklistE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/instcombine/InstCombineWorklist.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm24InstructionCombiningPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/instcombine/InstructionCombiningPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm17ConstantMergePassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/ConstantMergePass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm15CrossDSOCFIPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/CrossDSOCFIPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm27DeadArgumentEliminationPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/DeadArgumentEliminationPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm32EliminateAvailableExternallyPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/EliminateAvailableExternallyPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm22ForceFunctionAttrsPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/ForceFunctionAttrsPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm13GlobalDCEPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/GlobalDCEPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm13GlobalOptPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/GlobalOptPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm10IPSCCPPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/IPSCCPPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm22InferFunctionAttrsPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/InferFunctionAttrsPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm15InternalizePassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/InternalizePass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm18LowerTypeTestsPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/LowerTypeTestsPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm18PartialInlinerPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/PartialInlinerPass.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/CodeGen/BackendUtil.cpp "-nm=_ZN4llvm18PassManagerBuilderE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/PassManagerBuilder.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm26PostOrderFunctionAttrsPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/PostOrderFunctionAttrsPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/CodeGen/BackendUtil.cpp "-nm=_ZN4llvm22RegisterStandardPassesE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/RegisterStandardPasses.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm33ReversePostOrderFunctionAttrsPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/ReversePostOrderFunctionAttrsPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm23StripDeadPrototypesPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/StripDeadPrototypesPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm22WholeProgramDevirtPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/WholeProgramDevirtPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm14lowertypetests13BitSetBuilderE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/lowertypetests/BitSetBuilder.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm14lowertypetests10BitSetInfoE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/lowertypetests/BitSetInfo.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm14lowertypetests16ByteArrayBuilderE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/lowertypetests/ByteArrayBuilder.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm14lowertypetests19GlobalLayoutBuilderE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/lowertypetests/GlobalLayoutBuilder.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm18wholeprogramdevirt14AccumBitVectorE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/wholeprogramdevirt/AccumBitVector.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm18wholeprogramdevirt14TypeMemberInfoE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/wholeprogramdevirt/TypeMemberInfo.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm18wholeprogramdevirt10VTableBitsE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/wholeprogramdevirt/VTableBits.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm18wholeprogramdevirt17VirtualCallTargetE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/wholeprogramdevirt/VirtualCallTarget.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm8ADCEPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/ADCEPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm28AlignmentFromAssumptionsPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/AlignmentFromAssumptionsPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm8BDCEPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/BDCEPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm20ConstantHoistingPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/ConstantHoistingPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm30CorrelatedValuePropagationPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/CorrelatedValuePropagationPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm7DCEPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/DCEPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm7DSEPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/DSEPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm12EarlyCSEPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/EarlyCSEPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm13Float2IntPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/Float2IntPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp ${LLVM_SRC}/llvm/tools/clang/tools/driver/cc1_main.cpp "-nm=_ZN4llvm3GVNE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/GVN.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm12GVNHoistPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/GVNHoistPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm17GuardWideningPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/GuardWideningPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm18IndVarSimplifyPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/IndVarSimplifyPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm17JumpThreadingPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/JumpThreadingPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm8LICMPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/LICMPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm16LoopDeletionPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/LoopDeletionPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm18LoopDistributePassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/LoopDistributePass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm22LoopIdiomRecognizePassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/LoopIdiomRecognizePass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm20LoopInstSimplifyPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/LoopInstSimplifyPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm14LoopRotatePassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/LoopRotatePass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm19LoopSimplifyCFGPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/LoopSimplifyCFGPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm15LowerAtomicPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/LowerAtomicPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm24LowerExpectIntrinsicPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/LowerExpectIntrinsicPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm13MemCpyOptPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/MemCpyOptPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm25MergedLoadStoreMotionPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/MergedLoadStoreMotionPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm27PartiallyInlineLibCallsPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/PartiallyInlineLibCallsPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm15ReassociatePassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/ReassociatePass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm8SCCPPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/SCCPPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm4SROAE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/SROA.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm15SimplifyCFGPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/SimplifyCFGPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm11SinkingPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/SinkingPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm16TailCallElimPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/TailCallElimPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm10consthoist17ConstantCandidateE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/consthoist/ConstantCandidate.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm10consthoist12ConstantInfoE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/consthoist/ConstantInfo.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm10consthoist12ConstantUserE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/consthoist/ConstantUser.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm10consthoist19RebasedConstantInfoE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/consthoist/RebasedConstantInfo.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm11reassociate6FactorE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/reassociate/Factor.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm11reassociate10ValueEntryE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/reassociate/ValueEntry.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm21AddDiscriminatorsPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/AddDiscriminatorsPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Linker/IRMover.cpp "-nm=_ZN4llvm14ClonedCodeInfoE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/ClonedCodeInfo.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm24DoNothingMemorySSAWalkerE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/DoNothingMemorySSAWalker.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Linker/LinkModules.cpp "-nm=_ZN4llvm30FunctionImportGlobalProcessingE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/FunctionImportGlobalProcessing.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm11GraphTraitsINS_7InverseIPNS_12MemoryAccessEEEEE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/GraphTraitsInverse\$MemoryAccess\$P.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm11GraphTraitsIPNS_12MemoryAccessEEE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/GraphTraitsMemoryAccess\$P.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Linker/IRMover.cpp "-nm=_ZN4llvm18InlineFunctionInfoE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/InlineFunctionInfo.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm18InstSimplifierPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/InstSimplifierPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm9LCSSAPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/LCSSAPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm16LoopSimplifyPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/LoopSimplifyPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm12MemoryAccessE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/MemoryAccess.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm9MemoryDefE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/MemoryDef.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm9MemoryPhiE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/MemoryPhi.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm9MemorySSAE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/MemorySSA.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm17MemorySSAAnalysisE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/MemorySSAAnalysis.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm26MemorySSAPrinterLegacyPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/MemorySSAPrinterLegacyPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm20MemorySSAPrinterPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/MemorySSAPrinterPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm21MemorySSAVerifierPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/MemorySSAVerifierPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm15MemorySSAWalkerE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/MemorySSAWalker.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm20MemorySSAWrapperPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/MemorySSAWrapperPass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm9MemoryUseE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/MemoryUse.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm14MemoryUseOrDefE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/MemoryUseOrDef.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm13OperandTraitsINS_9MemoryDefEEE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/OperandTraitsMemoryDef.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm13OperandTraitsINS_9MemoryPhiEEE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/OperandTraitsMemoryPhi.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm13OperandTraitsINS_9MemoryUseEEE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/OperandTraitsMemoryUse.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm13OperandTraitsINS_14MemoryUseOrDefEEE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/OperandTraitsMemoryUseOrDef.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm11PromotePassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/PromotePass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/CodeGen/CodeGenModule.cpp "-nm=_ZN4llvm19SanitizerStatReportE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/SanitizerStatReport.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/CodeGen/BackendUtil.cpp "-nm=_ZN4llvm14SymbolRewriter17RewriteDescriptorE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/SymbolRewriter/RewriteDescriptor.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/CodeGen/BackendUtil.cpp "-nm=_ZN4llvm14SymbolRewriter16RewriteMapParserE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/SymbolRewriter/RewriteMapParser.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/tools/driver/cc1_main.cpp "-nm=_ZN4llvm22UnifyFunctionExitNodesE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/UnifyFunctionExitNodes.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Linker/IRMover.cpp "-nm=_ZN4llvm20ValueMapTypeRemapperE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/ValueMapTypeRemapper.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Linker/IRMover.cpp "-nm=_ZN4llvm11ValueMapperE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/ValueMapper.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Linker/IRMover.cpp "-nm=_ZN4llvm17ValueMaterializerE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/ValueMaterializer.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm12ilist_traitsINS_12MemoryAccessEEE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/ilist_traitsMemoryAccess.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/CodeGen/BackendUtil.cpp "-nm=_ZN4llvm12ilist_traitsINS_14SymbolRewriter17RewriteDescriptorEEE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/ilist_traitsRewriteDescriptor.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm30memoryaccess_def_iterator_baseE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/memoryaccess_def_iterator_base.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm20upward_defs_iteratorE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/upward_defs_iterator.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm17LoopVectorizePassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/vectorize/LoopVectorizePass.java
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm17SLPVectorizerPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/vectorize/SLPVectorizerPass.java

# Global and static namespaces

# Static functions/variables

# Global functions/variables

# Global functions/variables for namespace as packages
${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm11reassociateltERKNS0_10ValueEntryES3_;" -static-type=ReassociateGlobals -package=org.llvm.transforms.scalar.reassociate > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/scalar/reassociate/ReassociateGlobals.java
${SPUTNIK}/contrib/JConvert/jclank.sh -body-delegate -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/CodeGen/BackendUtil.cpp ${LLVM_SRC}/llvm/tools/clang/lib/CodeGen/CGCall.cpp ${LLVM_SRC}/llvm/lib/Linker/IRMover.cpp ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp ${LLVM_SRC}/llvm/tools/clang/lib/CodeGen/SanitizerMetadata.cpp "-nm=Tpl__ZN4llvm13EmitGEPOffsetEPT_RKNS_10DataLayoutEPNS_4UserEb;_Z4llvm_SanitizerStats_h_Unnamed_enum;_ZN4llvm11MapMetadataEPKNS_6MDNodeERNS_8ValueMapIPKNS_5ValueENS_6WeakVHENS_14ValueMapConfigIS6_NS_3sys10SmartMutexILb0EEEEEEENS_10RemapFlagsEPNS_20ValueMapTypeRemapperEPNS_17ValueMaterializerE;_ZN4llvm11MapMetadataEPKNS_8MetadataERNS_8ValueMapIPKNS_5ValueENS_6WeakVHENS_14ValueMapConfigIS6_NS_3sys10SmartMutexILb0EEEEEEENS_10RemapFlagsEPNS_20ValueMapTypeRemapperEPNS_17ValueMaterializerE;_ZN4llvm13RemapFunctionERNS_8FunctionERNS_8ValueMapIPKNS_5ValueENS_6WeakVHENS_14ValueMapConfigIS5_NS_3sys10SmartMutexILb0EEEEEEENS_10RemapFlagsEPNS_20ValueMapTypeRemapperEPNS_17ValueMaterializerE;_ZN4llvm15upward_defs_endEv;_ZN4llvm16RemapInstructionEPNS_11InstructionERNS_8ValueMapIPKNS_5ValueENS_6WeakVHENS_14ValueMapConfigIS5_NS_3sys10SmartMutexILb0EEEEEEENS_10RemapFlagsEPNS_20ValueMapTypeRemapperEPNS_17ValueMaterializerE;_ZN4llvm17internalizeModuleERNS_6ModuleESt8functionIFbRKNS_11GlobalValueEEEPNS_9CallGraphE;_ZN4llvm17upward_defs_beginERKSt4pairIPNS_12MemoryAccessENS_14MemoryLocationEE;_ZN4llvm8MapValueEPKNS_5ValueERNS_8ValueMapIS2_NS_6WeakVHENS_14ValueMapConfigIS2_NS_3sys10SmartMutexILb0EEEEEEENS_10RemapFlagsEPNS_20ValueMapTypeRemapperEPNS_17ValueMaterializerE;_ZN4llvm8MapValueEPKNS_8ConstantERNS_8ValueMapIPKNS_5ValueENS_6WeakVHENS_14ValueMapConfigIS6_NS_3sys10SmartMutexILb0EEEEEEENS_10RemapFlagsEPNS_20ValueMapTypeRemapperEPNS_17ValueMaterializerE;_ZN4llvmL16scaleBranchCountEyy;_ZN4llvmL17getKnownAlignmentEPNS_5ValueERKNS_10DataLayoutEPKNS_11InstructionEPNS_15AssumptionCacheEPKNS_13DominatorTreeE;_ZN4llvmL19calculateCountScaleEy;_ZN4llvmlsERNS_11raw_ostreamERKNS_12MemoryAccessE;_ZN4llvmorENS_10RemapFlagsES0_;" -static-type=TransformsLlvmGlobals -package=org.llvm.transforms.utils > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/TransformsLlvmGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm17internalizeModuleERNS_6ModuleESt8functionIFbRKNS_11GlobalValueEEEPNS_9CallGraphE;" -static-type=InternalizeLlvmGlobals -package=org.llvm.transforms.ipo.impl > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/impl/InternalizeLlvmGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/CodeGen/CGCall.cpp "-nm=Tpl__ZN4llvm13EmitGEPOffsetEPT_RKNS_10DataLayoutEPNS_4UserEb;_ZN4llvmL17getKnownAlignmentEPNS_5ValueERKNS_10DataLayoutEPKNS_11InstructionEPNS_15AssumptionCacheEPKNS_13DominatorTreeE;" -static-type=LocalLlvmGlobals -package=org.llvm.transforms.utils.impl > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/impl/LocalLlvmGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Linker/IRMover.cpp "-nm=_ZN4llvm11MapMetadataEPKNS_6MDNodeERNS_8ValueMapIPKNS_5ValueENS_6WeakVHENS_14ValueMapConfigIS6_NS_3sys10SmartMutexILb0EEEEEEENS_10RemapFlagsEPNS_20ValueMapTypeRemapperEPNS_17ValueMaterializerE;_ZN4llvm11MapMetadataEPKNS_8MetadataERNS_8ValueMapIPKNS_5ValueENS_6WeakVHENS_14ValueMapConfigIS6_NS_3sys10SmartMutexILb0EEEEEEENS_10RemapFlagsEPNS_20ValueMapTypeRemapperEPNS_17ValueMaterializerE;_ZN4llvm13RemapFunctionERNS_8FunctionERNS_8ValueMapIPKNS_5ValueENS_6WeakVHENS_14ValueMapConfigIS5_NS_3sys10SmartMutexILb0EEEEEEENS_10RemapFlagsEPNS_20ValueMapTypeRemapperEPNS_17ValueMaterializerE;_ZN4llvm16RemapInstructionEPNS_11InstructionERNS_8ValueMapIPKNS_5ValueENS_6WeakVHENS_14ValueMapConfigIS5_NS_3sys10SmartMutexILb0EEEEEEENS_10RemapFlagsEPNS_20ValueMapTypeRemapperEPNS_17ValueMaterializerE;_ZN4llvm8MapValueEPKNS_5ValueERNS_8ValueMapIS2_NS_6WeakVHENS_14ValueMapConfigIS2_NS_3sys10SmartMutexILb0EEEEEEENS_10RemapFlagsEPNS_20ValueMapTypeRemapperEPNS_17ValueMaterializerE;_ZN4llvm8MapValueEPKNS_8ConstantERNS_8ValueMapIPKNS_5ValueENS_6WeakVHENS_14ValueMapConfigIS6_NS_3sys10SmartMutexILb0EEEEEEENS_10RemapFlagsEPNS_20ValueMapTypeRemapperEPNS_17ValueMaterializerE;_ZN4llvmorENS_10RemapFlagsES0_;" -static-type=ValueMapperLlvmGlobals -package=org.llvm.transforms.utils.impl > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/impl/ValueMapperLlvmGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/tools/clang/lib/CodeGen/BackendUtil.cpp "-nm=_ZN4llvmL16scaleBranchCountEyy;_ZN4llvmL19calculateCountScaleEy;" -static-type=InstrumentationLlvmGlobals -package=org.llvm.transforms.impl > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/impl/InstrumentationLlvmGlobals.java
    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Passes/PassBuilder.cpp "-nm=_ZN4llvm15upward_defs_endEv;_ZN4llvm17upward_defs_beginERKSt4pairIPNS_12MemoryAccessENS_14MemoryLocationEE;_ZN4llvmlsERNS_11raw_ostreamERKNS_12MemoryAccessE;" -static-type=MemorySSALlvmGlobals -package=org.llvm.transforms.utils.impl > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/utils/impl/MemorySSALlvmGlobals.java

# Static functions/variables for namespaces as packages

# Global typedefs

#${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Transforms/IPO/PassManagerBuilder.cpp "-nm=_Z28LLVMPassManagerBuilderCreate;_Z29LLVMPassManagerBuilderDispose;_Z33LLVMPassManagerBuilderSetOptLevel;_Z34LLVMPassManagerBuilderSetSizeLevel;_Z43LLVMPassManagerBuilderSetDisableUnitAtATime;_Z43LLVMPassManagerBuilderSetDisableUnrollLoops;_Z44LLVMPassManagerBuilderPopulateLTOPassManager;_Z45LLVMPassManagerBuilderUseInlinerWithThreshold;_Z47LLVMPassManagerBuilderPopulateModulePassManager;_Z48LLVMPassManagerBuilderSetDisableSimplifyLibCalls;_Z49LLVMPassManagerBuilderPopulateFunctionPassManager;_Z4wrapPN4llvm18PassManagerBuilderE;_Z6unwrapP28LLVMOpaquePassManagerBuilder;_ZL10EnableMLSM;_ZL12RunFloat2Int;_ZL14EnableGVNHoist;_ZL14RunLoadCombine;_ZL14RunPGOInstrGenB5cxx11;_ZL14RunPGOInstrUseB5cxx11;_ZL16GlobalExtensions;_ZL16RunLoopRerolling;_ZL17DisablePreInliner;_ZL18EnableLoopLoadElim;_ZL18PreInlineThreshold;_ZL18RunBBVectorization;_ZL19RunSLPVectorization;_ZL20RunLoopVectorization;_ZL21EnableLoopInterchange;_ZL21ExtraVectorizerPasses;_ZL21UseLoopVersioningLICM;_ZL24UseGVNAfterVectorization;_ZL25EnableNonLTOGlobalsModRef;_ZL28RunSLPAfterLoopVectorization;_ZL8UseCFLAA;" -static-type=PassManagerBuilderStatics -package=org.llvm.transforms.ipo.impl > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/impl/PassManagerBuilderStatics.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Transforms/IPO/PassManagerBuilder.cpp "-nm=_Z9CFLAAType;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/impl/CFLAAType.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Transforms/IPO/InlineAlways.cpp "-nm=_ZL31InitializeAlwaysInlinerPassFlag;_ZL31initializeAlwaysInlinerPassOnceRN4llvm12PassRegistryE;" -static-type=InlineAlwaysStatics -package=org.llvm.transforms.ipo.impl > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/impl/InlineAlwaysStatics.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Transforms/IPO/BarrierNoopPass.cpp "-nm=_ZN12_GLOBAL__N_111BarrierNoopE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/impl/BarrierNoop.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Transforms/IPO/BarrierNoopPass.cpp "-nm=_ZL29InitializeBarrierNoopPassFlag;_ZL29initializeBarrierNoopPassOnceRN4llvm12PassRegistryE;" -static-type=BarrierNoopPassStatics -package=org.llvm.transforms.ipo.impl > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/impl/BarrierNoopPassStatics.java
#    ${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Transforms/IPO/BarrierNoopPass.cpp "-nm=_ZN4llvm25initializeBarrierNoopPassERNS_12PassRegistryE;" -static-type=BarrierNoopPassLlvmStatics -package=org.llvm.transforms.ipo.impl > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/impl/BarrierNoopPassLlvmStatics.java
#    ${SPUTNIK}/contrib/JConvert/jclank.sh -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Transforms/IPO/BarrierNoopPass.cpp "-nm=_ZN4llvm21createBarrierNoopPassEv;" -static-type=BarrierNoopPassLlvmGlobals -package=org.llvm.transforms.impl > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/impl/BarrierNoopPassLlvmGlobals.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Transforms/IPO/ForceFunctionAttrs.cpp "-nm=_ZN12_GLOBAL__N_128ForceFunctionAttrsLegacyPassE;" > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/impl/ForceFunctionAttrsLegacyPass.java
#${SPUTNIK}/contrib/JConvert/jclank.sh -empty-body -java-options=${SPUTNIK}/modules/org.llvm.transforms/llvmToClangType ${LLVM_SRC}/llvm/lib/Transforms/IPO/Inliner.cpp "-nm=_ZL10NumDeleted;_ZL10NumInlined;_ZL12emitAnalysisN4llvm8CallSiteERKNS_5TwineE;_ZL15NumCallsDeleted;_ZL16NumMergedAllocas;_ZL20InlineCallIfPossibleRN4llvm4PassENS_8CallSiteERNS_18InlineFunctionInfoERNS_8DenseMapIPNS_9ArrayTypeESt6vectorIPNS_10AllocaInstESaISA_EENS_12DenseMapInfoIS7_EENS_6detail12DenseMapPairIS7_SC_EEEEib;_ZL21InlineHistoryIncludesPN4llvm8FunctionEiRKNS_15SmallVectorImplISt4pairIS1_iEEE;_ZL24NumCallerCallersAnalyzed;" -static-type=InlinerStatics -package=org.llvm.transforms.ipo.impl > ${SPUTNIK}/modules/org.llvm.transforms/src/org/llvm/transforms/ipo/impl/InlinerStatics.java
